NEWS.md

Work in progress, since we’re not ready for 3.7.5 yet!

Add release notes for 3.7.5

---

NEWS.md
lib/nanoc/base.rb
lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/source_data/layout.rb
lib/nanoc/base/views/item_collection.rb
lib/nanoc/base/views/layout_collection.rb
lib/nanoc/base/views/mutable_config.rb
lib/nanoc/base/views/mutable_item.rb
lib/nanoc/base/views/mutable_item_collection.rb
lib/nanoc/base/views/mutable_layout.rb
lib/nanoc/base/views/mutable_layout_collection.rb
spec/nanoc/base/views/mutable_config_spec.rb
spec/nanoc/base/views/mutable_item_collection_spec.rb
spec/nanoc/base/views/mutable_item_spec.rb
spec/nanoc/base/views/mutable_layout_collection_spec.rb
spec/nanoc/base/views/mutable_layout_spec.rb

The preprocessor needs views that can modify information.

Create mutable views for preprocessor

---

lib/nanoc/base/compilation/compiler_dsl.rb
lib/nanoc/base/source_data/identifier.rb
test/base/test_compiler_dsl.rb

Discovered through nanoc/nanoc.ws#90.

Fix #passthrough

---

lib/nanoc/cli/commands/create-site.rb
test/cli/commands/test_create_site.rb

This enables auto-pruning by default.
Fix for #589.

Auto-prune by default

---

lib/nanoc/base/views/item.rb
spec/nanoc/base/views/item_spec.rb

Let ItemView#parent return nil if parent is nil

---

lib/nanoc/cli/commands/create-site.rb

Document identifier_type in default site

---

lib/nanoc/base.rb
lib/nanoc/base/views/item.rb
lib/nanoc/base/views/item_rep_collection.rb
spec/nanoc/base/views/item_rep_collection_spec.rb
spec/nanoc/base/views/item_spec.rb

Add ItemRepCollectionView

---

lib/nanoc/base/source_data/identifier.rb
spec/nanoc/base/identifier_spec.rb

Add Identifier#ext

---

lib/nanoc/base/source_data/item.rb
lib/nanoc/base/source_data/site.rb
test/helpers/test_capturing.rb

Remove site attribute from item

---

lib/nanoc/base/result_data/item_rep.rb
lib/nanoc/base/views/item.rb
lib/nanoc/base/views/item_rep.rb
spec/nanoc/base/views/item_rep_spec.rb
spec/nanoc/base/views/item_spec.rb
test/base/test_item_rep.rb

This moves notifications from `ItemRep` into the views.

Notify in views view

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/repos/site_loader.rb
lib/nanoc/base/source_data/data_source.rb
lib/nanoc/base/source_data/site.rb
lib/nanoc/cli/command_runner.rb
lib/nanoc/cli/commands/prune.rb
lib/nanoc/data_sources/filesystem.rb
test/base/test_compiler.rb
test/base/test_outdatedness_checker.rb
test/base/test_site.rb
test/cli/commands/test_create_site.rb
test/data_sources/test_filesystem_unified.rb
test/extra/checking/checks/test_stale.rb
test/helpers/test_rendering.rb

This isn’t quite right (yet). Reverting for the time being.
Reverts nanoc/nanoc#636

Revert "Full site loader"

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/repos/site_loader.rb
lib/nanoc/base/source_data/data_source.rb
lib/nanoc/base/source_data/site.rb
lib/nanoc/cli/command_runner.rb
lib/nanoc/cli/commands/prune.rb
lib/nanoc/data_sources/filesystem.rb
spec/nanoc/base/repos/site_loader_spec.rb
test/base/test_compiler.rb
test/base/test_outdatedness_checker.rb
test/base/test_site.rb
test/cli/commands/test_create_site.rb
test/data_sources/test_filesystem_unified.rb
test/extra/checking/checks/test_stale.rb
test/helpers/test_rendering.rb

Full site loader, attempt 2

---

lib/nanoc/filters/relativize_paths.rb

Because Code Climate made me feel guilty.

Clean up relativize_paths filter

---

lib/nanoc/base/compilation/compiler.rb
test/base/test_compiler.rb

Potential fix for #665.
Replaces #666.

Error on identical output paths

---

lib/nanoc/cli/commands/create-site.rb
lib/nanoc/extra/checking/checks/external_links.rb
test/extra/checking/checks/test_external_links.rb

Exclude URLs from external links check

---

lib/nanoc/base/entities/pattern.rb
spec/nanoc/base/entities/pattern_spec.rb

Improve Pattern.from error message

---

lib/nanoc/base/views/mixins/document_view_mixin.rb
spec/nanoc/base/entities/document_spec.rb
spec/nanoc/base/views/document_view_spec.rb

Fix comparing document view with other

---

lib/nanoc/filters/rdiscount.rb

Fix :rdiscount params documentation

---

lib/nanoc/base/views/mixins/mutable_document_view_mixin.rb
spec/nanoc/base/views/mutable_document_view_spec.rb

Add #identifier= to mutable document views

---

spec/nanoc/helpers/blogging_spec.rb
spec/spec_helper.rb

This is an attempt at writing an API to make testing helpers easier.
A test using this helper API would start by creating a helper context (which is used for “setting the scene” by creating items, reps, etc), and a helper (which is the reified helper module). For example:
```ruby
describe Nanoc::Helpers::Blogging do
let(:ctx) { HelperContext.new(described_class) }
let(:helper) { ctx.helper }
```
Next up is the subject. This calls a method on `helper`, which, as mentioned above, is an object that includes the helper module:
```ruby
describe '#articles' do
subject { helper.articles }
```
To set up the context, we use methods like `#create_item` on `ctx` (the helper context). We have to use `#let!` rather than `#let` (notice the bang) to prevent them from being lazily evaluated. In this …

Add API for testing helpers

---

lib/nanoc/base/services/executor.rb
spec/nanoc/base/services/executor_spec.rb

Fixes #771.
I’ve opted to fix this in the upcoming 4.1 release instead, since that one’s around the door.
CC @hilohiro — this is the bug you’re experiencing.

Wrap `@layout` in a view

---

lib/nanoc/extra/pruner.rb
spec/nanoc/regressions/gh_776_spec.rb

Do not prune other snapshots

---

lib/nanoc/cli/cleaning_stream.rb
lib/nanoc/cli/stream_cleaners/ansi_colors.rb
test/cli/test_cleaning_stream.rb

Call #to_s before printing on cleaning stream

---

lib/nanoc/cli/command_runner.rb
spec/nanoc/cli/commands/shell_spec.rb
test/cli/commands/test_deploy.rb

Preprocess before deploy/check

---

lib/nanoc.rb
lib/nanoc/base/compilation/filter.rb
lib/nanoc/base/entities/configuration.rb
lib/nanoc/base/services/item_rep_writer.rb
lib/nanoc/base/views/config_view.rb
lib/nanoc/base/views/mixins/document_view_mixin.rb
lib/nanoc/cli/ansi_string_colorizer.rb
lib/nanoc/cli/commands/create-site.rb
lib/nanoc/cli/commands/show-plugins.rb
lib/nanoc/cli/error_handler.rb
lib/nanoc/cli/logger.rb
lib/nanoc/extra/checking/checks/mixed_content.rb
lib/nanoc/extra/checking/runner.rb
lib/nanoc/extra/deployers/rsync.rb
lib/nanoc/extra/jruby_nokogiri_warner.rb
lib/nanoc/extra/link_collector.rb
lib/nanoc/filters/colorize_syntax.rb
lib/nanoc/filters/relativize_paths.rb
lib/nanoc/version.rb

This prevents accidental modification.

Freeze constants

---

lib/nanoc/extra/checking/checks/stale.rb
spec/nanoc/regressions/gh_809_spec.rb

Let stale check handle non-final snapshots

---

lib/nanoc/extra/checking/runner.rb
spec/nanoc/regressions/gh_804_spec.rb

Fix crash in check when subject is nil

---

lib/nanoc/helpers/link_to.rb
test/helpers/test_link_to.rb

Check link_to type

---

lib/nanoc/base/checksummer.rb

This splits out behaviours into separate behaviour classes, making the overall structure of `#update` more clear.

Refactor checksummer

---

lib/nanoc/rule_dsl/action_provider.rb
spec/nanoc/regressions/gh_828_spec.rb

Disable dependency tracker in preprocessor

---

lib/nanoc/cli/commands/check.rb
spec/nanoc/regressions/gh_841_spec.rb

Preprocess before running check

---

lib/nanoc/base/services/item_rep_router.rb
spec/nanoc/base/services/item_rep_router_spec.rb

Strip index.html only if it is a full component

---

.travis.yml
Gemfile

Run JRuby on Travis CI

---

lib/nanoc/base/memoization.rb

I assume that checking `#weakref_alive?` is not a strong guarantee that the ref is alive. Perhaps the ref dies after the call, but before it’s accessed?
Needs more rigorous (load) testing.
Fixes #863.

Fix WeakRef::RefError

---

lib/nanoc/cli/command_runner.rb
lib/nanoc/cli/commands/check.rb
lib/nanoc/cli/commands/deploy.rb
lib/nanoc/cli/commands/prune.rb
lib/nanoc/cli/commands/show-data.rb
spec/nanoc/regressions/gh_867_spec.rb

Let show-data run preprocessor

---

lib/nanoc/spec.rb

Allow creating named reps in specs

---

lib/nanoc/base/entities/identifier.rb
spec/nanoc/base/entities/identifier_spec.rb

Fixes #873 (or at least the error message).

Fix message of invalid prefix error

---

spec/nanoc/regressions/gh_882_spec.rb

This is a test to ensure that the example give on the Nanoc web site is correct (see https://github.com/nanoc/nanoc.ws/pull/177).
Also see #882, #898.

Add spec for #882

---

lib/nanoc/rule_dsl/recording_executor.rb
spec/nanoc/rule_dsl/recording_executor_spec.rb

Raise proper error when passing symbol to #layout

---

lib/nanoc/rule_dsl/rule_memory_calculator.rb
spec/nanoc/rule_dsl/rule_memory_calculator_spec.rb

Better no layout rule memory error

---

lib/nanoc/base/plugin_registry.rb
spec/nanoc/base/plugin_registry_spec.rb
spec/nanoc/regressions/gh_928_spec.rb

Fix finding root class in PluginRegistry

---

lib/nanoc/base/compilation/dependency_tracker.rb
lib/nanoc/helpers/rendering.rb
spec/nanoc/helpers/rendering_spec.rb
test/base/test_dependency_tracker.rb

Fix checking outdatedness of LayoutView

---

Gemfile
lib/nanoc/extra/checking/checks/external_links.rb

Use [parallel](https://github.com/grosser/parallel) gem, rather than rolling our own.

Extract parallel code

---

scripts/release

Remove the double negation in script/release

Remove double negation in script/release

---

lib/nanoc/base/checksummer.rb
spec/nanoc/base/checksummer_spec.rb
spec/nanoc/regressions/gh_981_spec.rb

Fix for #981.
This adds a checksum for `RuleContext` and `ItemRep`.

Add checksums for RuleContext and ItemRep

---

lib/nanoc/cli/commands/view.rb
spec/nanoc/cli/commands/view_spec.rb

Use config index_filenames in view command

---

lib/nanoc/base/services/checksummer.rb
spec/nanoc/base/checksummer_spec.rb

Define Nanoc::Int::Context checksum

---

lib/nanoc/base/services/compiler.rb
spec/nanoc/regressions/gh_1031_spec.rb

Recompile all reps of outdated items

---

lib/nanoc/base/services/compiler.rb
lib/nanoc/base/services/executor.rb
lib/nanoc/rule_dsl/recording_executor.rb
lib/nanoc/rule_dsl/rule_context.rb
lib/nanoc/rule_dsl/rule_memory_calculator.rb
spec/nanoc/base/services/executor_spec.rb
spec/nanoc/rule_dsl/recording_executor_spec.rb
spec/nanoc/rule_dsl/rule_context_spec.rb

This won’t quite make the executor stateless just yet, but it goes in the right direction.

Simplify executor

---

lib/nanoc/base/services/compiler.rb
spec/nanoc/regressions/gh_1047_spec.rb

Store compiled content cache, even on exception

---

lib/nanoc/data_sources/filesystem.rb
spec/nanoc/regressions/gh_1022_spec.rb
test/data_sources/test_filesystem.rb

Allow periods in identifiers for full identifiers

---

lib/nanoc.rb
lib/nanoc/helpers/xml_sitemap.rb
test/helpers/test_xml_sitemap.rb

Escape URLs in sitemaps (fixes #1052)

---

lib/nanoc/base/views/mixins/mutable_document_view_mixin.rb
spec/nanoc/base/views/mutable_document_view_spec.rb

This allows the raw content of an item to be changed during preprocessing.
CC @dieterdepaepe — this is for you

Add #raw_content= to views

---

lib/nanoc/base/entities/item_rep.rb
lib/nanoc/base/views/item_rep_view.rb
spec/nanoc/base/entities/item_rep_spec.rb
spec/nanoc/base/views/item_rep_view_spec.rb

This will allow querying whether a given rep has a given snapshot:
```ruby
<% if @rep.snapshot?(:latex) %>
<link rel=stylesheet href=latex.css>
<% end %>
```
CC @gpakosz — This will be useful for you.

Add #snapshot?

---

lib/nanoc/base/entities/identifiable_collection.rb
lib/nanoc/base/views/mutable_identifiable_collection_view.rb
lib/nanoc/base/views/mutable_item_collection_view.rb
lib/nanoc/base/views/mutable_layout_collection_view.rb
lib/nanoc/rule_dsl/action_provider.rb
lib/nanoc/spec.rb
spec/nanoc/base/checksummer_spec.rb
spec/nanoc/base/compiler_spec.rb
spec/nanoc/base/entities/site_spec.rb
spec/nanoc/base/services/compiler/stages/compile_reps_spec.rb
spec/nanoc/base/views/identifiable_collection_view_spec.rb
spec/nanoc/base/views/item_view_spec.rb
spec/nanoc/base/views/mutable_identifiable_collection_view_spec.rb
spec/nanoc/base/views/mutable_item_collection_view_spec.rb
spec/nanoc/base/views/mutable_layout_collection_view_spec.rb
spec/nanoc/cli/commands/show_data_spec.rb
spec/nanoc/cli/commands/show_rules_spec.rb
spec/nanoc/rule_dsl/rule_context_spec.rb
test/base/test_item_array.rb
test/helpers/test_xml_sitemap.rb

This removes
so that `IdentifiableCollection` becomes immutable.

Make IdentifiableCollection immutable

---

lib/nanoc/base/services/filter.rb
spec/nanoc/base/filter_spec.rb
spec/nanoc/regressions/gh_1093_spec.rb

Make Filter#depend_on depend on all reps, not just one

---

lib/nanoc/base/views/item_rep_view.rb
lib/nanoc/helpers/xml_sitemap.rb
spec/nanoc/base/views/item_rep_view_spec.rb
spec/nanoc/regressions/gh_1097_spec.rb

Let #raw_path require rep to be compiled

---

lib/nanoc/base/entities/identifiable_collection.rb
spec/nanoc/base/entities/identifiable_collection_spec.rb
spec/nanoc/regressions/gh_1100_spec.rb

Fix: Do not change @objects type in #delete_if

---

lib/nanoc/cli/commands/compile.rb
spec/nanoc/regressions/gh_1107_spec.rb

Fix undefined method reverse_each

---

lib/nanoc/spec.rb
spec/nanoc/helpers/blogging_spec.rb
spec/nanoc/helpers/capturing_spec.rb
spec/nanoc/helpers/child_parent_spec.rb
spec/nanoc/helpers/filtering_spec.rb
spec/nanoc/helpers/link_to_spec.rb
spec/nanoc/helpers/rendering_spec.rb
spec/nanoc/spec_spec.rb

Fixes #1110.
This breaks the existing helper tests, but that is expected!

Make HelperContext#create_* return self

---

lib/nanoc/cli/commands/compile.rb
lib/nanoc/cli/stream_cleaners/utf8.rb
spec/nanoc/cli/commands/compile/timing_recorder_spec.rb
spec/nanoc/cli/stream_cleaners/utf8_spec.rb

Use bow drawing characters

---

lib/nanoc/base/services/compiler.rb
lib/nanoc/cli/commands/compile.rb
spec/nanoc/cli/commands/compile/timing_recorder_spec.rb

Record telemetry for stages

---

lib/nanoc/base/services/compiler/phases/abstract.rb
lib/nanoc/base/services/compiler/phases/cache.rb
lib/nanoc/base/services/compiler/phases/mark_done.rb
lib/nanoc/base/services/compiler/phases/recalculate.rb
lib/nanoc/base/services/compiler/phases/resume.rb
lib/nanoc/base/services/compiler/phases/write.rb
spec/nanoc/base/services/compiler/phases/abstract_spec.rb

Derive phase names from class

---

lib/nanoc/base/services/outdatedness_checker.rb
lib/nanoc/base/services/outdatedness_rule.rb
lib/nanoc/cli/commands/compile.rb
spec/nanoc/cli/commands/compile/timing_recorder_spec.rb

Add outdatedness rules telemetry

---

lib/nanoc/base/services/outdatedness_rules.rb
spec/nanoc/base/services/outdatedness_rules_spec.rb
spec/nanoc/regressions/gh_1134_spec.rb

Check existence of files of all snapshots

---

lib/nanoc/filters/colorize_syntax.rb
lib/nanoc/filters/colorize_syntax/colorizers.rb

This splits out the colorizers into individual classes—a refactoring I’ve been wanting to make for a long time!

Refactor :colorize_syntax filter

---

lib/nanoc/base/entities/identifiable_collection.rb
lib/nanoc/base/repos/dependency_store.rb
lib/nanoc/base/services/compiler/stages/preprocess.rb
lib/nanoc/base/services/compiler_loader.rb
spec/nanoc/base/compiler_spec.rb
spec/nanoc/base/entities/identifiable_collection_spec.rb
spec/nanoc/base/repos/dependency_store_spec.rb
spec/nanoc/base/services/compiler/stages/compile_reps_spec.rb
spec/nanoc/base/services/dependency_tracker_spec.rb
spec/nanoc/base/services/outdatedness_checker_spec.rb
spec/nanoc/base/services/outdatedness_rules_spec.rb
spec/nanoc/base/views/document_view_spec.rb
spec/nanoc/base/views/item_rep_view_spec.rb
spec/nanoc/base/views/item_view_spec.rb
spec/nanoc/cli/commands/show_data_spec.rb
test/base/test_dependency_tracker.rb
test/filters/test_xsl.rb

This turns the accidentally quadratic dependency loading algorithm into a linear one. Oops!

Optimise loading dependencies

---

lib/nanoc/base/entities/directed_graph.rb
spec/nanoc/base/directed_graph_spec.rb

Handle tails in dependency cycles

---

lib/nanoc/base/errors.rb
spec/nanoc/base/errors/dependency_cycle_spec.rb

Fix ordering of dependency cycle

---

lib/nanoc/helpers/blogging.rb
test/helpers/test_blogging.rb

Identical to #1172 (thanks @christoper) but with more tests and some fixes.

Add xml:base support

---

spec/nanoc/cli_spec.rb

Ensure commands have no conflicting options

---

lib/nanoc/base/views/mixins/mutable_document_view_mixin.rb
spec/nanoc/base/views/mutable_document_view_spec.rb
spec/nanoc/regressions/gh_1216_spec.rb

Invalidate checksum_data when mutated

---

lib/nanoc/base/services/compiler.rb
nanoc.manifest
spec/nanoc/regressions/gh_1248_spec.rb

Pass non-preprocessed output_dirs to cleanup stage

---

Gemfile
lib/nanoc/cli/commands/view.rb

This lets `nanoc view` use `Adsf::Server`, which already does what `nanoc view` does.

Use Adsf::Server

---

lib/nanoc/filters/erubi.rb
test/filters/test_erubi.rb

Add filename to erubi exceptions

---

nanoc-live/lib/nanoc/live.rb
nanoc-live/lib/nanoc/live/commands/live.rb
nanoc-live/nanoc-live.manifest
nanoc/lib/nanoc/cli.rb
nanoc/nanoc.manifest

Move live command from nanoc to nanoc-live

---

.rubocop.yml
Gemfile
Rakefile
nanoc-external/.rspec
nanoc-external/LICENSE
nanoc-external/NEWS.md
nanoc-external/README.md
nanoc-external/Rakefile
nanoc-external/lib/nanoc-external.rb
nanoc-external/lib/nanoc/external.rb
nanoc-external/lib/nanoc/external/filter.rb
nanoc-external/lib/nanoc/external/version.rb
nanoc-external/nanoc-external.gemspec
nanoc-external/nanoc-external.manifest
nanoc-external/spec/filter_spec.rb
nanoc-external/spec/manifest_spec.rb
nanoc-external/spec/spec_helper.rb
scripts/release

Integrate nanoc-external

---

nanoc/lib/nanoc/base/views/identifiable_collection_view.rb
nanoc/spec/nanoc/base/views/support/identifiable_collection_view_examples.rb

Let #find_all take a block (fixes #1284)

---

nanoc/lib/nanoc.rb
nanoc/lib/nanoc/rule_dsl/action_recorder.rb
nanoc/lib/nanoc/rule_dsl/compilation_rule_context.rb
nanoc/spec/nanoc/integration/write_nil_spec.rb
nanoc/spec/nanoc/rule_dsl/action_recorder_spec.rb
nanoc/spec/nanoc/rule_dsl/rule_context_spec.rb

Let `write nil` skip routing rule

---

nanoc/lib/nanoc/cli.rb
nanoc/spec/nanoc/cli_spec.rb

See [no-color.org](http://no-color.org/).

Honor NO_COLOR

---

nanoc/lib/nanoc/cli/commands/shell.rb

Fixes #1309.
God knows how to test this.

Handle SIGINT in shell

---

nanoc/lib/nanoc/data_sources/filesystem.rb
nanoc/spec/nanoc/data_sources/filesystem_spec.rb
nanoc/spec/nanoc/regressions/gh_1358_spec.rb

Fix checksumming of binary items in filesystem data source

---

.rubocop.yml
.travis.yml
common/spec/spec_helper_foot.rb
nanoc-external/nanoc-external.gemspec
nanoc-live/nanoc-live.gemspec
nanoc/lib/nanoc/base/entities/identifier.rb
nanoc/lib/nanoc/checking/checks/external_links.rb
nanoc/lib/nanoc/cli/error_handler.rb
nanoc/lib/nanoc/data_sources/filesystem.rb
nanoc/lib/nanoc/data_sources/filesystem/parser.rb
nanoc/lib/nanoc/filters/colorize_syntax.rb
nanoc/lib/nanoc/filters/less.rb
nanoc/lib/nanoc/filters/relativize_paths.rb
nanoc/nanoc.gemspec
nanoc/test/helper.rb
scripts/release

Ruby 2.3 is out of normal maintenance.

Drop support for Ruby 2.3

---

nanoc/lib/nanoc/cli/commands/compile_listeners/timing_recorder.rb
nanoc/spec/nanoc/cli/commands/compile/file_action_printer_spec.rb

Refactor: Extract TimingRecord#setup_phase_notifications

---

nanoc/lib/nanoc/cli/commands/compile_listeners/debug_printer.rb

* New: Log phase changes
* Improved: Better rep name printing
* New: Colored log messages

Improve debug logging

---

nanoc/lib/nanoc/helpers/blogging.rb
nanoc/test/helpers/test_blogging.rb

Identical to ##1415 but with tests.

Add atom:link[type] attributes (with tests)

---

guard-nanoc/Rakefile
nanoc-core/Rakefile
nanoc-external/Rakefile
nanoc-live/Rakefile
nanoc/Rakefile

The JUnit output could be interesting, but is not working at the moment, and gives no useful results.

Use regular RSpec output on CI

---

nanoc/lib/nanoc/base/views/config_view.rb
nanoc/spec/nanoc/base/views/config_view_spec.rb

Usage example:
<p>Running in <%= @config.env_name %>.</p>
Closes nanoc/features#52.

Add #env_name to ConfigView

---

nanoc/lib/nanoc/base/views/identifiable_collection_view.rb
nanoc/spec/nanoc/base/views/support/identifiable_collection_view_examples.rb

Let #find_all yield item views, not item objects

---

nanoc/lib/nanoc/cli/commands/compile_listeners/diff_generator.rb
nanoc/spec/nanoc/cli/commands/compile/diff_generator_spec.rb

This fixes an issue where the generated diff would have missing hunks.

Fix diff generation

---

.github/workflows/ruby.yml

As it says on the tin.
(Add issue IDs for related issues here.)

Re-add CI using GitHub actions

---

common/spec/spec_helper_foot_core.rb
nanoc-core/spec/nanoc/core/temp_filename_factory_spec.rb

This should hopefully fix the tests on GitHub as well.
n/a
https://github.com/rspec/rspec-core/issues/2064

Fix deadlock

---

.github/workflows/ruby.yml

This triggers builds for PRs as well, rather than just pushes.
n/a
n/a

Run GitHub actions for PRs

---

.github/workflows/ruby.yml

As it says in the title. I missed this earlier.
n/a
n/a

Run Rubocop on GitHub CI

---

.rubocop.yml
nanoc-core/lib/nanoc/core/temp_filename_factory.rb
nanoc-deploying/spec/nanoc/deploying/command_runners/deploy_spec.rb
nanoc/spec/nanoc/helpers/filtering_spec.rb

This enables new RuboCop cops. These new cops are disabled by default.
n/a
n/a

Enable new RuboCop cops

---

nanoc-core/lib/nanoc/core/dependency_props.rb
nanoc-core/lib/nanoc/core/dependency_store.rb
nanoc-core/lib/nanoc/core/document.rb
nanoc-core/lib/nanoc/core/item.rb
nanoc-core/lib/nanoc/core/layout.rb
nanoc-core/lib/nanoc/core/outdatedness_checker.rb

This is a continuation of #1602, finding bottlenecks and optimising them.
n/a

 Improve performance

---

nanoc/lib/nanoc/orig_cli/commands/show-rules.rb

This command takes no arguments.

Fix show-rules usage

---

.github/workflows/ruby.yml

Update the GitHub workflow to also test on Ruby 3.2 preview 3.
n/a
n/a

Test on Ruby 3.2 preview 3

---

Gemfile

Allow slim 5.x

---

common/spec/spec_helper_foot_core.rb
nanoc-checking/lib/nanoc/checking/command_runners/check.rb
nanoc-checking/lib/nanoc/checking/runner.rb
nanoc-cli/lib/nanoc/cli/commands/show-data.rb
nanoc-core/lib/nanoc/core/filter.rb
nanoc-core/lib/nanoc/core/outdatedness_checker.rb
nanoc-core/lib/nanoc/core/outdatedness_rules/attributes_modified.rb
nanoc/lib/nanoc/data_sources/filesystem.rb
nanoc/lib/nanoc/filters/kramdown.rb
nanoc/lib/nanoc/rule_dsl/action_provider.rb

This removes all uses of `#any?` that could have been `#empty?`. The latter is faster.

Replace #any? with #empty? where possible

---

nanoc-core/lib/nanoc/core/basic_outdatedness_checker.rb

Because `#outdatedness_status_for` can be called with an item and an item rep, it can happen that the outdatedness of an item rep is calculated twice: once for the item rep, and once for the item for that item rep.
This change prevents that double calculation. The memoization that was already there was not helpful as it was right there.
> [!tip]
> Best viewed with whitespace turned off in the diff.

Remove potential redundant outdatedness calc check
