Gemfile
nanoc.gemspec

The code itself does not require any changes for Ruby 2.2, but our Gemfile wasn’t ready to handle Ruby 2.2.
**Blocked on new Bundler version.** Bundler 1.7.9 doesn’t support Ruby 2.2 yet.

Add Ruby 2.2 support

---

.travis.yml

This is necessary so that Travis uses the most recent Bundler version, 1.7.10, since that is what the gemspec requires.

Upgrade Bundler before install

---

lib/nanoc/extra/checking/checks/css.rb
lib/nanoc/extra/checking/checks/html.rb
test/extra/checking/checks/test_css.rb
test/extra/checking/checks/test_html.rb
test/fixtures/vcr_cassettes/css_run_parse_error.yml

This improves the error messages generated by the HTML and CSS validators.
Potential fix for #484. CC @dgmstuart
Example for `h1 { coxlor: rxed; }`:
```
line 1: Property coxlor doesn't exist: h1 { coxlor: rxed; }
```
Contrast this with before:
```
Property coxlor doesn't exist
```
Example for `h1 { ; {`:
```
line 1: Parse Error: h1 { ; {
```
Contrast this with before:
```
Parse Error
```

Improve HTML/CSS validator error messages

---

lib/nanoc/base/checksummer.rb
test/base/checksummer_spec.rb

Fix for #469. Instead of preventing items and layouts in attributes, we can allow them and let the checksummer properly deal with it.
PR #507 had a different implementation, but too much like a hack.

Bound recursive checksumming

---

lib/nanoc/filters/kramdown.rb
test/filters/test_kramdown.rb

Potential fix for #459.
The warnings are not particularly useful, since they do not contain line number information; that information is unfortunately not provided by kramdown yet.

Print kramdown warnings

---

lib/nanoc/cli/commands/create-site.rb
test/cli/commands/test_create_site.rb

Fix crash when compiling extensionless binary items

---

lib/nanoc/helpers/blogging.rb
test/helpers/test_blogging.rb

Potential fix for #533.
This also fixes the incorrect default for the `:articles` option.

Add option to preserve order in Atom feed

---

lib/nanoc/filters/pandoc.rb
test/filters/test_pandoc.rb

Potential fix for #526.
It is now possible to call Pandoc like this:
```ruby
filter :pandoc, args: [:s, {:f => :markdown, :to => :html}, 'no-wrap', :toc]
```
I don’t think this breaks backwards compatibility, even though the filter’s method signature has changed, because it was never possible to call the filter in a different way.
CC @ghiknt

Allow generic Pandoc options with :args

---

lib/nanoc/extra/checking/checks.rb
lib/nanoc/extra/checking/checks/mixed_content.rb
lib/nanoc/extra/link_collector.rb
test/extra/checking/checks/test_mixed_content.rb

Commit message:
> This check ensures that resources embedded within HTML documents are not
> requested using a protocol that degrades the security of the original
> connection. This avoids "mixed content" warnings in browsers that
> enforce consistent protocols, and it precludes the leaking of private
> information in browsers that do not.
Resolves gh-542

Implement "Mixed Content" check

---

lib/nanoc/base/result_data/item_rep.rb
test/base/test_item_rep.rb

Fix for #537.
The `:pre` snapshot can now be accessed within the item itself, provided that the `:post` snapshot is present (because at that point, the `:pre` snapshot stops moving).
The implementation of the fix in this PR is conceptually the same as in the aforementioned bug, but refactored.
CC @nanoc/contributors @jethrogb

Allow acessing :pre snapshot in item itself

---

lib/nanoc/base/compilation/item_rep_recorder_proxy.rb
test/base/test_item_rep_recorder_proxy.rb

The following does not raise an error, but should:
```ruby
snapshot(:foo, stuff: :giraffe)
snapshot(:foo, stuff: :donkey)
```
The following does raise an error, but should not:
```ruby
snapshot(:foo)
snapshot(:bar)
```
The reason is that uniqueness is tested on the *second* argument (params), but should be on the first (name).

Fix double snapshot creation error

---

lib/nanoc/base/result_data/item_rep.rb
test/base/test_item_rep.rb

Second part of the fix for #537.
This PR has two commits:
1. The fix itself, which consists of recording the `:pre` snapshot in the `snapshots` instance variable (which is filled in only with data from explicit snapshots), and let `#compiled_content` use the snapshots variable to determine whether the `:pre` snapshot is usable.
2. Some cleanup (e.g. renaming `snapshot` to `snapshot_name` to avoid confusion).
The code related to the fix isn’t as nice as it could be:
* Ideally, I’d redo the `snapshots` instance variable to be a hash instead of an array (not sure why it is an array in the first place) but that breaks backwards compatibility in the API. :(
* The `snapshots` instance variable is a bit weird anyway. It is used to check whether `#compiled_content` is trying to access a snapshot …

Allow accessing :pre snapshot inside layout

---

test/base/temp_filename_factory_spec.rb

The tests for `Nanoc::TempFilenameFactory` occasionally fail because other tests pollute the data that these tests depend on.
This PR resolves the problem by creating a new  `Nanoc::TempFilenameFactory`, rather than relying on the singleton.
This is not a bug; it’s simply tests being flaky.
Replaces #550 (code identical, but this time on `release-3.8.x` instead of `release-3.7.x`).

Create new temp filename factory for testing

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/compilation/item_rep_proxy.rb
lib/nanoc/base/compilation/outdatedness_checker.rb
lib/nanoc/base/compilation/rules_collection.rb
lib/nanoc/base/core_ext/array.rb
lib/nanoc/base/core_ext/hash.rb
lib/nanoc/base/core_ext/pathname.rb
lib/nanoc/base/core_ext/string.rb
lib/nanoc/base/source_data/code_snippet.rb
lib/nanoc/base/source_data/item.rb
lib/nanoc/base/source_data/layout.rb
lib/nanoc/base/source_data/site.rb
lib/nanoc/base/views/item.rb
lib/nanoc/data_sources/filesystem_unified.rb
lib/nanoc/data_sources/filesystem_verbose.rb
lib/nanoc/data_sources/static.rb
lib/nanoc/helpers/rendering.rb
test/base/core_ext/array_spec.rb
test/base/core_ext/hash_spec.rb
test/base/core_ext/pathname_spec.rb
test/base/core_ext/string_spec.rb
test/data_sources/test_static.rb

This will allow us to get rid of the monkeypatched methods, and explicitly break when the old names are used.

Rename internal monkey-patched methods

---

lib/nanoc/base.rb
lib/nanoc/base/compilation/compiler_dsl.rb
lib/nanoc/base/compilation/rule.rb
lib/nanoc/base/compilation/rules_collection.rb
lib/nanoc/base/pattern.rb
nanoc.gemspec
spec/nanoc/base/pattern_spec.rb
test/base/test_compiler.rb
test/base/test_compiler_dsl.rb
test/base/test_rule.rb

This adds glob patterns to nanoc 4. They are not super useful yet, because identifiers are still old-style (without extensions), but it is a good step forward.
Also, I guess I lied about nanoc 4 not getting new features!
Note that `File::FNM_EXTGLOB` is only available in Ruby 2.0 and up. Because of this, nanoc now depends on Ruby ≥ 2.0.0. (This should be fine, since Ruby 1.9.3 reached end-of-life status last February.)
Documentation for this new feature:
nanoc 4 supports using globs. Globs are more powerful than nanoc’s original pattern syntax, and they are also more commonplace, such as in Unix shells.
To enable globs, set `pattern_syntax` to `"glob"` in the configuration. For example:
```yaml
pattern_syntax: "glob"
```
The three most useful wildcards are the following:
`*`
: Matches any …

Glob patterns

---

lib/nanoc/base/views/config.rb
lib/nanoc/base/views/item.rb
lib/nanoc/base/views/item_collection.rb
lib/nanoc/base/views/mutable_item.rb
lib/nanoc/base/views/mutable_item_collection.rb
spec/nanoc/base/views/config_spec.rb
spec/nanoc/base/views/item_collection_spec.rb
spec/nanoc/base/views/item_spec.rb
spec/nanoc/base/views/mutable_item_collection_spec.rb
spec/nanoc/base/views/mutable_item_spec.rb

Fixes for #570.
Two ugly things:
* The dependency tracking support. Having to evaluate `@item[key]` just so the dependency tracking doesn’t break is pretty icky.
* The amount of duplication. I couldn’t find a clean and non-intrusive way to implement this.
I’m okay with both ugly bits, because they’re abstracted away and we can refactor this later. (I’d *love* to refactor the dependency tracking out of `Nanoc::Int::Item` and into the view classes.)

View API convenience methods

---

lib/nanoc/base/views/item.rb
lib/nanoc/base/views/item_collection.rb
lib/nanoc/base/views/item_rep.rb
lib/nanoc/base/views/layout.rb
lib/nanoc/base/views/layout_collection.rb
lib/nanoc/base/views/mutable_config.rb
lib/nanoc/base/views/mutable_item.rb
lib/nanoc/base/views/mutable_item_collection.rb
lib/nanoc/base/views/mutable_layout.rb
lib/nanoc/base/views/mutable_layout_collection.rb
spec/nanoc/base/views/item_collection_spec.rb
spec/nanoc/base/views/layout_collection_spec.rb
spec/nanoc/base/views/mutable_item_collection_spec.rb
spec/nanoc/base/views/mutable_item_spec.rb
spec/nanoc/base/views/mutable_layout_collection_spec.rb

This adds documentation to the view API where it was missing or incomplete.
**Also:**
- I added specs where necessary and fixed some issues—all discovered while writing documentation.
- I removed `#concat`, because it doesn’t make sense (there is no way to get a collection of items that isn’t already in the site).

Document + fix view API

---

lib/nanoc/base/views/layout_collection.rb
lib/nanoc/helpers/rendering.rb
spec/nanoc/base/views/layout_collection_spec.rb
spec/nanoc/base/views/mutable_layout_collection_spec.rb
test/helpers/test_rendering.rb

This lets `#render` take a glob as its argument, e.g. `render '/page.*'`
For this to work, there’s now `LayoutCollectionView#[]`. Unfortunately, this makes it clear that the collection views are starting to show a serious issue of code duplication.

Fix rendering helper

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/compilation/filter.rb
lib/nanoc/base/views/item.rb
lib/nanoc/base/views/item_rep.rb
lib/nanoc/base/views/site.rb
lib/nanoc/helpers/capturing.rb
lib/nanoc/helpers/rendering.rb
test/helpers/test_capturing.rb
test/helpers/test_rendering.rb

These private methods were intended for compatibility with existing code, but do not belong there any longer. This PR also fixed some issues uncovered while removing these private methods.
Two methods that haven’t been removed and will likely become part of the public API at some point:
* `ItemRep#binary?`
* `ItemRep#raw_path`

Remove private methods in views

---

lib/nanoc/cli/commands/create-site.rb
test/cli/commands/test_create_site.rb

Had issues when moving from Jekyll to nanoc with Github Pages where it didn't properly detect if there was a site that existed already.
I'm open to suggestions where detecting the presence of 'nanoc.yaml' assumes a site exists.

Allows creation of site in current directory

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/source_data/item_array.rb
lib/nanoc/base/views/item_collection.rb
spec/nanoc/base/views/item_collection_spec.rb
spec/nanoc/base/views/layout_collection_spec.rb
test/base/test_compiler.rb
test/base/test_item_array.rb
test/base/test_outdatedness_checker.rb
test/base/test_site.rb
test/helpers/test_breadcrumbs.rb
test/helpers/test_xml_sitemap.rb

`Nanoc::Int::ItemArray` is icky (too array-like, with too much magic delegation). This improves ItemArray to be more in line with the API that `ItemCollectionView` exposes.
From the public API point of view, only the removal of `#at`, `#[]` returning an array, and integer indexing has changed.
Future work could include renaming `ItemArray` to `ItemCollection`, but for the sake of not diverging too much from 3.x, I’ll keep it this way for now.

Improve Nanoc::Int::ItemArray

---

lib/nanoc/cli/commands/create-site.rb
test/cli/commands/test_create_site.rb

Continuation of #549. Allows --force flag to override the site-already-exists safeguard

Adds --force option to create site in non-empty directory

---

lib/nanoc/base/source_data/site.rb
test/base/test_compiler_dsl.rb
test/base/test_outdatedness_checker.rb
test/cli/commands/test_compile.rb
test/cli/commands/test_prune.rb
test/extra/checking/checks/test_stale.rb
test/helper.rb

I don’t like the option names for enabling/disabling these (`pattern_syntax: glob/null` and `identifier_style: full/stripped`).

Make globs and indentifiers with extensions the default

---

NEWS.md
lib/nanoc/base/compilation/compiler_dsl.rb
lib/nanoc/base/compilation/item_rep_proxy.rb
lib/nanoc/base/identifiable_collection.rb
lib/nanoc/base/source_data/identifier.rb
lib/nanoc/base/source_data/site.rb
lib/nanoc/cli/commands/create-site.rb
lib/nanoc/data_sources/filesystem.rb
lib/nanoc/data_sources/filesystem_unified.rb
lib/nanoc/data_sources/filesystem_verbose.rb
spec/nanoc/base/identifier_spec.rb
spec/nanoc/base/views/identifiable_collection_spec.rb
spec/nanoc/base/views/mutable_item_collection_spec.rb
spec/nanoc/base/views/mutable_layout_collection_spec.rb
test/base/test_compiler_dsl.rb
test/base/test_item_array.rb
test/base/test_outdatedness_checker.rb
test/base/test_site.rb
test/cli/commands/test_compile.rb
test/cli/commands/test_create_site.rb
test/cli/commands/test_prune.rb
test/data_sources/test_filesystem.rb
test/data_sources/test_filesystem_unified.rb
test/extra/checking/checks/test_stale.rb
test/helper.rb

Old:
* `identifier_style` &rarr; `"full"` / `"stripped"`
* `pattern_syntax` &rarr; `"glob"` / `nil`
New:
* `identifier_type` &rarr; `"full"` / `"legacy"`
* `string_pattern_type` &rarr; `"glob"` / `"legacy"`

Rename identifier_style and pattern_syntax

---

lib/nanoc/base/source_data/site.rb
lib/nanoc/cli/commands/create-site.rb
test/base/test_site.rb
test/cli/commands/test_create_site.rb

The new default site now includes a sample compilation rule for RDoc, along with a sample RDoc file (hopefully clearly enough marked as “just for demonstration purposes”). It also comes with a commented-out compilation rule for Markdown files.
It also adds `rdoc` to the list of text extensions, because otherwise the site wouldn’t compile :)
Potential fix for #588.

Better default site

---

lib/nanoc/extra/checking/check.rb
lib/nanoc/extra/checking/checks/css.rb
lib/nanoc/extra/checking/checks/html.rb
lib/nanoc/extra/checking/checks/internal_links.rb
lib/nanoc/extra/checking/checks/stale.rb
lib/nanoc/extra/checking/runner.rb
test/extra/checking/checks/test_css.rb
test/extra/checking/checks/test_external_links.rb
test/extra/checking/checks/test_html.rb
test/extra/checking/checks/test_internal_links.rb
test/extra/checking/checks/test_mixed_content.rb
test/extra/checking/checks/test_stale.rb
test/extra/checking/test_check.rb

In checks, there should be `@items`, `@layouts` and `@config`, but no `@site`. This will make it more consistent with other places where variables are accessible.

Fix check variables

---

lib/nanoc/cli/commands/create-site.rb

For full identifiers, which is the default, this does not make sense.

Remove allow_periods_in_identifiers from default site

---

test/test_gem.rb

This occasionally fails, and I haven’t been able to reproduce or investigate. The single `gem build` test should suffice.

Remove test_build output check

---

lib/nanoc/extra/deployers/fog.rb
test/extra/deployers/test_fog.rb

This is continued off #480. Replaces #536 (code identical, but this time on `master` instead of `release-3.7.x`).
This PR has quite a bit of extra tests and refactorings that make these tests possible. I also tested this with an actual S3 and can confirm that it works.

Do not upload files with identical etags

---

lib/nanoc/data_sources/filesystem.rb
test/data_sources/test_filesystem_unified.rb

This will allow usage the static data source to be replaced with the `filesystem_unified` one without awkwardly having to specify a non-existant directory, but rather having it set to nil.
Before:
```yaml
data_sources:
-
type: filesystem
-
type: filesystem
items_root: /static
content_dir: 'static'
layouts_dir: 'static_layouts'
```
After:
```yaml
data_sources:
-
type: filesystem
-
type: filesystem
items_root: /static
content_dir: 'static'
layouts_dir: nil
```

Allow nil in layouts/content dir name

---

lib/nanoc/data_sources/filesystem.rb
test/data_sources/test_filesystem_unified.rb

Given two files:
* _content/donkey.jpeg_
* _content/donkey.yaml_
The resulting identifier would be `/donkey.yaml` rather than `/donkey.jpeg`. This PR fixes that.

Use content filename when constructing identifier

---

lib/nanoc/base/compilation/rule_context.rb
test/base/test_rule_context.rb

Fixes #614.
This also means that calls such as `@rep.filter …` are no longer possible within Rules (use `filter …` instead). That’s OK as long as it is documented in the migration guide.

Expose views in RuleContext

---

Gemfile
lib/nanoc/base.rb
lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/item_rep_writer.rb
lib/nanoc/base/result_data/item_rep.rb
lib/nanoc/cli/commands/compile.rb
spec/nanoc/base/item_rep_writer_spec.rb
spec/spec_helper.rb
test/base/test_item_rep.rb

This is a refactoring that extracts item rep writing functionality into its own class. Quite WIP for the time being.
Philosophies in refactoring:
* Entities, such as item representations, should be data objects, and shouldn’t know how to interact with the outside world.
* Service classes, such as the item rep writer, can interact with the outside world (in this case, the filesystem).

Item rep writer

---

lib/nanoc/base/source_data/item.rb
lib/nanoc/base/source_data/layout.rb
lib/nanoc/base/views/item.rb
lib/nanoc/base/views/layout.rb
lib/nanoc/base/views/mutable_item.rb
lib/nanoc/base/views/mutable_layout.rb
spec/nanoc/base/views/item_spec.rb
spec/nanoc/base/views/layout_spec.rb
test/base/test_compiler_dsl.rb
test/base/test_item.rb
test/base/test_layout.rb
test/filters/test_less.rb
test/helpers/test_filtering.rb
test/helpers/test_tagging.rb

* `Item` and `Layout` no longer have `#[]` and `#[]=`. They do not serve a purpose anymore; the shorthand is handled by the views.
* Dependency tracking (“visit started” and “visit ended” notifications) should happen in the views. This PR makes that change.
* Strangely, no dependency tracking was done for attributes in layouts. This PR also fixes that issue.
* As expected, some helper/filter tests use the entities rather than the views, causing their tests to break after this change. The tests have been updated to use views rather than entities.
To do (in a separate PR):
* Move common `ItemView` and `LayoutView` method into module or superclass (`#[]`, `#fetch`, `#key?`). Same goes for the mutable variants (`#[]=`, `#update_attributes`).

Remove Item/Layout attribute shorthands

---

lib/nanoc/base/views.rb
lib/nanoc/base/views/item.rb
lib/nanoc/base/views/layout.rb
lib/nanoc/base/views/mixins/document.rb
lib/nanoc/base/views/mixins/mutable_document.rb
lib/nanoc/base/views/mutable_item.rb
lib/nanoc/base/views/mutable_layout.rb
spec/nanoc/base/views/mutable_document_view_spec.rb
spec/nanoc/base/views/mutable_item_spec.rb
spec/nanoc/base/views/mutable_layout_spec.rb

This DRYs up some view code.
It also makes `#update_attributes` available for layout views.
I’m not super happy with the use of mixins here, but it does the job and makes the code cleaner. I’ll probably revisit this at some point.

Create mutable document view

---

lib/nanoc/base/entities/content.rb
lib/nanoc/data_sources/filesystem.rb
spec/nanoc/base/entities/content_spec.rb
test/base/test_item_rep.rb
test/data_sources/test_filesystem_unified.rb

This removes a dependency on the current working directory.
Documentation changes:
* Filenames used when generating items or layouts need to be absolute.

Require absolute filenames

---

lib/nanoc/base/entities/content.rb
lib/nanoc/base/source_data/item.rb
spec/spec_helper.rb

The freeze tests didn’t check whether an error was raised at all; just that *if* an error is raised, it is the correct one.

Fix freezing

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/item_rep_writer.rb
lib/nanoc/base/result_data/item_rep.rb
lib/nanoc/helpers/capturing.rb
spec/nanoc/base/entities/content_spec.rb
spec/nanoc/base/item_rep_writer_spec.rb
test/base/test_item_rep.rb

This lets item reps use the `Content` entity, which cleans up the code a little.

Use content entity in reps

---

lib/nanoc/helpers/rendering.rb
test/helpers/test_rendering.rb

Potential fix for #628. @cdlm, can you verify that this indeed solves your case?
In the rendering helper, the layout (`@layout`) is wrapped twice inside a `Nanoc::LayoutView` instance. It even had a `FIXME`!

Prevent double-wrapping layout in rendering helper

---

lib/nanoc/base/entities/identifier.rb
lib/nanoc/base/services/executor.rb
lib/nanoc/base/views/item_rep_collection.rb
spec/nanoc/base/entities/content_spec.rb
spec/nanoc/base/entities/identifier_spec.rb
spec/nanoc/base/services/executor_spec.rb
spec/nanoc/base/views/item_rep_collection_spec.rb
spec/nanoc/base/views/item_spec.rb

RSpec started complaining about uses of `#raise_error` without argument, and so it guilted me into making this PR.
* Added arguments to `#raise_error` everywhere.
* Added specs for some cases that weren’t tested.
* Created specific error classes (`Nanoc::Error` subclasses) so they are easy to test and also easy to handle, if necessary. This also marks the departure from the monolithic `Nanoc::Errors` module.

Improve errors

---

lib/nanoc/base/compilation/rule.rb
lib/nanoc/base/entities/pattern.rb
lib/nanoc/cli/command_runner.rb
lib/nanoc/cli/commands/show-rules.rb
spec/nanoc/base/entities/pattern_spec.rb
spec/nanoc/cli/commands/show_rules_spec.rb

Checksumming is used to determine whether rules have changed, and thus it is no longer possible to show the full rules.
What is possible, however, is show which items match against which rules. This PR modifies the command to work that way.
Example output:
```
Item /docs/troubleshooting.md:
Rep default: /**/*
Item /docs/tutorial.md:
Rep default: /**/*
Item /favicon.ico:
Rep default: /favicon.ico
Item /index.html:
Rep default: /index.*
Item /release-notes:
Rep default: /**/*
Item /robots.txt.erb:
Rep default: /robots.*
Item /sitemap.xml.erb:
Rep default: /sitemap.*
Item /style-guide.md:
Rep default: /**/*
Layout /autodoc_partial.erb:
/**/*
Layout /default.html.erb:
/**/*
```

Fix show rules

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/repos/site_loader.rb
lib/nanoc/base/source_data/data_source.rb
lib/nanoc/base/source_data/site.rb
lib/nanoc/cli/command_runner.rb
lib/nanoc/cli/commands/prune.rb
lib/nanoc/data_sources/filesystem.rb
test/base/test_compiler.rb
test/base/test_outdatedness_checker.rb
test/base/test_site.rb
test/cli/commands/test_create_site.rb
test/data_sources/test_filesystem_unified.rb
test/extra/checking/checks/test_stale.rb
test/helpers/test_rendering.rb

**Goal:** Let `Site` be a dumb entity, and decouple state (`Site`) and operations on state (`SiteLoader`).
This lets the site loader provide all data necessary to construct a site.
The `Site` entity is now a lot smaller, and does not interact with outside systems anymore. The site loader itself has become an ugly beast, which is expected. Future refactorings will take care of that.

Full site loader

---

lib/nanoc/extra/checking/runner.rb
test/extra/checking/checks/test_stale.rb

The `stale` check requires the compiler to be loaded so that the item reps are available. This wasn’t the case, but this PR fixes that.
The fix is pretty ugly, but hopefully the ugliness will disappear once the item rep building is moved outside of `Compiler#load`.

Load compiler in check

---

Gemfile
Rakefile
lib/nanoc/base/source_data/configuration.rb
lib/nanoc/cli/cleaning_stream.rb
nanoc.gemspec
spec/spec_helper.rb
tasks/rubocop.rake
tasks/test.rake
test/gem_loader.rb
test/helper.rb

The Rubocop integration was failing because because of the call to `#exit`. SimpleCov/Coveralls should now also work properly.
Additionally, this PR simplifies the Rakefiles. It also removes `LOAD_PATH` magic.

Fix RuboCop and Coveralls integration

---

spec/nanoc/base/entities/pattern_spec.rb
test/base/test_memoization.rb

* `Pattern` had some untested code
* `MemoizationTest#test_equal` was not useful.
* `MemoizationTest#test` was never run.

Fix some tests

---

bin/nanoc

This shows the following message when nanoc is invoked without `bundle exec`, and a _Gemfile_ is present:
> A Gemfile was detected, but Bundler is not loaded. This is probably not what you want. To run nanoc with Bundler, use `bundle exec nanoc`.

Check for Gemfile

---

lib/nanoc/base/repos.rb
lib/nanoc/base/repos/config_loader.rb
lib/nanoc/base/repos/site_loader.rb
lib/nanoc/cli.rb
spec/nanoc/base/repos/config_loader_spec.rb
spec/nanoc/base/repos/site_loader_spec.rb
test/base/test_site.rb

Fixes #644.
Having a separate config loader prevents having to load the site twice, and thus all its code snippets, removing the “constant already defined” warnings. It also leads to a speedup, but it doesn’t make it faster than nanoc 3.x. It’s also cleaner to not have all config-loading functionality in the site loader.
It probably makes sense to test the config loader separately; I’m relying on the site loader tests to ensure the config loader works at the moment.

Extract config loader

---

README.md

nanoc is a tool, not a library. As much as I care about documentation, API documentation is not where it’s at for nanoc. Because of this, I don’t feel that the Inch badge belongs in the nanoc README.
I will continue to use Inch for other projects where it is more appropriate (for instance, [cri](https://github.com/ddfreyne/cri)).
CC @rrrene

Remove Inch badge

---

lib/nanoc/cli/commands/create-site.rb

* Added a link to the about page.
* Removed the link to the wiki. The wiki is not particularly useful, and linking to it makes it feel like it is an important part of the documentation or community.
* Pointed all links to `v4.nanoc.ws` rather than `nanoc.ws`. This is necessary because the links otherwise point to old documentation. This is temporary and needs to be changed before the v4 final release.

Fix sidebar links in default site

---

lib/nanoc/base/entities/content.rb

Fix for the issue mentioned in [this comment](https://github.com/nanoc/nanoc/pull/622#discussion_r31878466).

Fix absolute filename check on Windows

---

.rubocop.yml
CONTRIBUTING.md
NEWS.md
README.md
bin/nanoc
lib/nanoc.rb
lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/error.rb
lib/nanoc/base/errors.rb
lib/nanoc/base/source_data/code_snippet.rb
lib/nanoc/cli.rb
lib/nanoc/cli/command_runner.rb
lib/nanoc/cli/commands/create-site.rb
lib/nanoc/cli/commands/nanoc.rb
lib/nanoc/cli/commands/prune.rb
lib/nanoc/cli/commands/shell.rb
lib/nanoc/cli/commands/show-plugins.rb
lib/nanoc/cli/commands/view.rb
lib/nanoc/cli/error_handler.rb
lib/nanoc/data_sources/filesystem_unified.rb
lib/nanoc/extra/checking/runner.rb
lib/nanoc/extra/jruby_nokogiri_warner.rb
lib/nanoc/extra/pruner.rb
lib/nanoc/filters/erubis.rb
lib/nanoc/filters/slim.rb
lib/nanoc/helpers/capturing.rb
lib/nanoc/version.rb
nanoc.gemspec

Fix for #596.
The product name becomes _Nanoc_ (used to be _nanoc_). The following items are not affected:
* The command-line tool
* The library name
* The gem name

Rename nanoc to Nanoc

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/compilation/compiler_dsl.rb
lib/nanoc/base/compilation/outdatedness_checker.rb
lib/nanoc/base/compilation/rule.rb
lib/nanoc/base/compilation/rule_context.rb
lib/nanoc/base/entities/content.rb
lib/nanoc/base/entities/identifier.rb
lib/nanoc/base/repos/checksum_store.rb
lib/nanoc/base/result_data/item_rep.rb
lib/nanoc/base/services/executor.rb
lib/nanoc/base/services/preprocessor.rb
lib/nanoc/base/services/recording_executor.rb
lib/nanoc/base/services/rule_memory_calculator.rb
lib/nanoc/base/source_data/code_snippet.rb
lib/nanoc/base/source_data/data_source.rb
lib/nanoc/base/source_data/site.rb
lib/nanoc/base/views/item_rep_view.rb
lib/nanoc/base/views/item_view.rb
lib/nanoc/base/views/mutable_item_collection_view.rb
lib/nanoc/cli/commands/compile.rb
lib/nanoc/cli/error_handler.rb
lib/nanoc/extra/checking/check.rb
lib/nanoc/extra/deployer.rb
lib/nanoc/extra/piper.rb
lib/nanoc/extra/pruner.rb
lib/nanoc/helpers/tagging.rb
lib/nanoc/helpers/text.rb
spec/nanoc/base/entities/identifier_spec.rb
spec/nanoc/base/services/recording_executor_spec.rb
test/cli/commands/test_compile.rb

Ruby 2.2 supports keyword arguments, which has two advantages:
* It makes existing code more compact. No more `params.fetch` necessary.
* It increases reliability because unrecognised arguments will cause an `ArgumentError`.
Some occurrences of `params` cannot be replaced with keyword arguments—filters, for instance.
This change also removes a deprecated extra unused `params` argument in the `CodeSnippet` constructor.
To do:

Use keyword arguments

---

.rubocop.yml
lib/nanoc/base/compilation/filter.rb
lib/nanoc/base/services/item_rep_selector.rb
lib/nanoc/helpers/capturing.rb

Rescuing everything and retrying is bad and confusing, and the reason why `RescueModifier` exists. Fixed!

Remove #unwrap rescue

---

CONTRIBUTING.md

This is based off the [Contributor Covenant](http://contributor-covenant.org/).
Future work:
* Add to Contributing section on the nanoc web site

Add contributor code of conduct

---

lib/nanoc/cli/commands/shell.rb
spec/nanoc/cli/commands/shell_spec.rb
spec/spec_helper.rb

The `shell` command is broken because `#env_for_site` does not exist.
Based on #671 (by @jimjimovich) with a spec fix and an additional spec.

Fix broken shell command

---

lib/nanoc/cli/commands/shell.rb

Running nanoc shell was producing the following error:
NoMethodError: undefined method `env_for_site' for Nanoc::CLI::Commands::Shell:Class
I changed the method env_for to env_for_site and now everything works fine.

fixed typo in class definition of shell command module

---

lib/nanoc/data_sources/filesystem.rb
test/data_sources/test_filesystem.rb

When the frontmatter is not a hash (e.g. nil, or a string), raise an exception that is easier to understand than whatever happens now (`TypeError: no implicit conversion of String into Hash`).
Fixes #670.

Error on non-hash frontmatter

---

lib/nanoc/helpers/tagging.rb
test/helpers/test_tagging.rb

While using version 4.0.2rc2, one error occurred after `Tagging` helper and `tags_for` method were added into my code, which told me a KeyError around key `base_url`.
I checked the source in release-4.0.x and found that `base_url` must be provided or there will be an error here. It's never been listed in the document or the official tutorial.
In my mind it's not so important that users MUST have a link to a tag, at least there should be a default tag link url.
Thank you so much for your review.

Make base_url optional in #tags_for

---

lib/nanoc/base/identifiable_collection.rb
spec/nanoc/base/views/identifiable_collection_spec.rb

Allow IdentifiableCollection#[] with Identifier

---

lib/nanoc/base/entities/identifier.rb
spec/nanoc/base/entities/identifier_spec.rb

This PR extends Nanoc::Identifier with two new methods to handle identifiers with multiple exts. Two methods are added:
- #exts which returns a list of extensions of an identifier
- #without_exts which removes all extensions of an identifier
This PR is related to https://github.com/nanoc/nanoc/pull/679

Identifier with multiple exts

---

lib/nanoc/base/views/mixins/mutable_document_view_mixin.rb
spec/nanoc/base/views/mutable_document_view_spec.rb

Fix for #682.
This is possibly not the best approach—maybe rather than disallowing it, handle cases like these gracefully.

Disallow storing document (views) in attributes

---

lib/nanoc/cli/commands/create-site.rb

Rather thank linking to the stylesheet by finding it using `@items` and then getting the path, we can simply use a direct link to the stylesheet. This approach is more straightforward and less confusing.
Fixes #685.

Use direct stylesheet link

---

lib/nanoc/base/views/mixins/document_view_mixin.rb
spec/nanoc/base/views/document_view_spec.rb

This is useful when converting an item or a layout into a JSON representation.
(This was initially removed from Nanoc 4 because it was an internal method with public visibility in nanoc 3. Using it meant bypassing the dependency tracking mechanism. With this new implementation, that is no longer an issue.)
Fixes #699.

Add DocumentView#attributes

---

lib/nanoc/base/views/config_view.rb

Closes #705 
I actually wrote a little dinky test for this in *test_compiler_dsl.rb*: 
``` ruby
def test_config_iteration
hash = { :key_one => 1, :key_two => 2}
@config = Nanoc::ConfigView.new(hash, nil)
@config.each do |k, v|
puts k, v
end
end
```
It works, but because no other `ConfigView` syntaxes are tested (and the fact that STDOUT is muted) I decided not to include it. I could if there's a better way to work this.

Add `#each` to `ConfigView`

---

lib/nanoc/base/views/item_view.rb
spec/nanoc/base/views/item_view_spec.rb

In Nanoc 4.0.x, `:pre` is the default snapshot. This was mistakenly changed to `:last` in `master.

Use :pre, not :last, as the default snapshot

---

lib/nanoc/base/entities/identifier.rb
lib/nanoc/base/errors.rb
lib/nanoc/base/views/item_view.rb
spec/nanoc/base/entities/identifier_spec.rb
spec/nanoc/base/views/item_view_spec.rb

Fixes #709.
It also adds:
* a test for `#children` (which was still pending)
* `Identifier#legacy?` because it’s useful
* tests for `#full?` and `#legacy?`

Let #parent/#children raise for non-legacy identifiers

---

lib/nanoc/cli/stream_cleaners/ansi_colors.rb

I've noticed that if I try to do some quick debugging—like, `puts @config`, this little helper will complain about a missing `gsub`, because `s` is a Hash or a String or something.
I think it's necessary every now and then to not assume everything being printed is a string, so this PR protects against that.

Only attempt to clean if the item is a string

---

lib/nanoc/helpers/capturing.rb
test/helpers/test_capturing.rb

Make content_for raise an exception in case of silently overwriting content

---

lib/nanoc/helpers/blogging.rb

This enhances `attribute_to_time` which previously removed all time
information from a DateTime. This happened because DateTime identifies
itself as a Date.
2.2.3 :001 > require 'date'
=> true
2.2.3 :002 > DateTime.now.is_a?(Date)
=> true
Up to now, if `time.is_a?(Date)` is true, `attribute_to_time` will
create a new Time, with just year, month and day set. To fix that
behaviour, this commit adds a new condition at the beginning of
`attribute_to_time`, which uses `time.to_time` as long as `time` is a
DateTime.

Add DateTime handling to attribute_to_time

---

lib/nanoc/base/checksummer.rb

A minor refactoring to reduce the amount of code in the checksummer. Functionally still identical to the old version (as evidenced by the tests).

Simplify checksummer

---

lib/nanoc/helpers/blogging.rb
spec/nanoc/helpers/blogging_spec.rb

When give a `Date` or `String` instance, `#attribute_to_time` does not have timezone information, and so I believe the correct approach is to treat the argument as *local* time. The tests failed in UTC since they did not take the time offset into account.
This PR makes the argument be treated as local time. (Enhancement rather than a bug, because it’s mostly the specs being wrong, and the documentation being vague.)
A small bonus change involves refactoring `#attribute_to_time` so it no longer has assignments or explicit type checks with `if`.
Also see #717.

Fix #attribute_to_time timezone issues

---

lib/nanoc/base/entities/identifier.rb
spec/nanoc/base/entities/identifier_spec.rb

This provides a slightly nicer-to-use alternative to `identifier.to_s.split`.
The return value is such that `'/' + identifier.components.join('/')` is identical to `identifier.to_s`.
See #674.

Add Identifier#components

---

lib/nanoc/base/entities/document.rb
lib/nanoc/base/entities/identifier.rb
lib/nanoc/base/views/item_rep_view.rb
spec/nanoc/base/entities/identifier_spec.rb
spec/nanoc/base/views/item_rep_view_spec.rb

* Made comparing identifiers somewhat more strict (don’t blindly call `#to_s`)
* Make `Document` equality less strict (don’t require the exact same class—a view also works)
* Don’t crash when comparing an ItemRepView with something else (fixes #735).

Fix comparisons

---

lib/nanoc/extra/deployers/fog.rb

I attempted to write a test for this, but without luck.
Fixes #718.

Fix crash on Array#all in fog deployer

---

lib/nanoc/cli.rb
test/cli/test_cli.rb
test/helper.rb

Fixes #741.
Nanoc loads commands using the environment’s encoding. We know for a fact that these are UTF-8, so relying on the environment is unnecessary, and even wrong, as shown by the crash.

Load commands as UTF-8

---

lib/nanoc/helpers/link_to.rb
test/helpers/test_link_to.rb

The `link_to_unless_current` function from `link_to` helper was outputing english text. This should be avoided.

Removed english text from link_to helper.

---

lib/nanoc/helpers/capturing.rb
test/helpers/test_capturing.rb

Fixes #704.
`#content_for`, when given a block, now gains a second parameter, `:existing`, which determines what to do when existing content already exists. The three possible values are:
* `:error` (current behavior): when content already exists and is not identical, raise an error.
* `:overwrite`: overwrite the previously captured content with the newly captured content
* `:append`: append the newly captured content to the previously captured content
For example:
```rhtml
<% content_for(:stuff) do %>banana<% end %>
<% content_for(:stuff, existing: :append) do %>donkey<% end %>
```
will result in `content_for(:stuff)` containing `"bananadonkey"`
```rhtml
<% content_for(:stuff) do %>banana<% end %>
<% content_for(:stuff, existing: :error) do %>donkey<% end %>
```
will raise an exception …

Add behaviors to #content_for

---

Gemfile
test/filters/test_sass.rb

Sass got locked into the 3.2.x branch, presumably due to a bug in a more recent version that caused issues with Nanoc a while back. Sadly, upgrading breaks tests:
```
3) Error:
Nanoc::Filters::SassTest#test_filter_can_import_external_files:
Sass::SyntaxError: File to import not found or unreadable: moo.
(sass):1
/usr/local/lib/ruby/gems/2.2.0/gems/sass-3.4.19/lib/sass/tree/import_node.rb:67:in `rescue in import'
[snip]
/Users/ddfreyne/Documents/Development/nanoc/repos/nanoc/lib/nanoc/filters/sass.rb:18:in `run'
/Users/ddfreyne/Documents/Development/nanoc/repos/nanoc/lib/nanoc/base/compilation/filter.rb:130:in `setup_and_run'
/Users/ddfreyne/Documents/Development/nanoc/repos/nanoc/test/filters/test_sass.rb:54:in `block in test_filter_can_import_external_files' …
```

Allow more recent sass version in Gemfile

---

nanoc.gemspec

4.0.1 was supposed to have its minimum required Ruby version lowered from 2.2 to 2.1, but the only thing that was changed was to run the tests on Ruby 2.1 on Travis CI, which worked fine.
This PR changes the actual minimum required Ruby version, checked when doing a `bundle install` or a `gem install`, to 2.1.
CC @Fjan

Support Ruby 2.1

---

lib/nanoc/base/views/item_rep_collection_view.rb
spec/nanoc/base/views/item_rep_collection_view_spec.rb

Require ItemRepCollectionView#[] param to be Symbol

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/entities/rule_memory.rb
lib/nanoc/base/services/rule_memory_calculator.rb
spec/nanoc/base/services/rule_memory_calculator_spec.rb
test/base/test_compiler.rb

This makes the compiler use the rule actions, rather than executing the rules a second time.
This gets rid of an icky bit of duplication in `#new_rule_memory_for_rep`, and using rule actions means that we are a step closer to decoupling the rules file from Nanoc core.
It also fixes an issue which would cause a path defined for the `:post` snapshot to have no effect.

Use rule memory for compiling reps

---

lib/nanoc/cli/commands/create-site.rb

Fixes #757.
There are no other useful places in the default site to use `#write` for.

Use #write in default site

---

lib/nanoc/base/entities/rule_memory.rb
lib/nanoc/rule_dsl/recording_executor.rb
spec/nanoc/base/entities/rule_memory_spec.rb
spec/nanoc/rule_dsl/recording_executor_spec.rb
spec/nanoc/rule_dsl/rule_memory_calculator_spec.rb
test/base/test_compiler.rb

The `:pre` snapshot is not generated properly (it remains “non-final”). This PR fixes that.
The `NonFinalSnapshotWithPathError` error might need to be removed. I’ll try to keep it in (it’s useful) but getting it to work properly might be hard.
Fixes #762.

Fix final :pre snapshot not being generated

---

lib/nanoc/base/entities/item_rep.rb
spec/nanoc/regressions/gh_761_spec.rb
test/base/test_item_rep.rb

Using `@item.compiled_content` in a layout broke in 4.1.0a1. This was caused by `#compiled_content` searching for the *first* snapshot with a given name (in this case, `:pre`) rather than the last one.
I’ve created a separate regression test in `spec/nanoc/regressions`. I haven’t done something like this before, but it seems sensible.
Fixes #761.

Fix using #compiled_content in layout

---

lib/nanoc/base/views/item_without_reps_view.rb
spec/nanoc/base/views/item_view_spec.rb
spec/nanoc/regressions/gh_769_spec.rb

This was already fixed as part of another PR, but this PR adds tests.
Fixes #769.

Fix finding parent of child of root

---

lib/nanoc/extra/checking/dsl.rb
test/extra/checking/test_dsl.rb

Relative requires do not work without a base path.

Give Checks file a base path

---

lib/nanoc/base/entities/pattern.rb

While mucking about I noticed this could probably be made a class-level constant rather than recomputing on each call.

Extract match opts out as a constant

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/compilation/dependency_tracker.rb
lib/nanoc/base/compilation/filter.rb
lib/nanoc/base/services/executor.rb
lib/nanoc/base/views/item_rep_view.rb
lib/nanoc/base/views/mixins/document_view_mixin.rb
lib/nanoc/base/views/view.rb
lib/nanoc/base/views/view_context.rb
lib/nanoc/cli/commands/compile.rb
lib/nanoc/extra/checking/check.rb
lib/nanoc/helpers/capturing.rb
lib/nanoc/helpers/rendering.rb
lib/nanoc/rule_dsl/action_provider.rb
lib/nanoc/rule_dsl/recording_executor.rb
spec/nanoc/base/services/executor_spec.rb
spec/nanoc/base/views/document_view_spec.rb
spec/nanoc/base/views/item_rep_view_spec.rb
spec/nanoc/base/views/item_view_spec.rb
spec/nanoc/base/views/mutable_document_view_spec.rb
spec/nanoc/helpers/blogging_spec.rb
spec/nanoc/rule_dsl/rule_context_spec.rb
spec/spec_helper.rb
test/base/test_dependency_tracker.rb
test/filters/test_less.rb
test/helpers/test_filtering.rb
test/helpers/test_rendering.rb
test/helpers/test_tagging.rb
test/helpers/test_xml_sitemap.rb

Rather than relying the dependency tracker of being available magically, and communicating with it through messages (notifications), inject the dependency tracker into the view context.
This is a step towards parallelism, because multiple parallel compilations will need their own dependency tracker—they can’t share the same stack used for dependency tracking.

Pass in dependency tracker

---

lib/nanoc/helpers/breadcrumbs.rb
test/helpers/test_breadcrumbs.rb

`#breadcrumbs_trail` will fail silently for full identifiers. To prevent that from happening, let’s make it raise an error.
Fixes #781.

Let #breadcrumbs_trail raise for full identifiers

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/entities/item.rb
lib/nanoc/base/entities/item_rep.rb
lib/nanoc/helpers/capturing.rb
test/helpers/test_capturing.rb

By using snapshots for captured content rather than relying on a separate “captures store”, there will no longer be a need force-recompile an item when its captures are requested.
Goodbye, tech debt!

Use snapshots for captured content

---

lib/nanoc/cli/command_runner.rb
lib/nanoc/cli/commands/deploy.rb
lib/nanoc/cli/commands/prune.rb
spec/nanoc/regressions/gh_787_spec.rb
spec/spec_helper.rb

Running the preprocessor every time a site is loaded is problematic because invoking the `compile` command will run the preprocessor twice.
Fixes #787.

Preprocess in deploy/prune only

---

lib/nanoc/base/compilation/outdatedness_checker.rb

The new checksum of objects is currently calculated twice:
1. for `checksums_available?`
2. for `checksums_identical?`
Since checksum calculation can be costly, this commit memoizes its calculation.
This speeds up the compilation of my site with 20% in case of no changes.

Avoid double calculation of checksum

---

lib/nanoc/base/checksummer.rb
lib/nanoc/base/entities/document.rb
lib/nanoc/base/repos/data_source.rb
lib/nanoc/data_sources/filesystem.rb
spec/nanoc/base/checksummer_spec.rb
spec/nanoc/base/entities/document_spec.rb
test/base/test_data_source.rb

As suggested in #790, this pull request allows a `Document` to specify a pre-calculated checksum. This gives data sources the ability to determine a checksum for the items and layouts they create.
This pull request:
- adds a `checksum` parameter to the initializer of `Document` (as well as `new_item` and `new_layout`)
- modifies `Checksummer` to use the `checksum` on `Item` and `Layout` if present
- modifies the filesystem datasource to set the size/modification time as checksum
This realizes a major compilation speed gain for my website (from 11s to 3s if nothing is changed), and paves the way for lazy loading of items, which could bring down compilation time even further.

Add checksum parameter to Document

---

lib/nanoc/base/entities/configuration.rb
lib/nanoc/base/entities/identifiable_collection.rb
lib/nanoc/base/entities/site.rb
lib/nanoc/base/views/item_without_reps_view.rb
lib/nanoc/base/views/view.rb
spec/nanoc/base/entities/site_spec.rb
spec/nanoc/base/views/config_view_spec.rb
spec/nanoc/base/views/document_view_spec.rb
spec/nanoc/base/views/identifiable_collection_view_spec.rb
spec/nanoc/base/views/item_rep_collection_view_spec.rb
spec/nanoc/base/views/item_rep_view_spec.rb
spec/nanoc/base/views/item_view_spec.rb
spec/nanoc/regressions/gh_795_spec.rb

This ensures that views are marked as frozen when their backing entity is marked as frozen.
In order for this to work, the item and layout collections needed to be frozen; only their contents were frozen until now. In addition, code snippets are now frozen as well.
Fixes #795.

Freeze views

---

lib/nanoc/cli/error_handler.rb

The environment can contain sensitive information, and so it shouldn’t be included in `crash.log` by default.
CC @gjtorikian 
See #798.

Remove env from crash.log

---

lib/nanoc/rule_dsl/rule_memory_calculator.rb
spec/nanoc/regressions/gh_807_spec.rb
spec/nanoc/rule_dsl/rule_memory_calculator_spec.rb

No actual dependency tracking needs to be done at this point. If anything would cause a dependency to be created, it’d either do so at a later stage, or would cause the rule memory to change.
Fixes #807.

Pass view context with dependency tracker to rule mem calculator

---

lib/nanoc/data_sources/filesystem.rb
test/data_sources/test_filesystem.rb
test/data_sources/test_filesystem_unified.rb

This is in preparation of returning content/attributes wrapped in a `LazyValue`. See #794.

Refactor filesystem data source

---

lib/nanoc/cli/commands/compile.rb
spec/nanoc/regressions/gh_813_spec.rb

`rep.raw_path` will only be the correct path if the snapshot is `:last`, but that’s not guaranteed.
Fixes #813.

Generate diff for correct path

---

lib/nanoc/base/entities/configuration.rb
spec/nanoc/base/entities/configuration_spec.rb
spec/nanoc/base/views/config_view_spec.rb
spec/nanoc/regressions/gh_815_spec.rb

Add Configuration#key?

---

lib/nanoc/filters/sass.rb

This caches the filename-to-item mapping, so that `#imported_filename_to_item` is significantly faster.
This is a per-site cache, which will stick around in memory, which I feel is okay for now. This could be updated to use `WeakRef`s.
* * *
Compilation speeds without cache:
```
Site compiled in 14.32s.
Site compiled in 13.85s.
Site compiled in 14.15s.
Site compiled in 15.27s.
Site compiled in 15.52s.
```
Method profile without cache:
```
TOTAL    (pct)     SAMPLES    (pct)     FRAME
3560  (36.4%)        1778  (18.2%)     Nanoc::Filters::Sass#uncached_imported_filename_to_item
3220  (34.4%)        1606  (17.2%)     Nanoc::Filters::Sass#uncached_imported_filename_to_item
3368  (35.7%)        1679  (17.8%)     Nanoc::Filters::Sass#uncached_imported_filename_to_item
3996  (38.0%)        1990 …
```

Cache filename-to-item mapping in Sass

---

lib/nanoc/cli/commands/show-data.rb
spec/nanoc/regressions/gh_833_spec.rb

Fixes #833.
This PR has a fix and a regression test, but I’d like to take the time to write a proper spec for the `show-data` command. That command has been around for a while and has always “just worked”—until now, apparently, and I’d like to ensure that it keeps on working.

Fix show-data crash

---

lib/nanoc/helpers/html_escape.rb
spec/nanoc/helpers/html_escape_spec.rb

Nanoc::Helpers::HTMLEscape#html_escape breaks when the given parameter
is not a String.
The following message appeared:
~~~~~
Captain! We’ve been hit!
Message:
NoMethodError: undefined method `gsub' for 1:Fixnum
Stack trace:
0. […]/nanoc-4.1.4/lib/nanoc/helpers/html_escape.rb:38:in `html_escape'
1. […]/nanoc-4.1.4/lib/nanoc/helpers/link_to.rb:59:in `block in link_to'
2. […]/nanoc-4.1.4/lib/nanoc/helpers/link_to.rb:58:in `each'
3. […]/nanoc-4.1.4/lib/nanoc/helpers/link_to.rb:58:in `reduce'
4. […]/nanoc-4.1.4/lib/nanoc/helpers/link_to.rb:58:in `link_to'
5. layout /default/:84:in `block in render'
~~~~~
After I tried something similar to the following:
~~~~~ruby
link_to 'Homepage', @items['/'].path, {accesskey: 1}
~~~~~~
To fix this issue I had multiple ideas:
I first wanted to use …

Raise a better error when no String is given in #html_escape

---

test/cli/commands/test_create_site.rb

RuboCop on Travis CI (but not locally?!) errors because of a parse error regarding non-UTF-8 characters. This is an attempt at a fix.

Fix create-site test

---

lib/nanoc/base/entities/document.rb
lib/nanoc/base/entities/lazy_value.rb
spec/nanoc/base/entities/lazy_value_spec.rb

This removes `#transform` and provides a more composable `#map`:
```ruby
lv = Nanoc::Int::LazyValue.new(-> { sleep 1; 'Hello' })
lv_uppercase = lv.map(&:upcase)
p lv_uppercase.value
p lv_uppercase.value
```
This eliminates the need for subclassing `LazyValue` to specify custom transformations, and it allows chaining transformations.
Next up: updating the filesystem data source to make use of these new lazy values.
CC @RubenVerborgh — this will likely break your customisations since I believe they depend on `#transform`

Replace LazyValue#transform with #map

---

lib/nanoc/base/memoization.rb

Memoized values only exist to speed up calculations, and are okay to be garbage-collected when memory pressure rises.
The `Wrapper` is necessary in order to let the value pointed to by the weak ref behave exactly as the calculation result. In particular, `nil` is troublesome as it requires syntactic support from Ruby to be handled properly, and weak refs to nil don’t behave the same as nil itself.

Wrap memoized values in weak refs

---

lib/nanoc/extra/checking/checks/internal_links.rb
test/extra/checking/checks/test_internal_links.rb

The internal links checker has an `exclude` configuration option, which matches hrefs. This is often not enough, as sometimes it is useful to ignore all links in a file. This PR adds a configuration option `exclude_origins`, which is used for exactly that purpose.
For example, the following excludes all files under `/api` from the internal links checker, perhaps because it’s auto-generated and is known to be broken:
```yaml
checks:
internal_links:
exclude_origins: ^/api/
```

Add exclude_origins option to internal links checker

---

lib/nanoc/helpers.rb
lib/nanoc/helpers/child_parent.rb
lib/nanoc/spec.rb
spec/nanoc/helpers/child_parent_spec.rb
spec/nanoc/helpers/tagging_spec.rb

This adds `#children_of` and `#parent_of`, which works with both legacy *and* full identifiers. For example:
```rhtml
<%= link_to(parent_of(@item)) %>
```
```rhtml
<ul>
<% children_of(@item).each do |child| %>
<li><%= link_to(child[:title], child) %></li>
<% end %>
</ul>
```
This allows getting rid of the ugly piece of upgrade advice that tells people to replace `@item.parent` with `@items[@item.identifier.to_s.sub(/[^\/]+$/, '').chop + '.*']`.

Add ChildParent helper

---

lib/nanoc/base/services/item_rep_router.rb
spec/nanoc/base/services/item_rep_router_spec.rb

Fixes #837.
I can’t find a good high-level test case for this.

Force UTF-8 for item rep paths

---

.travis.yml

Ruby 2.1 is [EOL as of March](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/).
This PR also upgrades the Ruby versions for 2.2 and 2.3 as Listen requires a more recent version.

Drop Ruby 2.1 support

---

lib/nanoc/base/checksummer.rb
spec/nanoc/base/checksummer_spec.rb

This will reduce the number of unnecessary recompiles when `Sass::Importers::Filesystem` is involved (typically via Compass).
Fixes #866.

Handle Sass::Importers::Filesystem in checksummer

---

lib/nanoc/base/services/executor.rb
lib/nanoc/cli/error_handler.rb
spec/nanoc/base/services/executor_spec.rb

Potential fix for #866.
Mutating the filter arguments will break the outdatedness checker (this has always been the case).

Freeze filter arguments

---

lib/nanoc/base/checksummer.rb
nanoc.gemspec

Using Ruby’s `Set` in an immutable way is slow. `Hamster::Set`, from [Hamster](https://github.com/hamstergem/hamster), is significantly faster.
Example: 1138s &rarr; 50s
Fixes #864.

Use Hamster::Set in checksummer for speed

---

lib/nanoc/base/entities/document.rb
lib/nanoc/base/entities/identifier.rb
lib/nanoc/base/views/item_rep_view.rb
lib/nanoc/base/views/mixins/document_view_mixin.rb
spec/nanoc/base/entities/identifier_spec.rb
spec/nanoc/base/views/document_view_spec.rb
spec/nanoc/base/views/item_rep_view_spec.rb
spec/nanoc/base/views/item_view_spec.rb
spec/nanoc/base/views/layout_view_spec.rb
spec/nanoc/helpers/blogging_spec.rb

* `#==` can do type coercion (e.g. `2.0 == 2` &rarr; true)
* `#eql?` does not do type coercion (e.g. `2.0.eql?(2)` &rarr; false)
For this reason, `#eql?` in `Nanoc::Identifier` should not do type coercion either. This is important for correctness, as `#eql?` is used in `Hamster::Set`.

Remove type coercion in #eql?

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/repos/dependency_store.rb
spec/nanoc/regressions/gh_885_spec.rb
spec/nanoc/regressions/gh_891_spec.rb

Fixes #885, #891.
This is not a pretty fix, but I fear that solving this properly might require some rethinking and rearchitecting. We’ll see!

Ensure dependency graph includes preprocessor items

---

lib/nanoc/base/compilation/compiler.rb
test/base/test_compiler.rb

The compiler does not need to compile reps that are not outdated.
If a rep is not compiled, its compiled content will not be filled in, which is fine during compilation, as the compiler will compile that item on-demand, probably reusing the cached compiled content for this item. For this reason, I believe the `#test_compile_should_recompile_all_reps` to be useless.

Only recompile outdated reps

---

lib/nanoc/base/memoization.rb
test/base/test_memoization.rb

Inspecting a `WeakRef` can cause a `WeakRef::RefError`. To prevent these errors from happening, use a wrapper for `WeakRef` that has a custom implementation of `#inspect`.
Fixes #877.

Wrap WeakRefs in object with custom #inspect

---

lib/nanoc/base/views/item_rep_view.rb
lib/nanoc/base/views/mixins/document_view_mixin.rb
lib/nanoc/base/views/view.rb
spec/nanoc/base/views/config_view_spec.rb
spec/nanoc/base/views/item_collection_view_spec.rb
spec/nanoc/base/views/item_rep_collection_view_spec.rb
spec/nanoc/base/views/item_rep_view_spec.rb
spec/nanoc/base/views/item_view_spec.rb
spec/nanoc/base/views/layout_collection_view_spec.rb
spec/nanoc/base/views/layout_view_spec.rb
spec/nanoc/base/views/mutable_config_view_spec.rb
spec/nanoc/base/views/mutable_item_collection_view_spec.rb
spec/nanoc/base/views/mutable_item_view_spec.rb
spec/nanoc/base/views/mutable_layout_collection_view_spec.rb
spec/nanoc/base/views/mutable_layout_view_spec.rb

This prevents the risk of an `#inspect` call accidentally printing the world.
Also se #877.

Add #inspect method to views

---

lib/nanoc/base/views/post_compile_item_view.rb
spec/nanoc/base/views/post_compile_item_view_spec.rb

The `#modified` method is confusing. This PR introduces `#modified_reps` and deprecates `#modified`.

Add #modified_reps and deprecate #modified

---

lib/nanoc/cli/commands/compile.rb

This prevents the tests from generating `output.diff`.

Tear down DiffGenerator notifications

---

lib/nanoc.rb
lib/nanoc/base/memoization.rb
nanoc.gemspec

Using soft references rather than weak references will hopefully prevent memoized values from being garbage collected too eagerly.

Use soft ref rather than weak ref

---

lib/nanoc/cli/commands/compile.rb
spec/nanoc/cli/commands/compile_spec.rb

This makes exceptions that occur in `#start` not be turned into weird `#stop` errors.

Do not call Listener#stop when #start failed

---

lib/nanoc/base/compilation/filter.rb
spec/nanoc/base/filter_spec.rb

This makes filter easier to define.
Before:
```ruby
Class.new(Nanoc::Filter) do
identifier :upcase
def run(content, params={})
content.upcase
end
end
```
After:
```ruby
Nanoc::Filter.define(:upcase) do |content, params|
content.upcase
end
```

Add Filter.define

---

lib/nanoc/cli/commands/compile.rb

This adds a profiler, enabled by passing the `--profile` flag to the `compile` command.
This feature is only available when `NANOC_FEATURE_PROFILER` is set to a true value (`1`, `true`, `yes`, …). It will become generally available in 4.3.
This will hopefully make it easier for people to profile their site compilation.

Add profiler (behind feature flag)

---

lib/nanoc/extra/checking/checks/internal_links.rb
test/extra/checking/checks/test_internal_links.rb

Add resources to ilinks check, see #911

---

lib/nanoc/cli.rb

Other gems may want to add commands to the nanoc CLI. To do this
they need to run Nanoc::CLI.add_after_setup_proc. Currently, there
is no way to hook into the CLI. This commit adds such a way by
utilizing Bundler. E.g. the gem guard-nanoc could introduce new
commands when added to the Gemfile in this way:
gem 'nanoc'
group :nanoc do
gem 'guard-nanoc'
end
Presence of any gems in the group :nanoc will cause the library with
the same name as the gem to be required by Bundler during
the initialization of the CLI.
A special group :nanoc is used for two reasons:
* nanoc may not be the only or primary user of the Gemfile,
and requiring many unrelated gems will slow down every invocation
of nanoc with no workaround;
* existing Gemfiles may include specifications for gems that cannot
be …

Discover external commands through Bundler

---

lib/nanoc/base/compilation/compiler.rb
test/base/test_compiler.rb

Reverting, because when a postprocessor exist, all reps need to be compiled.
A better solution would be to compile item reps on-demand in the postprocessor, but that’s an optimisation left for later.
Fixes #913.
Reverts #894.

Revert "Only recompile outdated reps"

---

lib/nanoc/cli.rb

win32console (https://github.com/luislavena/win32console) is deprecated
in favour of ANSICON (https://github.com/adoxa/ansicon).
Hopefully makes #900 less of an issue.

Remove win32console require

---

lib/nanoc/cli/commands/deploy.rb
spec/nanoc/cli/commands/deploy_spec.rb

Before:
```
The site has no deployment configuration for staging.
```
After:
```
The site has no deployment configuration named `staging`.
```

Improve missing deploy target error message

---

lib/nanoc/extra/deployers/fog.rb
spec/nanoc/extra/deployers/fog_spec.rb

Before:
```
The path requires no trailing slash
```
After:
```
The path `foo/` is not supposed to have a trailing slash
```

Improve trailing-slash error message

---

lib/nanoc/base/compilation/filter.rb
spec/nanoc/base/filter_spec.rb

Fix assigns in filters defined with Filter.define

---

lib/nanoc/base/entities/configuration.rb
lib/nanoc/base/repos/checksum_store.rb
lib/nanoc/base/repos/compiled_content_cache.rb
lib/nanoc/base/repos/config_loader.rb
lib/nanoc/base/repos/dependency_store.rb
lib/nanoc/base/repos/rule_memory_store.rb
lib/nanoc/base/repos/site_loader.rb
lib/nanoc/base/repos/store.rb
lib/nanoc/base/services/compiler_loader.rb
lib/nanoc/cli/commands/nanoc.rb
spec/nanoc/base/checksummer_spec.rb
spec/nanoc/base/entities/configuration_spec.rb
spec/nanoc/base/repos/config_loader_spec.rb
spec/nanoc/base/views/config_view_spec.rb
test/base/test_store.rb

Introduce support for nanoc environment and addresses https://github.com/nanoc/nanoc/issues/676.
- nanoc command is updated to include `--env` argument
- site config is overriden using the active environment if any and fallback to 'default'
- if environments is provided, `tmp` directory is updated to `tmp/{{env_name}}`
Setting environments is done in nanoc.yaml using the `environments` property.
Example usage is:
```
output_dir: output
environments:
default: &default
base_url: ...
...
development:
<<: *default
base_url: ...
production:
<<: *default
base_url: ...
yet_another_env:
<<: *default
base_url: ...
output_dir: build
```
Selecting working environment can be done:
- using environment variable `NANOC_ENVIRONMENT`
- using `nanoc --env=[<value>]`

Support nanoc environments

---

lib/nanoc/base/feature.rb
lib/nanoc/cli/commands/compile.rb
spec/nanoc/base/feature_spec.rb
ugh.diff

This uses `NANOC_FEATURES` to specify features, rather than `NANOC_FEATURE_abc` (where `abc` is the feature name.
See nanoc/rfcs#5 for details on the design.

Improve feature flag implementation

---

lib/nanoc/base/feature.rb
lib/nanoc/base/repos/config_loader.rb
spec/nanoc/base/repos/config_loader_spec.rb
spec/nanoc/base/repos/site_loader_spec.rb

This hides the environment behind a feature flag, so that it can be part of the next patch release as a pre-release feature.
Also see nanoc/rfcs#5.

Hide env behind feature flag

---

lib/nanoc/base/feature.rb
spec/nanoc/base/feature_spec.rb

Allows defining features tied to a specific version.
Features are defined this way:
```ruby
Nanoc::Feature.define('profiler', version: '4.3')
```
The version describes when (in this case, 4.3.x) the feature is considered experimental. A new test ensures that no features are defined for past or future versions.
* How will we ensure that the tests are run *after* changing the version number? This needs to happen in order to verify feature versions.

Improve Nanoc::Feature API

---

lib/nanoc/cli.rb

In #910, some interaction with Bundler was introduced. However, when running nanoc from commandline immediately, without a Gemfile or .bundle directory being present (when creating a new site, for example), a script created by rubygems gets called, which includes Bundler. This would give the following error any time nanoc gets called from CLI
```
☁  Projects  nanoc create-site cv
Captain! We’ve been hit!
Message:
Bundler::GemfileNotFound: Could not locate Gemfile or .bundle/ directory
````
We add a rescue block in order to prevent nanoc from crashing. If there's no Gemfile, nothing should happen anyway.
https://gist.github.com/werthen/ffa7610068ea5afa956fe5f12c8d20ea

BUGFIX: Bundler::GemfileNotFound

---

lib/nanoc/cli/commands/deploy.rb
spec/nanoc/cli/commands/deploy_spec.rb

This change allows the deploy target to be specified as an argument, in addition to an option. This makes the command easier to use, as `-t` (or `--target`) is not necessary. For example,
```
nanoc deploy staging
```
can now be used in addition to
```
nanoc deploy --target staging
nanoc deploy -t staging
```
As this is an enhancement to an existing feature,  this’ll go in the next patch release (4.3.3).

Allow specifying deploy target as argument

---

lib/nanoc/cli/commands/compile.rb
spec/nanoc/regressions/gh_942_spec.rb

Prune before compiling, to delete any files/directories that could interfere with new files/directories being generated. Fixes #942.

Prune before compiling (fixes #942)

---

lib/nanoc/extra/pruner.rb
spec/nanoc/regressions/gh_948_spec.rb

When `auto_prune: true` and the output directory does not exist, `compile` will crash.
Fixes #948.

Fix prune crash when output dir does not exist

---

lib/nanoc/rule_dsl/compiler_dsl.rb
spec/nanoc/regressions/gh_951_spec.rb
test/rule_dsl/test_compiler_dsl.rb

Fixes #951.
The regex generated from legacy patterns now makes the trailing slash optional. In addition, it escapes periods, which are intended to be literal.

Fix support for legacy patterns combined with full identifiers

---

lib/nanoc/cli/command_runner.rb
spec/nanoc/cli/commands/show_rules_spec.rb

This makes “Loading site… done” be written to stderr rather than stdout.

Write status information to stderr

---

lib/nanoc/base/feature.rb
spec/nanoc/base/feature_spec.rb
spec/nanoc/base/repos/config_loader_spec.rb

This adds `Nanoc::Feature.enable`, which executes a given block with a give feature enabled. For example:
```ruby
Nanoc::Feature.enable(Nanoc::Feature::SHELL_EXEC) do
end
```
This is intended for tests which require these features to be enabled. For this reason, this PR also modifies the existing tests to make use of this new functionality.

Add Nanoc::Feature.enable

---

lib/nanoc/extra/core_ext/time.rb
lib/nanoc/helpers/blogging.rb
spec/nanoc/helpers/blogging_spec.rb
test/extra/core_ext/test_time.rb
test/helpers/test_xml_sitemap.rb

* Make `#attribute_to_time` convert `Date` to UTC (rather than local) `Time`
* Make `#to_iso8601_date` return UTC representation
`#to_iso8601_date` currently deliberately does not convert to UTC, because the date is supposed to be timezone-agnostic.
For example, if I were to write `2016-10-22`, then I intend that specific day, no matter where I am, and what time it is. Converting this date to UTC first could change that date to `2016-10-21` or `2016-10-23`, which is not what’s intended.
Unfortunately, this does not hold up when I write a `Time` (e.g. `2016-10-22 10:15:00`) rather than a `Date` and then run it through `#to_iso8601_date`.
In order to make both cases work,  this PR converts `Date` to UTC `Time`s rather than local `Time`s, and then makes `#to_iso8601_date` convert to UTC. …

Fix timezone issues in #attribute_to_time/#to_iso8601_date

---

lib/nanoc/cli/commands/shell.rb
spec/nanoc/cli/commands/shell_spec.rb

This makes the `shell` command load item reps, and thus makes paths available. For example, the following now works:
```ruby
@items.find_all('/doc/*.dmark').map { |i| i.path.to_s }
```
Fixes #955.

Expose reps and paths in shell command

---

lib/nanoc/base/services/action_provider.rb
lib/nanoc/base/services/item_rep_router.rb
lib/nanoc/rule_dsl/action_provider.rb
lib/nanoc/rule_dsl/rule_memory_calculator.rb
spec/nanoc/base/services/item_rep_router_spec.rb
spec/nanoc/regressions/gh_954_spec.rb

This makes `rep.path` in compilation rules not be nil when the rep gets a route assigned to it later on.
The following now behaves as expected:
```ruby
compile '/**/*' do
filter :relativize_paths, type: :html unless rep.path.nil?
write item.identifier.without_ext + '.html'
end
```
The `:relativize_paths` filter _will_ now be executed, even though the path is only assigned later.
This happens because compilation is now done in three steps:
1. Calculate rule memory, and build snapshot-path pairs for each rep
2. Recalculate rule memory using snapshot-path pairs calculated before
3. Perform actual compilation
Previously, there were only two steps:
1. Calculate rule memory
2. Perform actual compilation
The rule memory depends on the paths, and so the extra step is necessary.
Fixes #954.

Allow querying path in compilation rule

---

lib/nanoc/extra/checking/dsl.rb
test/extra/checking/test_dsl.rb

This sets `__FILE__` to an absolute path in the Checks file, which allows doing e.g. `File.dirname(__FILE__)`.

Use absolute filename for Checks file

---

lib/nanoc/extra/pruner.rb

* Unify `File.file?` and `File.directory?` calls into a single `File.ftype` call
* Use `Find.prune` to limit the file search tree
For the Nanoc web site, this results in a ±100x speedup (unscientific results), going from ±0.5s to ±0.005s.
No test changes, as the behavior has not changed.

Speed up pruner

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/views.rb
lib/nanoc/base/views/item_rep_collection_view.rb
lib/nanoc/base/views/post_compile_item_rep_collection_view.rb
lib/nanoc/base/views/post_compile_item_rep_view.rb
lib/nanoc/base/views/post_compile_item_view.rb
spec/nanoc/base/views/item_rep_collection_view_spec.rb
spec/nanoc/base/views/post_compile_item_rep_collection_view_spec.rb
spec/nanoc/base/views/post_compile_item_rep_view_spec.rb
spec/nanoc/base/views/post_compile_item_view_spec.rb
test/base/test_compiler.rb

This revisits #894.
It’s possible for the compiler to only recompile outdated reps, as long as the compiled content in the preprocessor can still be accessed. This is why `PostCompileItemRepView` is introduced.
(Add issue IDs for related issues here.)

Only compile outdated reps

---

lib/nanoc/cli/commands/show-data.rb
lib/nanoc/cli/commands/show-rules.rb
spec/nanoc/cli/commands/show_rules_spec.rb

The `show-{data,rules}` commands do not load or describe the item reps. This pull request builds the reps in the setup of the command so they can be described.
The `show-{data,rules}` commands do not load or describe the item reps, so the methods that use the reps in these commands are actually operating on an empty `Nanoc::Int::ItemRepRepo` and do not output anything helpful.
I'm not sure whether this is the best way to accomplish loading the reps, but this simple change enables these two commands to work as expected. 
~~About the lack of tests, the [existing test for `show-rules`](https://github.com/nanoc/nanoc/blob/e148ecc699406fa50c5839645ae60d64df2cc93f/spec/nanoc/cli/commands/show_rules_spec.rb) creates stubs for the item reps, and does not test the actual setup of the command. I'm …

Build the reps in the show commands so they can be described

---

lib/nanoc/filters/kramdown.rb
test/filters/test_kramdown.rb

This PR does two things in two commits:
- tell which item and rep produces a kramdown warning
- implements warning filtering (see #675) as kramdown itself as no warning switches
The `:warning_filters` array should be documented on https://nanoc.ws as part of the filters reference documentation.

Kramdown warnings

---

lib/nanoc/base/context.rb
test/base/test_context.rb

This adds `Context#include`, which makes it possible to call `include` directly from the `shell` command:
```
% bundle exec nanoc shell
Loading site… done
> include Nanoc::Helpers::HTMLEscape
=> #<Class:…>
> link_to 'not where you want to go', @items['/404.*']
=> "<a href=\"/404.html\">not where you want to go</a>"
```

Add Context#include

---

lib/nanoc/cli/commands/compile.rb

Stop playing around with the GC manually.
Previous versions of Nanoc (3.x) had the problem of occasionally running very slowly due to spending large amounts of time in the garbage collector (79% for one site).
As a temporary workaround until either Nanoc and/or Ruby improved memory handling, I added a `GCController` which disables and enables the GC at certain times in order to eliminate needless GC activity. I knew from the start that this was a hack and would cause problems, but luckily very few people reported having problems with it—until now, I guess (#972).
Ruby 2.2 and up have generational GC, which greatly reduces the demand on the garbage collector. This should eliminate the need for this GC hack.
* #972 — “Getting "Killed" on Ubuntu 16.04.1 LTS”

Remove GCController

---

lib/nanoc/rule_dsl/recording_executor.rb
spec/nanoc/regressions/gh_974_spec.rb
spec/nanoc/rule_dsl/recording_executor_spec.rb

This allows paths to be specified as an identifier.
For routing rules, `#write` calls and `#snapshot` calls with a path, this is particularly useful.
Fixes #974.

Allow routing to identifier

---

Gemfile
lib/nanoc.rb
lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/compilation/filter.rb
lib/nanoc/base/entities/item_rep.rb
lib/nanoc/cli/commands/compile.rb
lib/nanoc/helpers/capturing.rb
spec/nanoc/base/compiler_spec.rb
spec/nanoc/cli/commands/compile/file_action_printer_spec.rb
spec/nanoc/cli/commands/compile/timing_recorder_spec.rb
spec/nanoc/filters/less_spec.rb
spec/nanoc/helpers/capturing_spec.rb
spec/spec_helper.rb
test/base/test_item_rep.rb
test/filters/test_less.rb

Perform compilation in a resumable fiber.
The compilation of an item rep can currently fail due to an unmet dependency (a `Nanoc::Int::Errors::UnmetDependency` exception will be raised). This is suboptimal for two reasons:
* All work done on compiling this item representation is lost, and will have to be started over.
* In a worst-case scenario, an item representation that has many hard dependencies on other other item representations might be compiled in a way that causes the item representation to be compiled over and over again, and failing due to unmet dependencies over and over again. This could drive the compilation time up by orders of magnitude.
The approach in this PR eliminates used work. When an unmet dependency occurs, compilation will continue at the point where the unmet …

Use fibers to minimize redundant work

---

lib/nanoc/cli/commands/view.rb
spec/nanoc/cli/commands/view_spec.rb

This lets `nanoc view` serve `index.xhtml` when a directory is requested, rather than only `index.html`.
Implements #986.

Let `nanoc view` serve /index.xhtml

---

lib/nanoc/base/compilation/outdatedness_checker.rb
spec/nanoc/base/services/outdatedness_checker_spec.rb

When requesting the outdatedness reason for an item, the first outdated item rep would be returned, rather than the outdatedness reason.
This has no effective impact, but is still wrong.

Fix outdatedness reason for item

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/compilation/outdatedness_checker.rb
lib/nanoc/base/compilation/outdatedness_reasons.rb
lib/nanoc/base/entities/document.rb
lib/nanoc/base/repos/checksum_store.rb
lib/nanoc/base/repos/data_source.rb
lib/nanoc/base/services/checksummer.rb
lib/nanoc/data_sources/filesystem.rb
spec/nanoc/base/checksummer_spec.rb
spec/nanoc/base/entities/document_spec.rb
spec/nanoc/base/services/outdatedness_checker_spec.rb
spec/nanoc/data_sources/filesystem_spec.rb
test/base/test_data_source.rb
test/base/test_outdatedness_checker.rb

Record separate checksums for item content and attributes, so that later on, dependencies can be more granular.
This change requires updating the documentation to mention the existence of `content_checksum_data` and `attributes_checksum_data`. (Not urgent; `checksum_data` remains functional.)

Split content and attributes checksums

---

lib/nanoc/base/feature.rb
lib/nanoc/base/repos/config_loader.rb
lib/nanoc/cli/commands/nanoc.rb
spec/nanoc/base/repos/config_loader_spec.rb
spec/nanoc/base/repos/site_loader_spec.rb
spec/nanoc/regressions/gh_937_spec.rb

This removes the feature flag around the environments feature and makes it officially supported. Best viewed with [?w=1](https://github.com/nanoc/nanoc/pull/993/files?w=1).
This requires a 4.4 release.

Enable environments feature

---

lib/nanoc/base/views/mixins/document_view_mixin.rb
spec/nanoc/base/views/document_view_spec.rb
spec/nanoc/base/views/item_view_spec.rb
test/filters/test_xsl.rb

~Fixes #924.~
This fixes an issue with the XSL filter not generating a correct dependency on the layout.

Make DocumentViewMixin#raw_content generate dependency

---

lib/nanoc/base/entities/directed_graph.rb
lib/nanoc/base/repos/dependency_store.rb
lib/nanoc/base/services/dependency_tracker.rb
lib/nanoc/base/services/executor.rb
lib/nanoc/base/services/filter.rb
lib/nanoc/base/views/item_rep_view.rb
lib/nanoc/base/views/mixins/document_view_mixin.rb
lib/nanoc/cli/commands/show-data.rb
lib/nanoc/helpers/capturing.rb
lib/nanoc/helpers/rendering.rb
spec/nanoc/base/filter_spec.rb
spec/nanoc/base/repos/dependency_store_spec.rb
spec/nanoc/base/services/dependency_tracker_spec.rb
spec/nanoc/base/services/executor_spec.rb
spec/nanoc/base/views/document_view_spec.rb
spec/nanoc/base/views/item_rep_view_spec.rb
spec/nanoc/cli/commands/show_data_spec.rb
spec/nanoc/helpers/capturing_spec.rb
spec/nanoc/helpers/rendering_spec.rb
test/base/test_directed_graph.rb
test/filters/test_xsl.rb

This is part of what #991 wants to achieve, without making changes to the outdatedness checker yet.

Record finer grained dependencies

---

lib/nanoc/base/compilation/compiler.rb
lib/nanoc/base/errors.rb
lib/nanoc/base/services/executor.rb
lib/nanoc/base/services/item_rep_selector.rb
lib/nanoc/cli/command_runner.rb
lib/nanoc/cli/error_handler.rb
lib/nanoc/helpers/rendering.rb
spec/nanoc/base/compiler_spec.rb
spec/nanoc/base/services/executor_spec.rb
spec/nanoc/base/services/item_rep_selector_spec.rb
test/cli/test_error_handler.rb

Remove the compiler stack and print the details of the current in-compilation item rep.
This is done in two steps:
1. Wrap every error raised during compilation in an error decorator that will contain the current item rep that is being compiled, and ensure that item rep is printed in the error handler.
2. Remove the now unused compiler stack.
Before:
After:

Remove compiler stack

---

lib/nanoc/filters/less.rb
spec/nanoc/filters/less_spec.rb

In Less, `@import`s relative to the site directory would not generate the proper dependencies. This fixes that.
This also refactors the source for the `:less` filter (in separate commits).

Fix Less filter dependencies

---

lib/nanoc/helpers/breadcrumbs.rb
spec/nanoc/helpers/breadcrumbs_spec.rb

This adds support for full identifiers (e.g. `/projects/nanoc.md`) to `#breadcrumbs_trail`. Currently, only legacy identifiers (e.g. `/projects/nanoc/`) are supported.
Fix for #1010.
This change first of all refactors the existing code to construct a prefix array for a given item identifier. For example, `/projects/nanoc/` is turned into `['', '/projects', '/projects/nanoc']`. This in turn is used to construct the array of item identifiers which will be the breadcrumbs trail.
For full identifiers, the procedure is the same, with the main difference that the item matching `/index.*` is treated specially. This item is considered the root item and has the same role as the `/` item when using legacy identifiers.
* #1010

Support full identifiers in breadcrumbs

---

lib/nanoc/base/repos/compiled_content_cache.rb
lib/nanoc/base/services/compiler_loader.rb
spec/nanoc/base/compiler_spec.rb
spec/nanoc/base/repos/compiled_content_cache_spec.rb
spec/nanoc/base/views/post_compile_item_rep_view_spec.rb
test/base/test_compiler.rb

This ensures that no cached compiled content is loaded for items that do not exist. This will prevent the compiled content cache from ever growing.
A partial fix for #1004.

Prune old data from compiled content cache

---

lib/nanoc/helpers/blogging.rb
test/helpers/test_blogging.rb

This constructs the Atom feed’s `<updated>` from the most recent `updated_at` or `created_at`, rather than the last article’s `created_at`.
Fix for #1007. In addition, `updated_at` is now preferred to `created_at`, if available.

Use most recent timestamp for <updated> in Atom feed

---

lib/nanoc/base/services/item_rep_router.rb
spec/nanoc/base/services/item_rep_router_spec.rb
spec/nanoc/regressions/gh_1015_spec.rb

Raise error if item rep path does not start with slash

---

lib/nanoc/base/compilation/outdatedness_checker.rb
lib/nanoc/base/entities/document.rb
lib/nanoc/base/repos/dependency_store.rb
spec/nanoc/base/services/outdatedness_checker_spec.rb
spec/nanoc/integration/outdatedness_integration_spec.rb

This is the first step in making dependencies more fine-grained. For the time being, this only affects
* attribute dependencies
* raw content dependencis

Use fine-grained attr/content dependencies

---

lib/nanoc/base/repos/dependency_store.rb
spec/nanoc/base/repos/dependency_store_spec.rb
spec/nanoc/cli/commands/show_data_spec.rb

Until recently, dependencies in Nanoc were unqualified: a dependency of one item onto another object (item or layout) had no information about what property the item had a dependency on. This changed in Nanoc 4.4.1, which records dependency properties.
The dependencies store (in `tmp/`) might still have old dependencies with no prop information. Additionally, even in the most recent release (4.4.3), Nanoc would generate dependencies without props for new items (see eb801a6e7028755f0a630412e283a28e8aa35fc3 for a fix).
Prop-less dependencies should be considered as dependencies with all props. This matches the historic behavior of how Nanoc treats dependencies before the upcoming Nanoc 4.4.4 release (which will make use of fine-grained dependencies to reduce outdatedness).

Treat deps without props as deps with all props

---

lib/nanoc/base/compilation/outdatedness_checker.rb
spec/nanoc/base/services/outdatedness_checker_spec.rb
spec/nanoc/integration/outdatedness_integration_spec.rb

Nanoc’s outdatedness checking system is currently not able to handle composite outdatedness reasons, and is therefore not able to express outdatedness such as “raw content *and* attributes modified”.
This is problematic for the current finer-grained dependency/outdatedness implementation; changing both raw content *and* attributes will cause the attribute change to be ignored, and items that have an attribute dependency will therefore not be considered as outdated.
**This workaround:** For both attribute and raw content dependencies, consider both raw content and attributes to be modified. This approach is not incorrect, but also not optimal.
**The fix:** Eventually, allow multiple outdatedness reasons to be returned.

Work around lack of composite outdatedness reasons

---

lib/nanoc/base/compilation/outdatedness_checker.rb
lib/nanoc/base/compilation/outdatedness_reasons.rb
lib/nanoc/base/entities/rule_memory.rb
lib/nanoc/base/services/action_provider.rb
lib/nanoc/base/services/outdatedness_rules.rb
lib/nanoc/rule_dsl/action_provider.rb
lib/nanoc/rule_dsl/rule_memory_calculator.rb
spec/nanoc/base/entities/outdatedness_status_spec.rb
spec/nanoc/base/services/outdatedness_checker_spec.rb
spec/nanoc/base/services/outdatedness_rules_spec.rb

This makes path dependencies not unconditionally cause outdatedness.

Add fine-grained path dependencies

---

lib/nanoc/base/compilation/outdatedness_checker.rb
spec/nanoc/base/services/outdatedness_checker_spec.rb

This prevents transitive dependencies from needlessly generating outdatedness. Transitive dependencies should only be considered if they apply to compiled content.
Given:
* Item A has an **attribute dependency** on item B
* Item B has an attribute dependency on item C
When:
* Item C’s attributes change
Then:
* Item B is outdated
* Item A **is not** outdated
Given:
* Item A has a **compiled content dependency** on item B
* Item B has an attribute dependency on item C
When:
* Item C’s attributes change
Then:
* Item B is outdated
* Item A **is** outdated

Propagate outdatedness only across compiled-content deps

---

lib/nanoc/base/repos/dependency_store.rb
spec/nanoc/base/repos/dependency_store_spec.rb
spec/nanoc/base/services/dependency_tracker_spec.rb
test/base/test_dependency_tracker.rb

When an item is added, Nanoc generates a dependency of all items onto this new item. This is done because Nanoc can‘t accurately infer whether a newly added item will cause an existing item to need recompilation. This approach is crude and definitely something I’d like to improve, but at the same time it is also *correct*, which for me is the most important bit.
Unfortunately, radically changing the directory structure of a site means that dependency generation blows up. While Nanoc is apparently doing nothing (right after Compiling…), it is generating all these dependencies, which takes minutes. On top of that, all these artificially new dependencies make memory usage increase up to the point where my laptop cannot handle it anymore.
This fix: Mark new items as “new”, and when looking up …

Optimise recording deps on new items

---

lib/nanoc/base/services/compiler.rb
lib/nanoc/base/services/executor.rb
lib/nanoc/base/views/post_compile_item_rep_view.rb
lib/nanoc/base/views/view_context.rb
lib/nanoc/checking/check.rb
lib/nanoc/cli/commands/shell.rb
lib/nanoc/helpers/rendering.rb
lib/nanoc/rule_dsl/action_provider.rb
lib/nanoc/rule_dsl/recording_executor.rb
lib/nanoc/rule_dsl/rule_memory_calculator.rb
lib/nanoc/spec.rb
spec/nanoc/base/compiler_spec.rb
spec/nanoc/base/filter_spec.rb
spec/nanoc/base/services/executor_spec.rb
spec/nanoc/base/views/document_view_spec.rb
spec/nanoc/base/views/item_rep_view_spec.rb
spec/nanoc/base/views/item_view_spec.rb
spec/nanoc/base/views/mutable_document_view_spec.rb
spec/nanoc/base/views/post_compile_item_rep_view_spec.rb
spec/nanoc/rule_dsl/rule_context_spec.rb
spec/nanoc/rule_dsl/rule_memory_calculator_spec.rb
test/filters/test_xsl.rb
test/helpers/test_capturing.rb
test/helpers/test_xml_sitemap.rb

This creates
* `CompilationContext`
* Three `ItemRepCompiler` classes:
* `ResumingItemRepCompiler` — Handles fiber management to support suspending and resuming item rep compilation. Always calls the next compiler (`CachingItemRepCompiler`). Also handles notifications.
* `CachingItemRepCompiler` — If the given item rep is not outdated and cached compiled content is available, reuses said content. Otherwise, calls the next compiler (`RecalculatingItemRepCompiler`).
* `RecalculatingItemRepCompiler` — (Re)calculate the compiled content of a given item rep. Also sets up dependency tracking.

Refactor: Split up compiler

---

lib/nanoc/base/services/compiler.rb
lib/nanoc/base/services/executor.rb
lib/nanoc/base/services/item_rep_writer.rb
spec/nanoc/base/item_rep_writer_spec.rb
spec/nanoc/base/services/executor_spec.rb

This will bring the `Executor` class closer to something stateless. All that remains is not updating `snapshot_contents`.

Refactor: Move item rep writing out of executor

---

lib/nanoc/base/entities/item_rep.rb
spec/nanoc/base/entities/item_rep_spec.rb
spec/nanoc/base/filter_spec.rb
spec/nanoc/regressions/gh_1035_spec.rb
spec/spec_helper.rb
test/base/test_item_rep.rb

Fix fetching text content of now-binary item rep

---

lib/nanoc/base/entities/rule_memory.rb
lib/nanoc/rule_dsl/rule_context.rb
lib/nanoc/rule_dsl/rule_memory_calculator.rb
spec/nanoc/regressions/gh_1037_spec.rb
spec/nanoc/rule_dsl/rule_context_spec.rb
spec/nanoc/rule_dsl/rule_memory_calculator_spec.rb

Fixes #1037.
* * *
The way snapshots are handled is currently less than ideal. I’d like them to be decoupled, so that
```ruby
write '/something.txt'
snapshot :something
```
or
```ruby
snapshot :something
write '/something.txt'
```
would both create a snapshot named `:something`, pointing to the file `/something.txt`.
Perhaps even
```ruby
snapshot :something
write '/something.txt'
write '/same.txt'
```
which would create a snapshot pointing to two files, or
```ruby
snapshot :something
write '/something.txt'
snapshot :same
```
which would be two snapshots pointing to the same file.
None of this currently works, and I’m hesitant to call it a bug (it’s not documented behavior!) but it would still be nice to have, because it makes sense. Out of scope for this PR, though.

Allow calling #write more than once

---

Gemfile
lib/nanoc/base/entities/processing_actions/snapshot.rb
lib/nanoc/base/entities/rule_memory.rb
lib/nanoc/rule_dsl/recording_executor.rb
lib/nanoc/rule_dsl/rule_memory_calculator.rb
spec/nanoc/base/entities/processing_actions/snapshot_spec.rb
spec/nanoc/base/entities/rule_memory_spec.rb
spec/nanoc/rule_dsl/recording_executor_spec.rb
spec/nanoc/rule_dsl/rule_memory_calculator_spec.rb
spec/spec_helper.rb

This turns `RecordingExecutor` into a dumb service that does nothing more than record actions.
The logic what was in `RecordingExecutor` for dealing with paths defined in routing rules is now in `RuleMemoryCalculator`, where it’s a transformation using the new `RuleMemory#map`. This new `#map` function will make it easy to make changes to the rule memory in the future.

Refactor: Move path calculation into RuleMemCalculator

---

.rubocop.yml
lib/nanoc/checking/checks/external_links.rb
lib/nanoc/extra.rb
lib/nanoc/extra/parallel_collection.rb
nanoc.gemspec
spec/nanoc/cli/commands/deploy_spec.rb
spec/nanoc/extra/parallel_collection_spec.rb
spec/spec_helper.rb

This replaces the `parallel` dependency with a `ParallelCollection` that looks like this:
```ruby
ints = [1, 2, 3, 4, 5]
col = Nanoc::Extra::ParallelCollection.new(ints, parallelism: 10)
p(col.map { |e| sleep rand; e * 10 })
```
This runs in ≤1s (roughly) and prints the array `[10, 20, 30, 40, 50]` *in any order*.

Add ParallelCollection

---

lib/nanoc/data_sources/filesystem.rb
spec/nanoc/data_sources/filesystem_spec.rb
spec/nanoc/integration/outdatedness_integration_spec.rb
spec/nanoc/regressions/gh_1045_spec.rb

Fixes #1045.
The checksum data provided by the filesystem data source did not include extra attributes (most specifically `mtime`).

Include extra attributes in filesystem checksum

---

lib/nanoc/checking/checks/external_links.rb

remove require 'parallel' in external links checks
This change proposes to remove the require statement on parallel as it seems it is not used here anymore, and is dropped from the Gemfile.

remove require 'parallel' in external links checks

---

lib/nanoc/deploying/deployers.rb
lib/nanoc/deploying/deployers/git.rb
spec/nanoc/cli/commands/deploy_spec.rb
spec/nanoc/deploying/git_spec.rb
spec/spec_helper.rb
test/deploying/test_git.rb

This copies [nanoc-git](https://github.com/nanoc/nanoc-git) into the `nanoc` repository.
With Git being a commonly used deployment strategy (for `gh-pages` most commonly), it does not make sense to have `nanoc-git` not be part of the standard Nanoc distribution.
This also
* adds new tests
* removes some of the implicit behavior
* adds dedicated errors with better descriptions

Bundle Git deployer

---

lib/nanoc/base/errors.rb
spec/nanoc/base/services/executor_spec.rb

The “cannot layout binary item” error would not properly print the item identifier.

Fix CannotLayoutBinaryItem error (missing # before {})

---

lib/nanoc/base/views/item_rep_collection_view.rb
lib/nanoc/extra/parallel_collection.rb

Fixes #1061.
Integer exists on Ruby 2.3 (and before) too, so `Fixnum` can be safely replace with `Integer`.

Use Integer instead of Fixnum

---

lib/nanoc/rule_dsl/rule_memory_calculator.rb
spec/nanoc/regressions/gh_1064_spec.rb
spec/nanoc/rule_dsl/rule_memory_calculator_spec.rb

Create :pre snapshot if none already exist

---

lib/nanoc/base/repos/checksum_store.rb
lib/nanoc/base/repos/compiled_content_cache.rb
lib/nanoc/base/repos/dependency_store.rb
lib/nanoc/base/repos/outdatedness_store.rb
lib/nanoc/base/repos/rule_memory_store.rb
lib/nanoc/base/repos/store.rb
spec/nanoc/regressions/gh_1067_spec.rb
test/base/test_store.rb

Do not store temp data per-env

---

lib/nanoc/helpers/capturing.rb
spec/nanoc/helpers/capturing_spec.rb

Implements #1066.
In addition to what is currently possible,
```ruby
content_for(:head) { _erbout << 'stuff' }
```
it is now possible to pass a string, rather than a block that changes `_erbout`, to `#content_for`:
```ruby
content_for(:head, 'stuff')
```
Note that
```ruby
content_for(:head) { 'stuff' }
```
will (still) not have any effect.
Documentation will be updated afterwards.

Allow setting content_for directly

---

lib/nanoc/cli/commands/compile.rb
spec/nanoc/cli/commands/compile/timing_recorder_spec.rb

Fix table formatting in compile --verbose
Dynamically resize the table depending on the cell lengths.
I normalized the space between cells to be 3 characters wide.
#1005

Fix #1005 - table formatting in compile --verbose

---

lib/nanoc/data_sources/filesystem.rb
spec/nanoc/data_sources/filesystem_spec.rb

The filesystem data source stores the entire content and dumped attributes as the checksum. This PR turns the checksum into SHA1 hashes, which speeds up checksum comparisons and reduces memory usage.

Store compact checksums

---

lib/nanoc/base/entities/context.rb

Metaclasses in Ruby do not appear to be garbage-collected, which means that all `Nanoc::Int::Context` instances indefinitely held on, via the metaclass, to the hash passed to them.
This replaces the `define_method` approach with a `method_missing` one, which fixes the memory leak.

Fix memory leak in Context

---

lib/nanoc/base/services/item_rep_selector.rb
spec/nanoc/base/services/item_rep_selector_spec.rb

The item rep selector now prioritises recompiling item reps that are a hard dependency of another item rep.
This keeps the number of suspended item rep compilations down, and can lead to significant reductions in memory usage (memory usage went down by 40% on nanoc.ws, from ±100 MB peak to ±60 MB peak).

Prioritise recompiling dependent reps

---

lib/nanoc/base/services/item_rep_selector.rb
spec/nanoc/base/services/item_rep_selector_spec.rb

This change gives (secondary) priority to in-progress reps, in order to reduce in-flight (suspended) compilations, and thus work towards finishing off work before starting new work.
This change reduces memory usage slightly.

Prioritise in-progress reps

---

lib/nanoc/base/repos/snapshot_repo.rb
lib/nanoc/base/views/item_rep_view.rb
spec/nanoc/regressions/gh_1082a_spec.rb
spec/nanoc/regressions/gh_1082b_spec.rb

Require compilation before calling #binary?

---

lib/nanoc/base/entities/snapshot_def.rb
lib/nanoc/base/views/item_rep_view.rb
lib/nanoc/rule_dsl/rule_memory_calculator.rb
lib/nanoc/spec.rb
spec/nanoc/base/compiler_spec.rb
spec/nanoc/base/entities/item_rep_spec.rb
spec/nanoc/base/repos/snapshot_repo_spec.rb
spec/nanoc/base/services/compiler/stages/compile_reps_spec.rb
spec/nanoc/base/services/executor_spec.rb
spec/nanoc/base/views/item_rep_view_spec.rb
spec/nanoc/base/views/item_view_spec.rb
spec/nanoc/regressions/gh_1082c_spec.rb
spec/nanoc/regressions/gh_1082d_spec.rb
spec/nanoc/rule_dsl/rule_memory_calculator_spec.rb

This records the binary-ness in the snapshot definition, so that it can be referenced later, without the item rep needing to be compiled first.
Fixes #1082.

Record snapshot definition binary-ness

---

lib/nanoc/checking/checks/html.rb
lib/nanoc/checking/checks/w3c_validator.rb
test/checking/checks/test_html.rb
test/fixtures/vcr_cassettes/html_run_error.yml

`validator.nu` is the preferred validator.
The `require 'resolv-replace'` is needed to avoid w3c-validators/w3c_validators/issues/35. :(

Use validator.nu for validating HTML

---

lib/nanoc/cli/commands/compile.rb
spec/nanoc/regressions/gh_1102_spec.rb

Fixes #1102.
Now that the same raw path can be shared by multiple snapshots, the compile command accidentally printed the paths for every snapshot.

Do not print multiple skips

---

lib/nanoc/base/services/compiler/phases/cache.rb
spec/nanoc/base/services/compiler/phases/cache_spec.rb
spec/nanoc/regressions/gh_1094_spec.rb
spec/spec_helper.rb

Fixes #1094.
Nanoc attempts to cache _binary_ content, which fails because the temporary files for binary content will have been removed in between runs.

Do not reuse cached binary content

---

lib/nanoc.rb
lib/nanoc/cli/commands/compile.rb
lib/nanoc/telemetry.rb
lib/nanoc/telemetry/counter.rb
lib/nanoc/telemetry/labelled_counter.rb
lib/nanoc/telemetry/labelled_summary.rb
lib/nanoc/telemetry/registry.rb
lib/nanoc/telemetry/stopwatch.rb
lib/nanoc/telemetry/summary.rb
spec/nanoc/cli/commands/compile/timing_recorder_spec.rb
spec/nanoc/telemetry/counter_spec.rb
spec/nanoc/telemetry/labelled_counter_spec.rb
spec/nanoc/telemetry/labelled_summary_spec.rb
spec/nanoc/telemetry/stopwatch_spec.rb
spec/nanoc/telemetry/summary_spec.rb
spec/nanoc/telemetry_spec.rb

This generalises the telemetry that’s currently already in Nanoc, to be more usable for other purposes.

Add basic telemetry implementation

---

lib/nanoc/cli/commands/compile.rb
spec/nanoc/cli/commands/compile/timing_recorder_spec.rb

The timing recorders breaks on `<% filter(:…) %> … <% end %>`.

Fix timing recorder for nested filter calls

---

lib/nanoc/cli/commands/compile.rb
spec/nanoc/cli/commands/compile/timing_recorder_spec.rb

All but the inner filter in a nested filter call won’t be recorded properly when compilation gets suspended.
Timing is hard :(

Pause outer stopwatch

---

lib/nanoc/cli/commands/compile.rb
lib/nanoc/telemetry/labelled_counter.rb
lib/nanoc/telemetry/labelled_summary.rb
spec/nanoc/telemetry/labelled_counter_spec.rb
spec/nanoc/telemetry/labelled_summary_spec.rb
spec/nanoc/telemetry_spec.rb

Improve handling of labels in telemetry API

---

lib/nanoc/base/services/compiler/phases.rb
lib/nanoc/base/services/compiler/phases/abstract.rb
lib/nanoc/base/services/compiler/phases/cache.rb
lib/nanoc/base/services/compiler/phases/mark_done.rb
lib/nanoc/base/services/compiler/phases/recalculate.rb
lib/nanoc/base/services/compiler/phases/resume.rb
lib/nanoc/base/services/compiler/phases/write.rb
lib/nanoc/base/services/compiler/stages/compile_reps.rb
lib/nanoc/cli.rb
lib/nanoc/cli/commands/compile.rb
lib/nanoc/cli/commands/nanoc.rb
spec/nanoc/base/compiler_spec.rb
spec/nanoc/base/services/compiler/phases/abstract_spec.rb
spec/nanoc/base/services/compiler/phases/cache_spec.rb
spec/nanoc/cli/commands/compile/timing_recorder_spec.rb

This introduces a superclass for all phases, that can notify started/stopped, yielded to/resumed from children, and abortion due to exception:
This will make it easier to add telemetry:
* start: start recording
* yield: stop  recording
* resume: restart recording
* end: stop recording
* abort: stop recording (recording might already be turned off)
This will only be printed if `--verbose` is given at least twice (e.g. `nanoc co -VV`).

Add telemetry for phases

---

lib/nanoc/rule_dsl/rule_context.rb
spec/nanoc/rule_dsl/rule_context_spec.rb

This adds
```ruby
write ext: 'html'
```
as an alternative to
```ruby
write item.identifier.without_exts + '.html'
```

Allow calling #write with ext: param

---

lib/nanoc/base/entities/directed_graph.rb
lib/nanoc/base/errors.rb
lib/nanoc/base/services/item_rep_selector.rb
spec/nanoc/base/directed_graph_spec.rb
spec/nanoc/base/errors/dependency_cycle_spec.rb
spec/nanoc/regressions/gh_1040_spec.rb
test/base/test_compiler.rb

Fixes #1111. This prints the first cycle, which should be enough information:
```
The site cannot be compiled because there is a dependency cycle:
(1) item /b.md, rep :default, depends on
(2) item /c.md, rep :default, depends on
(3) item /d.md, rep :default, depends on
(4) item /e.md, rep :default, depends on (1)
```

Add nice dependency cycle error

---

lib/nanoc/cli/commands/compile_listeners/timing_recorder.rb
spec/nanoc/cli/commands/compile/timing_recorder_spec.rb

Show percentiles rather than average

---

lib/nanoc/base/entities/identifiable_collection.rb
lib/nanoc/base/memoization.rb
test/base/test_memoization.rb

This changes `Memoization` to support frozen objects, and memoizes `IdentifiableCollection#[]`.

Memoized and frozen

---

lib/nanoc/base/entities/outdatedness_reasons.rb
lib/nanoc/base/services/filter.rb
lib/nanoc/base/services/outdatedness_checker.rb
lib/nanoc/base/services/outdatedness_rules.rb
lib/nanoc/filters/xsl.rb
spec/nanoc/base/filter_spec.rb
spec/nanoc/base/services/outdatedness_rules_spec.rb
spec/nanoc/regressions/gh_924_spec.rb

This allows filters to be declared as `always_outdated`, which means that item reps that use this filter will always be considered as outdated. This is useful for filters that cannot track dependencies properly.
Fixes #924.

Always recompile reps that use always-outdated filters

---

lib/nanoc/base/services/outdatedness_rules.rb

This speeds up `AttributesModified` by not repeating the same check in the case of items with multiple reps.
Example on nanoc.ws:
```
Nanoc::Int::OutdatednessRules::AttributesModified#apply │   91    273   25.0%
```
Hit rate of 25% which isn’t too high, but it is useful.

Speed up AttributesModified outdatedness rule

---

lib/nanoc/base/views/post_compile_item_rep_view.rb
lib/nanoc/checking/check.rb
spec/nanoc/base/views/post_compile_item_rep_view_spec.rb
spec/nanoc/regressions/gh_1130_spec.rb

Fixes #1130.
There are three different view contexts in Nanoc:
1. Preprocess: reps do not exist
2. Compilation: reps exist; accessing data might create dependencies
3. Postprocess: reps exist, accessing data will not create dependencies
The checks should use the postprocess views, rather than the compilation views.

Use post-compile views in checks

---

lib/nanoc/base/entities/props.rb
lib/nanoc/base/repos/dependency_store.rb
lib/nanoc/base/services/dependency_tracker.rb
lib/nanoc/base/views/mixins/document_view_mixin.rb
spec/nanoc/base/entities/props_spec.rb
spec/nanoc/base/repos/dependency_store_spec.rb
spec/nanoc/base/services/executor_spec.rb

This changes the dependency props to allow `attributes` to be either a boolean or a list of symbols:
* `true` means depending on _all_ attributes
* `false` means depending on _no_ attributes
* a list means depending on the given attributes
Next step: update outdatedness checker.

Store fine-grained attributes

---

lib/nanoc/base/services/outdatedness_checker.rb
lib/nanoc/base/services/outdatedness_rules.rb

By making `OutdatednessRule#apply` return a reason rather than a boolean, the reason can be qualified. This will make it easier to later on return _which_ attributes have been modified, rather than returning whether or not any attributes have been modified at all. Knowing which attributes have been modified will prevent another category of needless recompilations.

Refactor: Make OutdatednessRule#apply return reason

---

lib/nanoc/base/entities/outdatedness_reasons.rb
lib/nanoc/base/repos/checksum_store.rb
lib/nanoc/base/services/checksummer.rb
lib/nanoc/base/services/outdatedness_rules.rb
spec/nanoc/base/checksummer_spec.rb
spec/nanoc/base/repos/checksum_store_spec.rb
spec/nanoc/base/services/outdatedness_rules_spec.rb
test/base/test_outdatedness_checker.rb

This is in preparation for fine-grained attribute dependencies.
This might cause a small slowdown, but the fine-grained attribute triggering (which will come later) will likely more than make up for that. Additionally, some checksum caching could be introduced at a later point to mitigate any slowdowns.

Use per-attribute checksums to determine outdatedness

---

lib/nanoc/base/services/outdatedness_checker.rb
spec/nanoc/base/services/outdatedness_checker_spec.rb

This makes attribute dependencies only cause outdatedness when at least one of the dependency’s attributes are marked as outdated.

	Trigger attribute dependencies only if attributes overlap

---

lib/nanoc/base/services/compiler.rb
lib/nanoc/base/services/compiler/phases/recalculate.rb
lib/nanoc/base/services/compiler/stages/compile_reps.rb
lib/nanoc/base/services/compiler/stages/determine_outdatedness.rb
lib/nanoc/base/services/item_rep_builder.rb
lib/nanoc/base/services/item_rep_router.rb
lib/nanoc/base/services/outdatedness_checker.rb
lib/nanoc/base/services/outdatedness_rules/paths_modified.rb
lib/nanoc/base/services/outdatedness_rules/rules_modified.rb
lib/nanoc/base/services/outdatedness_rules/uses_always_outdated_filter.rb
spec/nanoc/base/compiler_spec.rb
spec/nanoc/base/services/compiler/stages/compile_reps_spec.rb

This prevents the rule memories from being recalculated when it’s not necessary. Calculating the rule memory is fairly expensive, so this leads to a nice speedup.
The design of the way the rule memory is passed around is not ideal. The `ItemRepRouter` is the service that calculates the final rule memory, and it returns that, so that it can be reused elsewhere. This is weird because `ItemRepRouter` both returns something and modifies item reps. Anyway, something to refactor later.

Cache rule memory calculator results

---

lib/nanoc/base/services/outdatedness_checker.rb
lib/nanoc/cli/commands/show-data.rb
spec/nanoc/cli/commands/show_data_spec.rb
spec/nanoc/integration/outdatedness_integration_spec.rb
spec/nanoc/integration/partial_recompilation_spec.rb
spec/nanoc/regressions/gh_970b_spec.rb
test/base/test_outdatedness_checker.rb

Printing all outdatedness reasons is the right thing to do (why only print one if there’s multiple?), and it allows the otherwise unused `#outdatedness_reason_for` method to be removed.

Print all outdatedness reasons in show-data command

---

lib/nanoc/base/services/compiler.rb
lib/nanoc/base/services/compiler/stages/determine_outdatedness.rb
lib/nanoc/base/services/outdatedness_checker.rb
spec/nanoc/base/services/outdatedness_checker_spec.rb
spec/nanoc/base/services/outdatedness_rules_spec.rb

This passes the already calculated action sequences to the outdatedness checker, which will prevent redundant recalculation.

Pass action sequences to outdatedness checker

---

lib/nanoc/cli/commands/compile_listeners/timing_recorder.rb
spec/nanoc/regressions/gh_1145_spec.rb

Fixes #1145.
The current approach of calling the `compile` command when no subcommand is specified, is problematic. Perhaps Cri (Nanoc’s backing CLI library) needs to able to handle automatic delegation to a dedicated subcommand. (Also see ddfreyne/cri/issues/53).

Recognise --verbose when calling nanoc without subcommand

---

lib/nanoc/base/entities/identifiable_collection.rb
lib/nanoc/base/views/identifiable_collection_view.rb
spec/nanoc/base/entities/identifiable_collection_spec.rb

This speeds up `#find_all`, as it’s often called with the same argument. This also speeds up other methods that rely on it, such as `#children_of`.

Cache #find_all

---

Gemfile
lib/nanoc/checking/checks/external_links.rb
lib/nanoc/filters/colorize_syntax.rb
lib/nanoc/filters/relativize_paths.rb
test/filters/colorize_syntax/test_common.rb
test/filters/test_relativize_paths.rb

Support HTML5 in relativize_paths + colorize_syntax

---

lib/nanoc/cli/commands/compile.rb
lib/nanoc/cli/commands/compile_listeners/diff_generator.rb
spec/nanoc/cli/commands/compile/diff_generator_spec.rb
spec/nanoc/integration/compile_command_spec.rb

This allows
```
nanoc compile --diff
```
or
```
nanoc --diff
```
to enable one-off diff generation.

Add --diff option to compile command

---

lib/nanoc/base/entities/action_sequence.rb
lib/nanoc/base/services.rb
lib/nanoc/base/services/action_sequence_builder.rb
lib/nanoc/rule_dsl/action_sequence_calculator.rb
lib/nanoc/rule_dsl/recording_executor.rb
spec/nanoc/base/entities/action_sequence_spec.rb
spec/nanoc/base/services/executor_spec.rb
spec/nanoc/base/services/outdatedness_checker_spec.rb
spec/nanoc/base/services/outdatedness_rules_spec.rb
spec/nanoc/rule_dsl/action_sequence_calculator_spec.rb
spec/nanoc/rule_dsl/recording_executor_spec.rb

The goal of this PR is to make `ActionSequence` an immutable object, and move the code that builds action sequences into a separate object (`ActionSequenceBuilder`?), so that computed properties of `ActionSequence` can be cached (`#serialize`, specifically).

Make ActionSequence immutable

---

lib/nanoc/base/entities.rb
lib/nanoc/base/entities/checksum_collection.rb
lib/nanoc/base/repos/checksum_store.rb
lib/nanoc/base/services/compiler.rb
lib/nanoc/base/services/compiler/stages.rb
lib/nanoc/base/services/compiler/stages/calculate_checksums.rb
lib/nanoc/base/services/compiler/stages/determine_outdatedness.rb
lib/nanoc/base/services/compiler/stages/store_pre_compilation_state.rb
spec/nanoc/base/services/compiler/stages/calculate_checksums_spec.rb

This is a refactoring that moves the checksum calculation into a separate stage, so that the calculated checksums can be reused.
Further work in a separate PR:
* Reuse precalculated checksums in the outdatedness checker
* Recalculate finer-grained checksums (content, attributes) only if parent checksums has changed

Precalculate checksums

---

lib/nanoc/base/services/compiler.rb
lib/nanoc/base/services/outdatedness_checker.rb
lib/nanoc/base/services/outdatedness_rules/attributes_modified.rb
lib/nanoc/base/services/outdatedness_rules/code_snippets_modified.rb
lib/nanoc/base/services/outdatedness_rules/configuration_modified.rb
lib/nanoc/base/services/outdatedness_rules/content_modified.rb
lib/nanoc/cli/commands/show-data.rb
spec/nanoc/base/services/outdatedness_checker_spec.rb
spec/nanoc/base/services/outdatedness_rules_spec.rb
spec/nanoc/cli/commands/show_data_spec.rb

A follow-up to #1159. This makes the outdatedness checker use the already calculated checksums, rather than calculating new ones.

Pass checksums to outdatedness checker

---

lib/nanoc/cli/cleaning_stream.rb
test/cli/test_cleaning_stream.rb

Scrub strings in cleaning stream

---

lib/nanoc/base/repos/site_loader.rb
spec/nanoc/base/repos/site_loader_spec.rb
spec/nanoc/regressions/gh_1171_spec.rb

Fixes #1171.
Turns out that `eval`’ing a string that has a magic comment (e.g. `# encoding: iso-8859-1`)  already (incorrectly) attempts to do the encoding handling. To work around that, Nanoc now reads the content in the specified encoding, converts it to UTF-8, and removes the magic comment before passing it to `eval`. Yuck!
(I have not found any other way that makes the tests pass.)

Infer code snippet encoding

---

lib/nanoc/filters/slim.rb
test/filters/test_slim.rb

When slim reports errors it currently looks like this:
```
Slim::Parser::SyntaxError: Expected attribute
(__TEMPLATE__), Line 16, Column 13
| id: 'webpage-description' }
```
It can be hard to find the offending file, so pass `filename` to slim to have errors reported like so:
```
Slim::Parser::SyntaxError: Expected attribute
layout /default.slim, Line 16, Column 13
| id: 'webpage-description' }
```

Report file name when slim encounters compilation errors

---

lib/nanoc/base/entities/configuration.rb
spec/nanoc/base/entities/configuration_spec.rb

I faced the following situation:
- I want `nanoc.yaml` to only define the `rsync` deployment url
- I want a parent `nanoc.yaml` to define other `rsync options`
----
`parent.yaml`
```
deploy:
default:
kind: rsync
options:
- --verbose
- --progress
- --recursive
- --links
- --chmod=D755,F644
- --times
- --partial
- --progress
- --compress
- --delete-during
- --force
- --exclude='.git'
```
`nanoc.yaml`
```
deploy:
default:
dst: 'example.com:/srv/www'
parent_config_file: _factory/nanoc.yaml
```
Without merging hashes recursively, parent config gets completely overridden.

Merge config recursively

---

lib/nanoc/base/entities/code_snippet.rb
lib/nanoc/rule_dsl/compiler_dsl.rb
spec/nanoc/base/entities/code_snippet_spec.rb
spec/nanoc/cli/commands/shell_spec.rb
test/rule_dsl/test_compiler_dsl.rb

Fixes #1169.
This introduces `use_helper` to load helpers. Helpers loaded with `use_helper` will only be available in contexts where it makes sense, so they don’t pollute the global namespace.
```ruby
module GreetingHelper
def greeting
'hello'
end
end
use_helper GreetingHelper
```

Improve helper handling in Nanoc::Int::Context

---

lib/nanoc/checking/checks/external_links.rb
test/checking/checks/test_external_links.rb

Fixes #1178.
This makes the external links checker always use GET rather than HEAD (and falling back to GET only on 405 Method Not Allowed), because using HEAD is not always reliable, sadly.

Always use GET, not HEAD, for external links

---

lib/nanoc/cli/commands/shell.rb
spec/nanoc/cli/commands/shell_spec.rb

This adds a `-p`/`--preprocess` option to `shell`, which makes the _preprocessed_ site content available.
This PR also cleans up the specs a little — I only now found out about `expect_any_instance_of`!

Add --preprocess to shell command

---

lib/nanoc/base/repos/dependency_store.rb
spec/nanoc/regressions/gh_1185_spec.rb

`Document`’s `@identifier` is mutable, and is therefore not a good candidate for use in a hash key.
Fixes #1185.

Do not use items/layouts (mutable identifier) as hash key

---

lib/nanoc/base/entities/dependency.rb
lib/nanoc/base/repos/dependency_store.rb
lib/nanoc/base/services/dependency_tracker.rb
lib/nanoc/base/views/config_view.rb
spec/nanoc/base/repos/dependency_store_spec.rb
spec/nanoc/base/views/config_view_spec.rb
test/helpers/test_blogging.rb
test/helpers/test_xml_sitemap.rb

Track dependencies onto `@config`, so that later on, the outdatedness checker can use that information to prevent recompilation if the configuration has changed but no dependency on `@config` exists.
This PR does *not* change the outdatedness checker yet. That change will come later!

Fine grained config dependencies

---

nanoc.gemspec

This will make it less likely that the built gem misses files.

Use git ls-files to specify gem files

---

lib/nanoc/deploying/deployers/fog.rb
spec/nanoc/deploying/fog_spec.rb
spec/spec_helper.rb

This doesn’t quite have much of an effect, because the files don’t stay open for long. Perhaps for very large sites deployed with fog, it’d run out of file descriptors.

Fix FogWrapper not closing file

---

lib/nanoc/base/entities/outdatedness_reasons.rb
lib/nanoc/base/entities/props.rb
lib/nanoc/base/repos/dependency_store.rb
lib/nanoc/base/services/dependency_tracker.rb
lib/nanoc/base/services/outdatedness_checker.rb
lib/nanoc/base/services/outdatedness_rules/item_collection_extended.rb
lib/nanoc/base/services/outdatedness_rules/layout_collection_extended.rb
lib/nanoc/base/views/identifiable_collection_view.rb
spec/nanoc/base/entities/props_spec.rb
spec/nanoc/base/services/outdatedness_checker_spec.rb
spec/nanoc/base/views/identifiable_collection_view_spec.rb
spec/nanoc/helpers/rendering_spec.rb

Dependencies on the item/layout collection are currently all-or-nothing. Any item that directly or indirectly accesses `@items` or `@layouts` will have a a dependency on the entire collection of items/layouts. This means that adding a new item or a new layout will cause these items to be marked as outdated, even if they won’t depend on that specific new layout.
This PR makes `@items[]` and `@items.find_all` (same for `@layout`) generate finer-grained dependencies, which only depend on a subset of the collection of items (or layouts). This way, adding a new item or layout is less likely to cause other items to be recompiled.

Make item/layout collection dependencies finer-grained

---

bin/nanoc

The `nanoc-rust` gem contains parts of Nanoc reimplemented in Rust.
This PR will attempt to load the `nanoc-rust` gem and call `NanocRust.activate!`, which replaces Ruby bits with their Rust equivalent.
⚠️  **Experimental** — although there’s no harm in releasing this, as long as you don’t enable `nanoc-rust` unless you know what you’re doing.

Add support for nanoc-rust gem

---

lib/nanoc/data_sources/filesystem.rb

`Marshal.dump` is faster than `YAML.dump` (2000–3000%).

Use Marshal.dump instead of YAML.dump for speed

---

Gemfile
lib/nanoc/filters.rb
lib/nanoc/filters/asciidoctor.rb
spec/nanoc/filters/asciidoctor_spec.rb

This integrates the `asciidoctor` filter, removing the need for a [separate `nanoc-asciidoctor` gem](https://github.com/nanoc/nanoc-asciidoctor).

Add asciidoctor filter

---

lib/nanoc/base/entities/directed_graph.rb
spec/nanoc/base/directed_graph_spec.rb
test/base/test_directed_graph.rb

This removes
* `DirectedGraph#direct_successors_of`
* `DirectedGraph#successors_of`
as neither are needed.
This change will make the directed graph class _slightly_ faster, as it no longer has to construct lists of successors.

No successors

---

lib/nanoc/cli/commands/view.rb

Many terminals (e.g. Konsole) let me open an URL by clicking it, which is quite convenient.

Print site URL when running `nanoc view`

---

lib/nanoc/cli/commands/view.rb
spec/nanoc/cli/commands/view_spec.rb

`nanoc view` listens on all network interfaces by default, which is potentially problematic, as exposes the (compiled) Nanoc site to other devices.
This is a potential security issue.

Listen on 127.0.0.1, not 0.0.0.0, by default

---

lib/nanoc/base/entities/document.rb
lib/nanoc/base/entities/identifier.rb
spec/nanoc/base/entities/document_spec.rb
spec/nanoc/base/entities/identifier_spec.rb
spec/nanoc/base/item_rep_writer_spec.rb
spec/nanoc/base/services/executor_spec.rb
spec/nanoc/base/views/document_view_spec.rb
spec/nanoc/base/views/item_rep_view_spec.rb
spec/nanoc/base/views/item_view_spec.rb
spec/nanoc/base/views/layout_view_spec.rb
spec/nanoc/base/views/mutable_document_view_spec.rb
spec/nanoc/base/views/mutable_identifiable_collection_view_spec.rb
spec/nanoc/base/views/mutable_item_collection_view_spec.rb
spec/nanoc/base/views/mutable_item_view_spec.rb
spec/nanoc/base/views/mutable_layout_collection_view_spec.rb
spec/nanoc/base/views/mutable_layout_view_spec.rb
spec/nanoc/base/views/post_compile_item_rep_view_spec.rb
spec/nanoc/data_sources/filesystem_spec.rb
spec/nanoc/helpers/blogging_spec.rb
spec/nanoc/helpers/link_to_spec.rb
test/base/test_data_source.rb
test/base/test_item_array.rb
test/cli/commands/test_compile.rb
test/filters/test_handlebars.rb
test/filters/test_mustache.rb
test/filters/test_relativize_paths.rb
test/filters/test_sass.rb
test/filters/test_xsl.rb
test/helpers/test_capturing.rb
test/helpers/test_xml_sitemap.rb

Full identifiers (e.g. `"/foo.md"` — compare to legacy identifiers such as `"/foo/"`) can never end with a slash. Nanoc does not currently enforce this, and silently allows a potentially buggy code.
This PR makes full identifiers that end with a slash explicitly invalid.
(It turns out that many of the tests cases were accidentally wrong. Yikes!)
This PR also makes `Nanoc::Document#identifier=` properly coerce the argument to an identifier, so that `@item.identifier = 'hah'` no longer turns the identifier from a `Nanoc::Identifier` into a `String`.

Disallow full identifiers from ending with a slash

---

lib/nanoc/cli/command_runner.rb
lib/nanoc/spec.rb
spec/nanoc/cli/command_runner_spec.rb
spec/nanoc/cli/commands/show_rules_spec.rb
spec/spec_helper.rb

Let `nanoc` search in ancestral directories for a site.
This change makes it possible to run `nanoc` or `bundle exec nanoc` from a directory that is a subdirectory of a Nanoc site. If the site directory is not the current directory, Nanoc will `cd` to the site directory first.
Implements nanoc/features#19.

Search for parent directory containing Nanoc site

---

lib/nanoc/cli/command_runner.rb
spec/nanoc/cli/command_runner_spec.rb

`#load_site` no longer loads the site, because of #1210. This PR fixes that.
Fixes #1211.

Let #load_site load site

---

lib/nanoc/cli/command_runner.rb
lib/nanoc/cli/commands/check.rb
lib/nanoc/cli/commands/compile.rb
lib/nanoc/cli/commands/compile_listeners/abstract.rb
lib/nanoc/cli/commands/compile_listeners/debug_printer.rb
lib/nanoc/cli/commands/compile_listeners/diff_generator.rb
lib/nanoc/cli/commands/compile_listeners/timing_recorder.rb
lib/nanoc/cli/commands/deploy.rb
lib/nanoc/cli/commands/prune.rb
lib/nanoc/cli/commands/shell.rb
lib/nanoc/cli/commands/show-data.rb
lib/nanoc/cli/commands/show-plugins.rb
lib/nanoc/cli/commands/show-rules.rb
lib/nanoc/cli/commands/view.rb
spec/nanoc/cli/command_runner_spec.rb
spec/nanoc/cli/commands/compile/diff_generator_spec.rb
spec/nanoc/cli/commands/show_data_spec.rb
spec/nanoc/cli/commands/show_rules_spec.rb
test/cli/commands/test_info.rb

The mutable state introduced by letting `#load_site` set the `@site` ivar is troubling (see #1211 for a case where I was bitten by this).
This PR lets `#load_site` return the new site, rather than set `@site`. I’ve opted to let the command runners assign the return value of `#load_site` to `@site`, which, even though not perfect, is more reasonable.

Let #load_site not set site ivar

---

lib/nanoc/cli/commands/compile_listeners/file_action_printer.rb
lib/nanoc/cli/logger.rb
spec/nanoc/cli/commands/compile/file_action_printer_spec.rb

This will let Nanoc print `cached` instead of `identical` when the compiled content of an item can be reused:
Fixes nanoc/features#12.

Print “cached” rather than “identical” when appropriate

---

lib/nanoc/base/entities/configuration.rb
lib/nanoc/base/views/config_view.rb
spec/nanoc/base/views/config_view_spec.rb

Getting closer to winning your eternal gratitude 😄

Add Configuration#dig() and ConfigView#dig()

---

lib/nanoc/data_sources/filesystem.rb
test/data_sources/test_filesystem.rb

Nanoc does not support four dashes to separate out metadata; it only supports either three or five.
Using four causes a weird error. This PR makes that weird error not happen.
Fixes #1222.

Properly handle four dashes for separating metadata

---

Gemfile
lib/nanoc/deploying/deployers/fog.rb

`require 'fog'` loads all providers. This patch limits fog and aws only.
fog has a ton of dependencies. (see below)
I think the deploy script does not need them.
We can use `'fog/core'` and `'fog/aws'` instead of just `'fog'`.
```
Using fog-aliyun 0.2.0
Using fog-brightbox 0.13.0
Using fog-dnsimple 1.0.0
Using fog-joyent 0.0.1
Using fog-openstack 0.1.21
Using fog-profitbricks 4.0.0
Using fog-sakuracloud 1.7.5
Using fog-serverlove 0.1.2
Using fog-softlayer 1.1.4
Using fog-storm_on_demand 0.1.1
Using fog-atmos 0.1.0
Using fog-cloudatcost 0.1.2
Using fog-digitalocean 0.3.0
Using fog-dynect 0.0.3
Using fog-ecloud 0.3.0
Using fog-google 0.1.0
Using fog-internet-archive 0.0.1
Using fog-powerdns 0.1.1
Using fog-rackspace 0.1.5
Using fog-radosgw 0.0.5
Using fog-riakcs 0.1.0
Using fog-terremark …
```

Limit fog's dependencies

---

lib/nanoc/base/services/compilation_context.rb
lib/nanoc/base/views.rb
lib/nanoc/base/views/view_context.rb
lib/nanoc/base/views/view_context_for_compilation.rb
lib/nanoc/base/views/view_context_for_pre_compilation.rb
lib/nanoc/base/views/view_context_for_shell.rb
lib/nanoc/cli/commands/shell.rb
lib/nanoc/rule_dsl/action_provider.rb
lib/nanoc/rule_dsl/action_sequence_calculator.rb
lib/nanoc/rule_dsl/rule.rb
lib/nanoc/rule_dsl/rule_context.rb
lib/nanoc/spec.rb
spec/nanoc/base/filter_spec.rb
spec/nanoc/base/services/executor_spec.rb
spec/nanoc/base/views/config_view_spec.rb
spec/nanoc/base/views/document_view_spec.rb
spec/nanoc/base/views/identifiable_collection_view_spec.rb
spec/nanoc/base/views/item_rep_view_spec.rb
spec/nanoc/base/views/item_view_spec.rb
spec/nanoc/base/views/mutable_document_view_spec.rb
spec/nanoc/base/views/post_compile_item_rep_view_spec.rb
spec/nanoc/rule_dsl/action_sequence_calculator_spec.rb
spec/nanoc/rule_dsl/rule_context_spec.rb
test/filters/test_slim.rb
test/filters/test_xsl.rb
test/helpers/test_blogging.rb
test/helpers/test_capturing.rb
test/helpers/test_xml_sitemap.rb

* Add contracts
* Split up
* `ViewContextForCompilation`
* `ViewContextForPreCompilation`
* `ViewContextForShell`
* Construct manually instead of going through compilation context (reduces hidden complexity)
This will meant to get rid of nonsensical view context constructions (e.g. weirdly requiring a dependency tracker and an item rep repo when preprocessing).

Refactor ViewContext

---

lib/nanoc/base/entities/site.rb
lib/nanoc/base/services/compiler.rb
lib/nanoc/base/services/compiler/stages/postprocess.rb
lib/nanoc/base/services/compiler/stages/preprocess.rb
lib/nanoc/checking/check.rb
lib/nanoc/checking/runner.rb
lib/nanoc/cli/command_runner.rb
lib/nanoc/cli/commands/check.rb
lib/nanoc/cli/commands/compile.rb
lib/nanoc/cli/commands/deploy.rb
lib/nanoc/cli/commands/prune.rb
lib/nanoc/cli/commands/shell.rb
lib/nanoc/cli/commands/show-data.rb
lib/nanoc/cli/commands/show-rules.rb
lib/nanoc/rule_dsl/action_provider.rb
lib/nanoc/spec.rb
spec/nanoc/base/services/compiler/stages/preprocess_spec.rb
spec/nanoc/cli/commands/show_rules_spec.rb
spec/nanoc/regressions/gh_776_spec.rb

This PR makes it possible to have multiple Compiler instances for the same site.
This makes the code cleaner (Site does not need to know about Compiler anymore), but also brings Nanoc closer to being able to listen to changes and compile the same site over and over again, as changes are coming in.
Note that the effects of compilers can still interfere with each other; don’t run two compilers at the same time.

Refactor: Support multiple compilers

---

lib/nanoc/cli.rb
lib/nanoc/cli/commands/compile.rb
lib/nanoc/cli/commands/compile_listeners/abstract.rb
lib/nanoc/cli/commands/compile_listeners/aggregate.rb
spec/nanoc/cli/commands/compile_spec.rb
test/cli/commands/test_compile.rb

This moves all the setup w.r.t. compile listeners into a new `Aggregate` listener class (actually `Nanoc::CLI::Commands::CompileListeners::Aggregate` — which I think is far too long of a name).
The upcoming `live` command will be able to use this!

Aggregate compile listener

---

lib/nanoc/base/services/filter.rb
lib/nanoc/base/views/item_rep_view.rb
spec/nanoc/base/views/item_rep_view_spec.rb
spec/nanoc/regressions/gh_1093_spec.rb
spec/nanoc/regressions/gh_1097_spec.rb

Reverts nanoc/nanoc#1229.
`#raw_path` is part of an internal API, but needs to become public as it has some use cases (`#compiled_content` suffices, but not for binary item snapshot).

Revert "Remove ItemRepView#raw_path"

---

lib/nanoc/base/feature.rb
lib/nanoc/cli/error_handler.rb
lib/nanoc/cli/stack_trace_writer.rb
spec/nanoc/cli/error_handler_spec.rb
spec/nanoc/cli/stack_trace_writer_spec.rb

This reverses the stack trace, to be in line with Ruby 2.5.
This change is **experimental**, because Ruby 2.5’s reversed stack trace is also experimental. These new stack traces will be used on Ruby 2.5 or when the new `sensible_stack_traces` feature is enabled.
* * *
**Regular stack trace (old):**
* * *
**Reversed stack trace (new):**

Reverse stack trace

---

lib/nanoc/filters/relativize_paths.rb
test/filters/test_relativize_paths.rb

Sometimes, you don't Nokogiri to reformat the document. Typically when you plan to style elements with `white-space: pre;`.
This PR adds a `save_with` parameter to the `relativize_paths` filter to which one can pass e.g. `Nokogiri::XML::Node::SaveOptions::DEFAULT_HTML & ~Nokogiri::XML::Node::SaveOptions::FORMAT` which clears the formatting bit from the default save options.

Add :save_with parameter to relativize_paths

---

lib/nanoc/base/entities/pattern.rb
spec/nanoc/base/entities/pattern_spec.rb

A little addition to allow the creation of patterns from symbols, which allows you to write
```
@items[i]
```
where `i` is a `Symbol` instead of having to mess with `#to_s()` at the call site

Allow creation of Pattern from Symbol

---

test/filters/colorize_syntax/test_coderay.rb
test/filters/test_bluecloth.rb
test/filters/test_erubi.rb
test/filters/test_erubis.rb
test/filters/test_haml.rb
test/filters/test_kramdown.rb
test/filters/test_markaby.rb
test/filters/test_maruku.rb
test/filters/test_mustache.rb
test/filters/test_rainpress.rb
test/filters/test_redcarpet.rb
test/filters/test_redcloth.rb
test/filters/test_rubypants.rb
test/filters/test_slim.rb
test/helpers/test_blogging.rb
test/helpers/test_xml_sitemap.rb

Don’t use `#if_have` for dependencies that _will_ work (i.e. have no non-Ruby dependencies).

Remove useless #if_have calls

---

lib/nanoc/base/feature.rb
lib/nanoc/cli/commands/view.rb

If the `LIVE_RELOAD` feature is enabled, the `nanoc view` command gets a new `--live-reload` option, which will make the browser reload when a change occurs.
Testing this is going to be a pain. :(

Add --live-reload option (experimental)

---

lib/nanoc/base/services/compiler/stages/compile_reps.rb
spec/nanoc/base/services/compiler/stages/compile_reps_spec.rb

An exception that isn’t a subclass of StandardError (e.g. SyntaxError) would prevent Nanoc from showing the item + item rep that is currently being compiled.

Handle Exception, not just StandardError

---

lib/nanoc/base/services/pruner.rb
spec/nanoc/base/services/pruner_spec.rb

The output dir itself is definitely still useful, so don’t prune it.

Do not remove output dir when pruning

---

lib/nanoc/cli/commands/view.rb
spec/nanoc/cli/commands/view_spec.rb

Create output dir when viewing

---

scripts/release

This changes the release script to read individual versions and release notes. GitHub releases will still be used for `nanoc` itself only.
New usage:
```
scripts/release [gem-name]
```

Make release script support independent versions

---

nanoc/lib/nanoc/cli/commands/show-data.rb
nanoc/spec/nanoc/cli/commands/show_data_spec.rb

Before:
```
item /robots.txt.erb depends on:
[  items ] (r___)
[   item ] (___p) /sitemap.xml.erb
```
After:
```
item /robots.txt.erb depends on:
[  items ] (r___) matching any of /sitemap.*
[   item ] (___p) /sitemap.xml.erb
```

Let show-data print item/layout collection dependencies

---

README.md

Fossa is too unreliable (keeps reporting new dependencies and miscategorises many projects as GPL rather than MIT) and too much effort to keep up-to-date.

Remove Fossa badge

---

nanoc-live/lib/nanoc/live/live_recompiler.rb
nanoc-live/spec/nanoc/live/live_recompiler_spec.rb
nanoc/lib/nanoc/cli/error_handler.rb

This makes `nanoc live` show errors, just like `nanoc compile` would.

Show errors in nanoc-live

---

nanoc/lib/nanoc/cli/error_handler.rb
nanoc/spec/nanoc/cli/error_handler_spec.rb

Fixes part of #1273.
* Known gems: e.g. `require 'nokogiri'` -> considered a trivial LoadError; Nanoc will tell you to add `nokogiri` to the Gemfile.
* Unknown gems: Usual stack trace.

Treat LoadErrors for known gems as trivial

---

nanoc/lib/nanoc/cli/error_handler.rb
nanoc/spec/nanoc/cli/error_handler_spec.rb
nanoc/test/cli/test_error_handler.rb

Follow-up to #1274.
Before:
```
Error: cannot load such file -- nokogiri
Make sure the gem is added to Gemfile and run `bundle install`.
```
After:
```
Error: cannot load such file -- nokogiri
1. Add `gem 'nokogiri'` to your Gemfile
2. Run `bundle install`
3. Re-run this command
```

Improve LoadError resolution

---

nanoc/lib/nanoc/helpers/breadcrumbs.rb
nanoc/spec/nanoc/helpers/breadcrumbs_spec.rb

Fixes #1278.
`#breadcrumbs_trail` already supported cases like these:
```
/index.md
/foo.md.erb
/foo/stuff.html
```
but now it will also support
```
/index.md
/1.2.erb
/1.2/stuff.html
```

Let #breadcrumbs_trail always find closest parent

---

nanoc/lib/nanoc/base/entities/configuration.rb

I added `.tex` to the list of `text_extensions`. Useful when creating a LaTeX layout (I stumbled upon this when creating a [latexmk filter](https://github.com/rien/nanoc-latexmk) for nanoc).

Add .tex to text_extensions

---

nanoc/lib/nanoc/base/services/compiler/stages/load_stores.rb
nanoc/lib/nanoc/cli/commands/compile_listeners/timing_recorder.rb
nanoc/spec/nanoc/cli/commands/compile/timing_recorder_spec.rb

Running `compile` with `-VV` shows e.g.
```
load_stores │   tot
─────────────────────────────────┼──────
Nanoc::Int::ChecksumStore │ 0.00s
Nanoc::Int::CompiledContentCache │ 0.01s
Nanoc::Int::DependencyStore │ 0.01s
Nanoc::Int::ActionSequenceStore │ 0.00s
Nanoc::Int::OutdatednessStore │ 0.00s
```

Time load stores

---

nanoc/lib/nanoc/base/services/compiler/phases/write.rb
nanoc/lib/nanoc/base/views/compilation_item_rep_view.rb
nanoc/lib/nanoc/cli/commands/compile_listeners/file_action_printer.rb
nanoc/spec/nanoc/base/views/compilation_item_rep_view_spec.rb
nanoc/spec/nanoc/cli/commands/compile/file_action_printer_spec.rb

This changes the `Write` phase to do writing in a background process, so that IO-intensive and CPU-intensive work can happen at the same time.
* Currently, it records/shows the duration between the start of the compilation and the moment where the file is written. This duration no longer makes sense because the writing happens asynchronously. The value that it currently prints gives a hint at how much the writing is running behind the compilation.
* * *
Here’s a before-and-after comparison of the GitLab CI docs (a fairly large site):
Before:
```
phases │ count     min     .50     .90     .95     max      tot
────────────┼───────────────────────────────────────────────────────
Write │  3209   0.00s   0.00s   0.01s   0.01s   0.18s   12.09s
```
```
Site compiled in 49.90s.
```
After:
``` …
```

Make Write phase async

---

nanoc/lib/nanoc/base/services/compiler/phases/write.rb

This lets the `Write` phase use multiple workers for speed.
It also refactors the code by introducing `Worker` and `WorkerPool` classes (both pretty tightly tied to `Write` but could be made generic later if needed).

Use multiple workers

---

nanoc/lib/nanoc/base/services/compiler/phases/write.rb

This speeds up the writing phase.
By reducing the queue size, the queue fill up more quickly, which will cause the compilation thread to be suspended more quickly, giving implicit priority to the writer threads.
I’ve measured a ~10% speedup as a result of this change.

Reduce async write queue size

---

nanoc-live/lib/nanoc/live/commands/live.rb
nanoc-live/spec/nanoc/live/commands/live_spec.rb

`nanoc live` should use `--live-reload` by default. Otherwise, it’s not really live.

Let `nanoc live` live-reload by default

---

nanoc/lib/nanoc/data_sources/filesystem/parser.rb
nanoc/test/data_sources/test_filesystem.rb

Remove leading blank line, if any

---

nanoc/lib/nanoc/checking/checks/external_links.rb
nanoc/spec/nanoc/checking/checks/external_links_spec.rb

Fixes #1297.
A HTTP 3xx header without `Location` is now an explicit error:
```
broken reference to http://example.com/x: redirection without a target location
```

Handle HTTP 302 without Location

---

nanoc/lib/nanoc/checking/checks/external_links.rb
nanoc/spec/nanoc/checking/checks/external_links_spec.rb

Fixes #1299.
Links with invalid URIs, e.g. `<a href="mailto:lol">stuff</a>`, will now create a proper issue.

Handle invalid URI components

---

nanoc/lib/nanoc/checking/loader.rb
nanoc/lib/nanoc/checking/runner.rb
nanoc/spec/nanoc/checking/runner_spec.rb

This allows defining deploy checks in the configuration file, rather than the Checks file:
```yaml
checking:
deploy_checks:
- internal_links
- spelling
```
See nanoc/features#27.

Read checks from config too

---

nanoc/lib/nanoc/cli/commands/check.rb
nanoc/spec/nanoc/cli/commands/check_spec.rb

Run deploy checks when invoking `nanoc check` without arguments or options.
This also deprecates the `--deploy` option for `nanoc check`, as it’s no longer needed.

Let check command run deploy checks by default

---

nanoc/lib/nanoc/base/entities/identifier.rb
nanoc/spec/nanoc/base/entities/identifier_spec.rb

Rubocop suggests changing `x =~ /foo/` to `x.match?(/foo/)`, but that fails when `x` is an identifier rather than a string.

Add Identifier#match?

---

nanoc/lib/nanoc/cli/commands/shell.rb
nanoc/spec/nanoc/cli/commands/shell_spec.rb

`nanoc shell` can now be invoked as `nanoc sh` (previously, it was an ambiguous command).

Make sh an alias for shell

---

nanoc/lib/nanoc/cli/commands/create-site.rb

Most of the configuration does not have to be modified. Therefore, there’s little point in listing all possible configuration options in the configuration file.
This PR removes most configuration details. If customisation is needed, it can still be added; the Nanoc web site still lists all configuration options.

Simplify default configuration

---

nanoc/lib/nanoc/cli/commands/create-site.rb

This changes the default site to only have compilation and layouting rules — no more routing rules.
Compilation rules with write calls are preferred over compilation rules and routing rules. They make the rules more easy to follow.

Remove routing rules from default site

---

nanoc/lib/nanoc/cli/logger.rb

Fixes #1312.
God knows how to test this.

Add mutex to logger

---

nanoc/lib/nanoc/helpers/blogging.rb
nanoc/test/helpers/test_blogging.rb

Allow overriding `<id>` and `<link rel="alternate">` elements.
Adds two new parameters, `:alt_link` and `:id`, to the `atom_feed` method. These allow the overriding of the `<id>` and `<link rel="alternate">` elements of the generated Atom feed.
Overriding these can result in greater compatibility and also allow for the possibility of multiple feeds per site.
I have manually tested that if you don't supply these new parameters, you get the same output as before. As mentioned in the comments on #1300, I think there's a separate issue that the default for `:alt_link` should probably be something like `"/"` instead of the base URL, but that seems like a separate issue to this enhancement.
Would address #1300.

Improve flexibility of Atom feed generator

---

nanoc/lib/nanoc/base/services/pruner.rb
nanoc/spec/nanoc/base/services/pruner_spec.rb

Ignore output_dir when checking for excludes in pruner

---

nanoc/lib/nanoc/filters/relativize_paths.rb
nanoc/spec/nanoc/regressions/gh_1319_spec.rb

Fixes #1319.
This isn’t pretty, but Nokogiri/libxml don’t offer a clean solution.

Handle gcse:search

---

nanoc-live/lib/nanoc/live/live_recompiler.rb
nanoc-live/spec/nanoc/live/commands/live_spec.rb
nanoc/spec/nanoc/cli/commands/compile_spec.rb
nanoc/spec/nanoc/cli/commands/view_spec.rb

The `live` command specs are flaky. This PR changes the implementation of the specs to be more robust.

Stabilise nanoc-live specs on Travis CI

---

nanoc/lib/nanoc/base/services/pruner.rb
nanoc/spec/nanoc/base/services/pruner_spec.rb
nanoc/spec/nanoc/regressions/gh_1313_spec.rb

Fixes #1313.
Also see #1317, which didn’t properly fix this issue.

Really ignore output_dir when checking for excludes in pruner

---

nanoc/lib/nanoc/base/errors.rb
nanoc/lib/nanoc/base/services/executor.rb
nanoc/lib/nanoc/base/services/filter.rb
nanoc/spec/nanoc/base/services/executor_spec.rb
nanoc/spec/nanoc/regressions/gh_1323_spec.rb

Fixes #1323.
After release: 
* Document `FilterReturnedNil` error on the Nanoc web site

Raise proper error when filter returns nil

---

Gemfile
common/spec/spec_helper_foot.rb
nanoc-live/spec/nanoc/live/commands/live_spec.rb
nanoc-live/spec/nanoc/live/live_recompiler_spec.rb
nanoc/lib/nanoc/spec.rb
nanoc/spec/nanoc/base/checksummer_spec.rb
nanoc/spec/nanoc/base/services/executor_spec.rb
nanoc/spec/nanoc/base/services/temp_filename_factory_spec.rb
nanoc/spec/nanoc/cli/commands/compile_spec.rb
nanoc/spec/nanoc/cli/commands/deploy_spec.rb
nanoc/spec/nanoc/cli/commands/view_spec.rb
nanoc/spec/nanoc/cli/stack_trace_writer_spec.rb
nanoc/spec/nanoc/filters/less_spec.rb
nanoc/test/checking/test_dsl.rb
nanoc/test/deploying/test_rsync.rb
nanoc/test/filters/colorize_syntax/test_common.rb
nanoc/test/filters/test_bluecloth.rb
nanoc/test/filters/test_redcarpet.rb
nanoc/test/filters/test_redcloth.rb
nanoc/test/filters/test_relativize_paths.rb
nanoc/test/helper.rb

This change is in preparation of running the build on AppVeyor (see #1325).

Improve test/spec Windows compatibility

---

nanoc/lib/nanoc/checking/check.rb
nanoc/lib/nanoc/checking/checks/external_links.rb
nanoc/lib/nanoc/checking/checks/internal_links.rb
nanoc/lib/nanoc/checking/checks/mixed_content.rb
nanoc/spec/nanoc/checking/check_spec.rb
nanoc/spec/nanoc/regressions/gh_1328_spec.rb

Fixes #1328.
I’m unsure whether or not it makes sense to configure the list of HTML extensions. There are no commonly-used extensions other than `html`, `htm`, and `xhtml`. (Wikipedia also lists `.xht`, but I have never seen that one in the wild.)

Also consider .xhtml and .html in checks

---

nanoc/lib/nanoc/base/views/basic_item_view.rb
nanoc/spec/nanoc/base/views/item_view_spec.rb
nanoc/spec/nanoc/filters/sass_spec.rb
nanoc/test/filters/test_sass.rb

As the title says. `#raw_filename` should have created a dependency.

Make *ItemView#raw_filename create dependency

---

common/spec/spec_helper_foot.rb
nanoc/lib/nanoc/base/services/filter.rb
nanoc/spec/nanoc/base/filter_spec.rb

`Filter#depend_on` does nothing when passed an item with no reps.
This change makes it depend at least on the raw content.

Make Filter#depend_on work even when no reps are present

---

nanoc-live/lib/nanoc/live/commands/live.rb

This fixes an obscure problem where `nanoc-live` would appear to successfully exit, but one thread would remain behind and keep soaking up memory and CPU time in trying to do garbage collection, in order to be able to print an apparently very large string.
This only affects Ruby 2.5, as older versions of Ruby either don’t have `report_on_exception`, or have it set to `false` by default.
Sample:
```
2591 Thread_1639960: live.rb:20
+ 2591 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fff7ccb5c5d]
+   2591 _pthread_start  (in libsystem_pthread.dylib) + 377  [0x7fff7ccb656d]
+     2591 _pthread_body  (in libsystem_pthread.dylib) + 340  [0x7fff7ccb66c1]
+       2591 thread_start_func_1  (in libruby.2.5.dylib) + 69  [0x10a81c481]
+         2591 thread_start_func_2  (in libruby.2.5.dylib) …
```

Do not report thread exceptions

---

nanoc/lib/nanoc/filters/relativize_paths.rb
nanoc/spec/nanoc/filters/relativize_paths_spec.rb

Implements nanoc/features/issues/41.
This allows specifying a list of excludes in the `relativize_paths` filter, e.g.
```ruby
filter :relativize_paths, type: :html, exclude: '/foo'
filter :relativize_paths, type: :html, exclude: ['/foo', '/bar']
filter :relativize_paths, type: :html, exclude: /ar/
```
It can be used in different ways:
* **string vs. regexp**: When given a regular expression, the path will not be relativized if the regular expression matches. When given a string, the path will not be relativized when the path starts with one or more components that matches the given string.
* **single object vs. array**: The parameter can be either a single string or regexp, or an array of them.
After merge, before release:
* Document

Add exclude: param to relativize_paths filter

---

nanoc/lib/nanoc/base.rb
nanoc/lib/nanoc/base/assertions.rb
nanoc/lib/nanoc/base/contracts_support.rb
nanoc/lib/nanoc/base/repos/compiled_content_cache.rb
nanoc/lib/nanoc/base/services/compiler/stages/compile_reps.rb
nanoc/lib/nanoc/base/services/compiler_loader.rb
nanoc/nanoc.manifest
nanoc/spec/nanoc/base/compiler_spec.rb
nanoc/spec/nanoc/base/repos/compiled_content_cache_spec.rb
nanoc/spec/nanoc/base/services/compiler/phases/cache_spec.rb
nanoc/spec/nanoc/base/services/compiler/stages/compile_reps_spec.rb
nanoc/spec/nanoc/base/views/post_compile_item_rep_view_spec.rb
nanoc/spec/nanoc/regressions/gh_1342_spec.rb

Potential fix for #1342.
The compiled content cache is loaded before preprocessing, and during loading it throws away all data about items it does not know about — therefore also the items that are not yet created. The compiled content cache is now pruned before storing, rather than at load time.
This PR also adds an assertion system to verify assumptions at runtime. It is disabled by default, but will be enabled if the `contracts` gem is loaded.

Retain cached compiled content for items created in preprocessor

---

nanoc/lib/nanoc/base/assertions.rb
nanoc/lib/nanoc/base/contracts_support.rb
nanoc/lib/nanoc/base/entities/configuration.rb
nanoc/lib/nanoc/base/entities/item_rep.rb
nanoc/lib/nanoc/base/repos/store.rb
nanoc/lib/nanoc/base/services/item_rep_router.rb
nanoc/lib/nanoc/base/services/item_rep_writer.rb
nanoc/lib/nanoc/base/services/pruner.rb
nanoc/lib/nanoc/base/views/config_view.rb
nanoc/lib/nanoc/checking/check.rb
nanoc/lib/nanoc/checking/checks/internal_links.rb
nanoc/lib/nanoc/checking/checks/w3c_validator.rb
nanoc/lib/nanoc/cli/commands/compile_listeners/diff_generator.rb
nanoc/lib/nanoc/cli/commands/compile_listeners/file_action_printer.rb
nanoc/lib/nanoc/cli/commands/deploy.rb
nanoc/lib/nanoc/cli/commands/view.rb
nanoc/spec/nanoc/base/entities/configuration_spec.rb
nanoc/spec/nanoc/base/entities/site_spec.rb
nanoc/spec/nanoc/base/item_rep_writer_spec.rb
nanoc/spec/nanoc/base/repos/store_spec.rb
nanoc/spec/nanoc/base/services/compiler/stages/cleanup_spec.rb
nanoc/spec/nanoc/base/services/executor_spec.rb
nanoc/spec/nanoc/base/services/item_rep_router_spec.rb
nanoc/spec/nanoc/base/services/outdatedness_rules_spec.rb
nanoc/spec/nanoc/base/services/pruner_spec.rb
nanoc/spec/nanoc/base/views/compilation_item_rep_view_spec.rb
nanoc/spec/nanoc/base/views/post_compile_item_rep_view_spec.rb
nanoc/test/base/test_site.rb
nanoc/test/checking/test_check.rb

This makes all raw paths absolute. The dependency on the current working directory still exists, but will be removed in the future. The dependency on the current working directory is much more explicit now, which should help in preventing issues where the current working directory might change during compilation.
This will likely help with #1338.

Make raw paths absolute

---

nanoc/lib/nanoc/base/repos/site_loader.rb
nanoc/spec/nanoc/base/repos/site_loader_spec.rb
nanoc/spec/nanoc/data_sources/filesystem_spec.rb
nanoc/test/base/test_site.rb
nanoc/test/data_sources/test_filesystem.rb
nanoc/test/helper.rb

This removes
* `SiteLoader.new_empty`
* `SiteLoader.new_with_config`
… as both are not particularly useful.

Refactor: Remove non-useful SiteLoader methods

---

nanoc/spec/nanoc/regressions/gh_1338_spec.rb

This adds an explicit test for #1338.
I am not 100% sure whether #1338 is indeed caused by the working directory changing, but if it does, at least now Nanoc keeps working fine.

Add regression test for #1338

---

nanoc/lib/nanoc/base/repos/store.rb
nanoc/spec/nanoc/base/repos/store_spec.rb

This makes the stores hold on to an absolute path, rather than a relative one. This too will help towards fixing/preventing #1338.

Make store paths absolute

---

nanoc/lib/nanoc/helpers/blogging.rb
nanoc/test/helpers/test_blogging.rb

Same as #1362 but with a test.
title_proc can be used to transform the title of each item in an Atom feed, like content_proc or excerpt_proc do for content or excerpt.
Closes nanoc/features#42
CC @th-h

title_proc for the blogging helper 

---

nanoc/lib/nanoc/helpers/breadcrumbs.rb
nanoc/spec/nanoc/helpers/breadcrumbs_spec.rb

The items in the path are up for interpretation (but not too much — see below), but the one at the very end, the item for which the breadcrumb is generated, definitely not.
As it stands right now, `#breadcrumbs_trail` makes a decision which parent to use. This might not be the right thing to do; when there is ambiguity, it might make more sense to raise an error instead. Perhaps it needs a `strict: false` (default `true`) option?
Fixes #1366.

Ensure breadcrumb trail always ends in item itself

---

nanoc/lib/nanoc/base/errors.rb
nanoc/lib/nanoc/data_sources/filesystem.rb
nanoc/lib/nanoc/data_sources/filesystem/parser.rb
nanoc/spec/nanoc/data_sources/filesystem_spec.rb

Fixes #1369.
In the case where there is on meta-file, and
* … two or more content files, all without inline metadata: raise error
* … two or more content files, all with inline metadata: raise error
* … exactly one content file without inline metadata: use attributes from the meta-file
#1369

Raise when meta-file cannot be unambiguously associated

---

nanoc/lib/nanoc/filters/sass.rb
nanoc/lib/nanoc/filters/sass/functions.rb
nanoc/lib/nanoc/filters/sass/importer.rb
nanoc/nanoc.manifest
nanoc/spec/nanoc/cli/error_handler_spec.rb
nanoc/spec/nanoc/filters/sass_spec.rb

This will Nanoc not _always_ load Sass, but only when the `:sass` filter is used.
Without this, users of Nanoc 4.10.0 would get
```
1: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in require' /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:inrequire': cannot load such file -- sass (LoadError)
```
(none)

Lazy-load Sass

---

nanoc/lib/nanoc/base/services/outdatedness_rules/rules_modified.rb
nanoc/spec/nanoc/base/services/outdatedness_rules_spec.rb
nanoc/spec/nanoc/regressions/gh_1372_spec.rb

When the params of a layout were changed, Nanoc wouldn’t recompile items that use this layout, because it only checked the rules of the item itself — not of the layout that it depends on.
Fixes #1372.

Let RulesModified check dependent objects as well

---

nanoc/lib/nanoc/base/entities/processing_actions/snapshot.rb
nanoc/lib/nanoc/rule_dsl/action_recorder.rb
nanoc/lib/nanoc/rule_dsl/action_sequence_calculator.rb
nanoc/spec/nanoc/integration/write_nil_spec.rb
nanoc/spec/nanoc/regressions/gh_1374_spec.rb
nanoc/spec/nanoc/rule_dsl/action_recorder_spec.rb

The `skip_routing_rule` was properly set up, but somehow not used.
If, after snapshot compaction, there is *any* path assigned to a snapshot action, the routing rule will be skipped. For example:
1. snapshot `a`, no paths
1. snapshot `b`, some paths
1. any filter
1. snapshot `c`, no paths
In the example above, only for snapshot `c` would the routing rule be used (if any).
Fixes #1374.

Let `write nil` always skip routing rule

---

nanoc/lib/nanoc/filters/sass/importer.rb
nanoc/spec/nanoc/filters/sass_spec.rb
nanoc/spec/nanoc/regressions/gh_1378_spec.rb

Fix backwards-incompatible change in 4.10’s Sass filter.
When no load paths are given to the Sass filter, it should still be able to resolve relative paths (e.g. `../external`) and successfully import. This isn’t currently possible, because the Sass filter assumes that the files have a corresponding Nanoc item.
This change allows the Sass filter to (again) import such files.
Fixes #1378.

Allow Sass to import files even if they don’t have an item

---

nanoc/lib/nanoc.rb
nanoc/lib/nanoc/filters/sass.rb
nanoc/spec/nanoc/filters/sass_spec.rb

This PR adds further improvements to the `:sass` and `:sass_sourcemap` filters.
- `:sass` and `:sass_sourcemap` filters now require the `:css_path` option, which produces source maps where the optional `"file"` field has a correct value
- the `:sass` filter now supports the generation of inline, base 64 encoded, source maps
https://github.com/nanoc/nanoc.ws/pull/227

Sass improvements

---

nanoc/lib/nanoc/base/errors.rb
nanoc/lib/nanoc/base/repos/snapshot_repo.rb
nanoc/lib/nanoc/base/views/compilation_item_rep_view.rb
nanoc/lib/nanoc/helpers/capturing.rb
nanoc/spec/nanoc/base/services/item_rep_selector_spec.rb

By adding `snapshot_name to the `UnmetDependency` error, an instance of this error now has all information needed to track hard dependencies.
This isn’t directly used yet, but in the future, this can be used to figure out more fine-grained dependencies on snapshot level, and coordinate between multiple dependent reps being compiled.

Add snapshot_name to UnmetDependency error

---

nanoc/lib/nanoc/base/errors.rb
nanoc/lib/nanoc/base/services/compiler/phases/resume.rb
nanoc/lib/nanoc/cli/commands/compile_listeners/debug_printer.rb
nanoc/lib/nanoc/cli/commands/compile_listeners/timing_recorder.rb
nanoc/spec/nanoc/base/compiler_spec.rb

It’s much cleaner to include the target rep and target snapshot name in the `compilation_suspended` notification, rather than the `Nanoc::Int::Errors::UnmetDependency` instance that caused it.

Include target rep and snapshot in compilation_suspended notification

---

nanoc/lib/nanoc/base/services/compiler/phases/resume.rb
nanoc/lib/nanoc/cli/commands/compile_listeners/file_action_printer.rb
nanoc/spec/nanoc/cli/commands/compile/file_action_printer_spec.rb

Rather than managing time ourselves, we can use `DDMetrics::Stopwatch` to record durations.
This also introduces `compilation_resumed`, which is needed to handle suspended compilation properly.

Use stopwatch for FileActionPrinter

---

Gemfile

Slim is now at 4.x. This PR updates the dependency’s version, so we test on the latest version of Slim.

Test Slim 4.x

---

guard-nanoc/lib/guard/nanoc.rb
nanoc/lib/nanoc/cli/commands/compile_listeners/abstract.rb
nanoc/lib/nanoc/cli/commands/compile_listeners/debug_printer.rb
nanoc/lib/nanoc/cli/commands/compile_listeners/diff_generator.rb
nanoc/lib/nanoc/cli/commands/compile_listeners/file_action_printer.rb
nanoc/lib/nanoc/cli/commands/compile_listeners/timing_recorder.rb
nanoc/spec/nanoc/cli/commands/compile/file_action_printer_spec.rb
nanoc/spec/nanoc/cli/commands/compile/timing_recorder_spec.rb
nanoc/test/cli/commands/test_compile.rb

This lets all compilation listeners use the built-in `#on`, and also lets it unsubscribe automatically, reducing the chance of errors.

Simplify notification center usage in compilation listeners

---

common/spec/spec_helper_foot.rb
nanoc/lib/nanoc/base/services/item_rep_writer.rb
nanoc/lib/nanoc/base/services/notification_center.rb
nanoc/spec/nanoc/base/services/notification_center_spec.rb
nanoc/spec/nanoc/cli/commands/compile/file_action_printer_spec.rb
nanoc/spec/nanoc/cli/commands/compile/timing_recorder_spec.rb
nanoc/spec/nanoc/helpers/filtering_spec.rb
nanoc/test/cli/commands/test_compile.rb

This will eliminate confusion about which thread executes a notification callback, and limit the amount of locking that will have to be done.

Use dedicated thread for notification center

---

nanoc/spec/nanoc/base/services/executor_spec.rb

This removes duplicated specs for `Executor`. I’m not sure how they came to be.

Refactor: Remove superfluous executor specs

---

nanoc/lib/nanoc/base/repos/snapshot_repo.rb

This makes use of `Hash.new` with a block, which eliminates the need for `||=` all the time.

Refactor: Simplify SnapshotRepo contents hash

---

nanoc/lib/nanoc/base/services.rb
nanoc/lib/nanoc/base/services/checksummer.rb
nanoc/lib/nanoc/base/views.rb
nanoc/lib/nanoc/rule_dsl.rb

The `Checksummer` always had the problem that it was aware of classes that live outside of the package it is defined in (e.g. it knew about the rule DSL, even though that is supposed to be not part of base).
This refactoring removes the knowledge of the rule DSL (and some other things) from the Checksummer, and instead lets the rule DSL inject update behavior into the checksummer.
This will make it possible for the Checksummer to live in Core.

Make Checksummer behaviors externally configurable

---

nanoc/lib/nanoc/base/services/item_rep_writer.rb

Fixes #1405. (Or rather, works around the issue…)
It is possible for hardlinking to fail when copying works fine. In that case, fall back to copying instead of hardlinking.
To do: Figure out a way to test this.
According to [facebook/create-react-app#1832 (comment)](https://github.com/facebook/create-react-app/issues/1832#issuecomment-445500936):
> Due to Android's SELinux policies, you cannot hard link as non-root

On EACCES, copy instead of hardlink

---

nanoc-core/lib/nanoc/core.rb
nanoc-core/nanoc-core.gemspec

[Zeitwerk](https://github.com/fxn/zeitwerk) is a new Ruby autoloader that seems to be sensible, and avoids the annoyance of having to figure out the order in which `require`s need to happen (because in Ruby, the order matters).
Do not merge until Zeitwerk is 1.0.

Use Zeitwerk for Core

---

nanoc-core/lib/nanoc/core/content.rb
nanoc/lib/nanoc/base/feature.rb
nanoc/lib/nanoc/base/repos.rb
nanoc/lib/nanoc/base/repos/binary_compiled_content_cache.rb
nanoc/lib/nanoc/base/repos/compiled_content_cache.rb
nanoc/lib/nanoc/base/repos/textual_compiled_content_cache.rb
nanoc/lib/nanoc/base/services/compiler_loader.rb
nanoc/lib/nanoc/base/views/post_compile_item_rep_view.rb
nanoc/nanoc.manifest
nanoc/spec/nanoc/base/compiler_spec.rb
nanoc/spec/nanoc/base/repos/binary_compiled_content_cache_spec.rb
nanoc/spec/nanoc/base/repos/compiled_content_cache_spec.rb
nanoc/spec/nanoc/base/services/compiler/phases/cache_spec.rb
nanoc/spec/nanoc/base/services/compiler/stages/compile_reps_spec.rb
nanoc/spec/nanoc/base/views/post_compile_item_rep_view_spec.rb

This is the same as #1398 with some modifications from my side. In particular:
* The textual and binary content caches now _only_ accept textual resp. binary content. I think the separation makes the design nicer.
* The binary content cache now keeps a data file which lists the items, their reps and their snapshots, rather than querying the filesystem. This is more in line with how `Store` is designed to work, but more importantly, this makes it possible to distinguish between the cases of an item having been compiled and resulting in no binary cached content, vs. the item _not_ having been compiled yet and the binary cached content not yet been available. This eliminates the need for `equals_snapshot_def`.
* Related, I was initially a bit worried about how backwards compatibility would …

Cache binary content (Denis’ remix)

---

nanoc-core/lib/nanoc/core.rb

I don't know if the original listing file by file was intentional (in which case please just disregard this PR), but it is possible to let Zeitwerk ignore directories too.

Let Zeitwerk ignore anything in core/core_ext

---

guard-nanoc/lib/guard/nanoc.rb
nanoc-core/lib/nanoc/core/notification_center.rb

The new `NotificationCenter` implementation uses a dedicated thread, but that unfortunately means that after a `fork`, the notification center stops working.
This fix forces a reset of the notification center right after forking.
Figure out how to test this.
Fixes #1409.

Force-reset NotificationCenter after fork

---

nanoc/lib/nanoc/filters/sass/importer.rb
nanoc/spec/nanoc/filters/sass_spec.rb

Infer Sass or Scss syntax from identifier with fallback to Scss if the identifer has no extension.
This also fixes the specs that always used Scss syntax from `CompiledContentStore`, despite of the created `TextualContent`s with the respective syntax.
#1397, FYI @gpakosz

Infer Sass syntax from item identifier extension, closes #1397

---

nanoc/lib/nanoc/helpers/blogging.rb

Adds media type hints to all links in Atom feeds. Adds the `atom:link[type="text/html"]` attribute to all web links and `atom:link[type="application/atom+xml"]` to the Atom self link.
RFC 4287 section 4.2.7.3.

Add atom:link[type] attributes

---

nanoc/lib/nanoc/checking/checks/external_links.rb

* The default “Ruby” User-Agent is blocked everywhere so replace it.
* Include “Mozilla/5.0” to pass through a lot of blocking filters and because it’s required due to the legacy of the web.
* Include Nanoc software name and version to identify the software making the request.
* Describe the purpose of the request to help webmasters make informed blocking decisions.
Proposed User-Agent string:
Mozilla/5.0 Nanoc/4.11.2 (link rot checker)
In my own set of 1800 links, this change reduces the number of HTTP 403 Forbidden responses from 482 to 17. (Most of these are  probably hosted by a single large provider like Cloudflare.) This could probably be reduced even further by faking a mainstream web browser’s User-Agent string. However, I’d rather live with a handful of blocked tests than start …

Set a User-Agent for HTTP requests from :elinks

---

nanoc/lib/nanoc/base/repos/compiled_content_store.rb
nanoc/spec/nanoc/base/repos/compiled_content_store_spec.rb
nanoc/spec/nanoc/regressions/gh_1412_spec.rb

If the compiled content of an item is requested, there is the possibility that Nanoc will fall back to `:last`, even though `:pre` is available. This can happen when the `:pre` compiled content is not yet available.
Fixes #1412.

Don’t fall back to :last content if :pre content is not yet available

---

nanoc/lib/nanoc/checking/checks/external_links.rb

Shuffle the list of links to test. The set will normally be sorted per item they were collected in and in many situation trend towards having the same origin repeated multiple times in a row.
Same-origin distance distribution (number of other links between links to the same origin) in my set of 2000+ links from 500 items **before** to change:
Min.   1st Qu.  Median    Mean   3rd Qu.    Max. 
1.0       2.0    10.0   135.8     103.8  2089.0 
Same-origin distance distribution **after** to change:
Min.   1st Qu.  Median    Mean   3rd Qu.    Max. 
1.0      15.0    52.5   207.0     202.0  1842.0
It’s not perfect but it’s an improvement.
- #1418

Shuffle external links list (:elinks checker)

---

nanoc/lib/nanoc/base/services/outdatedness_checker.rb
nanoc/spec/nanoc/regressions/gh_1428_spec.rb

`show-data` prints the outdatedness status of layouts. Unfortunately, the tests mock out the outdatedness checker, and the _real_ outdatedness checker does not permit calling `outdated_due_to_dependencies?` on layouts, only items and item reps.
This appears to be mostly a problem with the contracts that have been set up; the code appears to work fine without contracts in place.
Changing the `show-data` specs to not mock the outdatedness checker is rather difficult at this point, however.
Fixes #1428.

Fix crash in show-data when printing layout outdatedness

---

nanoc/lib/nanoc/checking/checks/internal_links.rb
nanoc/lib/nanoc/extra/link_collector.rb
nanoc/test/checking/checks/test_internal_links.rb
nanoc/test/checking/checks/test_mixed_content.rb
nanoc/test/extra/test_link_collector.rb
nanoc/test/helper.rb

* Support area, base, blockquote, object, and source elements.
* Support srcset attribute on img and source elements (for responsive images).
* Support poster attribute on the video element.
* Support ping attribute on a and area elements.
* Support HTML+RDFa global about and resource attributes.

Collect even more links from even more sources

---

nanoc/lib/nanoc/extra/link_collector.rb
nanoc/test/checking/checks/test_internal_links.rb
nanoc/test/extra/test_link_collector.rb

Protocol-relative URLs (e.g. `//example.com/foo`) were previously treated as internal links (e.g. `file:///example.com/foo`).
Fixes #1442.

Fix handling of protocol-relative URLs

---

nanoc-core/lib/nanoc/core/configuration-schema.json
nanoc-core/spec/nanoc/core/configuration_spec.rb
nanoc/lib/nanoc/checking/check.rb
nanoc/spec/nanoc/checking/check_spec.rb

This allows specifying files to exclude across all checks. Previously, each check had its own way to specify files to exclude.
To exclude certain files, list then under the `exclude_files` property, under the `all` property of `checks`, e.g.
```
checks:
all:
exclude_files:
- bad.html
- worse.html
```
Closes nanoc/features#51.

Allow specifying excluded files across all checks

---

nanoc/lib/nanoc/filters/sass/importer.rb

Fixes #1451. Not sure it's the cleanest way, but it sure is the shortest way 😄

Fix dependency tracking for sass imports

---

nanoc/lib/nanoc/base/services/item_rep_writer.rb
nanoc/lib/nanoc/cli/commands/compile_listeners/diff_generator.rb

This fixes a rare issue where Nanoc would print an error that a file does not exist. (Happens during output diff generation)
The call to `Nanoc::Core::NotificationCenter.sync` helped avoid some issues, but it is still possible for the diff generation to fail because the original file is no longer available. This happens because `.sync` unblocks as soon as the last notification is picked up, rather than when the last notification is finished.
(none)
(none)

Prevent race condition in diff generation

---

nanoc-core/lib/nanoc/core/dependency_store.rb
nanoc/spec/nanoc/regressions/gh_1463_spec.rb

Let dep tracker properly recognise re-added items

---

guard-nanoc/lib/nanoc/orig_cli/commands/live.rb
nanoc-live/lib/nanoc/live/commands/live.rb

The “nanoc live” command can be provided by two gems. This is confusing, so let’s add a warning.
nothing
* fixes #1450

Warn when both guard-nanoc and nanoc-live are present

---

nanoc-cli/lib/nanoc/cli/commands/prune.rb
nanoc-cli/lib/nanoc/cli/compile_listeners/file_action_printer.rb
nanoc-core/lib/nanoc/core/pruner.rb
nanoc/test/orig_cli/commands/test_prune.rb

The notification center approach works only during compilation; invoking `nanoc prune` won’t set up the right notification listeners.
CC @Fjan 
The output has also changed slightly, to reflect the actual “delete” log entry more closely.
Fixes #1474

Make pruner print things on dry run

---

nanoc/lib/nanoc/filters/erb.rb
nanoc/spec/nanoc/filters/erb_spec.rb

$SAFE_LEVEL and ERB’s safe_level parameter are deprecated and will be removed in Ruby 3. For Nanoc, keeping it around doesn’t make sense, as it’s not working properly anymore anyway, and it’s not useful for Nanoc.
This brings us a step closer to making Nanoc work on Ruby 2.7.
n/a
n/a

Remove safe_level support in ERB

---

nanoc-checking/lib/nanoc/checking/check.rb

This very simple change avoid repeating a class name. It also has the very nice side effect of allowing one to subclass Nanoc::Checking::Check to use custom helpers.
Example with a `ensure_matches_regex` helper:
```ruby
class ContentCheck < Nanoc::Checking::Check
def ensure_matches_regex(filename, regex)
add_issue(name, subject: filename) if File.read(filename).match?(regex)
end
end
ContentCheck.define(:foobar) do
@output_filenames.each do |filename|
ensure_matches_regex(filename, /html/)
end
end
```

Don't hardcode the current class in Nanoc::Checking::Check

---

nanoc/lib/nanoc/helpers/rendering.rb
nanoc/spec/nanoc/helpers/rendering_spec.rb

`@rep` is a common abbreviation of `@item_rep`.
Fixes #1484.

Make `@rep` available in rendering helper

---

common/spec/spec_helper_head_core.rb
nanoc-core/lib/nanoc/core/contracts_support.rb
nanoc-core/spec/meta_spec.rb

Nanoc will emit a warning when it notices that `contracts` is loaded.
When using Bundler:
```
------------------------------------------------------------------------------
A NOTE ABOUT PERFORMANCE:
The `contracts` gem is loaded, which enables extra run-time checks, but can
drastically reduce Nanoc’s performance. The `contracts` gem is intended for
development purposes, and is not recommended for day-to-day Nanoc usage.
To speed up compilation, remove `contracts` from the Gemfile and run
`bundle install`.
------------------------------------------------------------------------------
```
When not using Bundler:
```
------------------------------------------------------------------------------
A NOTE ABOUT PERFORMANCE:
The `contracts` gem is loaded, which enables extra run-time checks, but …
```

Emit warning when contracts is loaded

---

nanoc-cli/lib/nanoc/cli/commands/create-site.rb
nanoc/test/orig_cli/commands/test_create_site.rb

This changes the default rules so it handles `index` filenames a bit better:
* `/index.md` --> `/index.html`
* `/index.html` --> `/index.html`
* `/foo/index.md` --> `/foo/index.html`
* `/foo/index.html` --> `/foo/index.html`
Fixes #1485.

Let default Rules handle index.* files (fixes #1485)

---

nanoc/lib/nanoc/filters/relativize_paths.rb
nanoc/spec/nanoc/filters/relativize_paths_spec.rb
nanoc/test/filters/test_relativize_paths.rb

The `param` element has an attribute `value`, not `content`. Therefore, the `relativize_paths` filter needs to be updated to use `value` instead.

Relativize `value` attribute of <param>, not `content`

---

nanoc/lib/nanoc/extra.rb
nanoc/lib/nanoc/extra/srcset_parser.rb
nanoc/lib/nanoc/filters/relativize_paths.rb
nanoc/nanoc.manifest
nanoc/spec/nanoc/extra/srcset_parser_spec.rb
nanoc/spec/nanoc/filters/relativize_paths_spec.rb

This lets the `relativize_paths` filter deal with `srcset` attributes.
Fixes #1475.

Relativize srcset

---

nanoc-core/lib/nanoc/core/checksum_store.rb
nanoc-core/spec/nanoc/core/checksum_store_spec.rb

An exception was triggered on `key.first`, because not all keys are arrays (tuples). This exception would cause Store#load to delete the (presumed broken) checksums file, causing some checksusm to be nil, and therefore causing some items to be outdated.
(Describe the change in detail.)
Fixes #1471.

Fix: Handle non-array keys when loading checksums

---

nanoc-core/lib/nanoc/core/compiled_content_cache.rb
nanoc-core/lib/nanoc/core/compiler_loader.rb
nanoc-core/lib/nanoc/core/dependency_store.rb
nanoc-core/spec/nanoc/core/compilation_item_view_spec.rb

This fixes (hopefully) all remaining “warning: Using the last argument as keyword parameters is deprecated” warnings.
Fixes remaining issues related to #1479.

Fix some more “Using the last argument …” warnings

---

nanoc/lib/nanoc/filters/sass/functions.rb

The `nanoc()` Sass function takes optional keyword arguments. The counterpart Ruby function must be defined with a default hash.

Fixed 'nanoc()' Sass function definition

---

nanoc-core/lib/nanoc/core/compilation_item_rep_view.rb

At the moment, when an output file is needed, Nanoc will wait at most 1s for that file to appear (it could be in process of being filtered still).
1s is not enough, so this bumps up the timeout to 10s.
Ideally, this would not be necessary, and Nanoc would know that this file is being processed and that it is okay to wait for an extended amount of time, without timeout.
n/a

Wait longer for files to appear

---

nanoc-cli/lib/nanoc/cli/stream_cleaners/utf8.rb
nanoc-cli/spec/nanoc/cli/stream_cleaners/utf8_spec.rb

Previously, when attempting to load a custom filter in a Windows Nanoc
installation, Nanoc was crashing with indications that the UTF-8 stream cleaner
was unable to process the supplied string.
Now, we only attempt to clean UTF-8 characters out of the string if it is UTF-8
encoded.
Should fix #1502. (Including the contracts gem issue).

nanoc-cli: Only try to clean UTF-8 chars from UTF-8 strings

---

nanoc-core/lib/nanoc/core.rb
nanoc-core/lib/nanoc/core/compilation_phases/write.rb
nanoc-core/nanoc-core.gemspec

As #1501 revealed, the thread pool implementation in the `Write` phase has issues. Rather than fixing the implementation, this replaces the implementation with what `concurrent-ruby` provides, which is likely superior in all ways.
* ~~Documentation~~
* ~~Feature flags~~
This should fix #1501.

Use concurrent-ruby’s thread pool implementation

---

nanoc-core/lib/nanoc/core/temp_filename_factory.rb
nanoc-core/spec/nanoc/core/temp_filename_factory_spec.rb

It is used in multiple places (CompilationPhases::Write specifically) and therefore needs to be threadsafe.
Fixes #1501.

Make TempFilenameFactory threadsafe

---

nanoc-deploying/spec/nanoc/deploying/deployers/git_spec.rb

It’s only supported in Git versions newer than what CircleCI provides.
n/a

Don’t use --initial-branch option of `git init`

---

nanoc-core/lib/nanoc/core.rb
nanoc-core/lib/nanoc/core/item_rep_writer.rb
nanoc-core/nanoc-core.gemspec
nanoc-core/spec/nanoc/core/item_rep_writer_spec.rb
nanoc-live/spec/nanoc/live/live_recompiler_spec.rb

This is based on #1509 by @da2x.
I’ve tested this out locally and it seems to work wonderfully — it does not have the disadvantage of a hardlink (a file being shared between content/ and output/), but still has all its advantages.
The difference with #1509 is that it uses clonefile the same way as hardlinks: it doesn’t use `content.filename` but just `tmp_path` (which is a location inside `tmp/`, or `content/` if no filters were applied) and `raw_path` (which is a location in `output/`). It also doesn’t use `FileUtils.identical?`, which is not needed and would make compilation slower.
A 20 GB file in content/ is instantly copied* to output/.
* ~~Tests~~ — This is particularly hard to test, as a clone is almost identical to a copy.
* ~~Feature flags~~ — This behavior is not enabled unless …

Prefer copy-on-write cloning to hardlinking

---

.github/workflows/ruby.yml

This fixes the cache key for GitHub Actions (bundle install step).

Fix CI cache key

---

.github/workflows/ruby.yml

This makes `bundle install` use `--path`, so that it installs in a place where the `cache` GitHub action can be used.

Install bundle into a cacheable location

---

.github/workflows/ruby.yml

The tests weren’t genuinely being run — just a quick early exit for each of the test jobs.

Run actual tests on GitHub CI

---

.github/workflows/ruby.yml
Gemfile
nanoc-checking/nanoc-checking.gemspec
nanoc-cli/nanoc-cli.gemspec
nanoc-core/lib/nanoc/core/contracts_support.rb
nanoc-core/nanoc-core.gemspec
nanoc-core/spec/nanoc/core/content_spec.rb
nanoc-deploying/nanoc-deploying.gemspec
nanoc-deploying/spec/nanoc/deploying/deployers/rsync_spec.rb
nanoc-external/nanoc-external.gemspec
nanoc-live/nanoc-live.gemspec
nanoc-spec/nanoc-spec.gemspec
nanoc/nanoc.gemspec
nanoc/spec/nanoc/rule_dsl/action_recorder_spec.rb
nanoc/test/filters/test_markaby.rb

This makes the necessary changes to support Ruby 3.
* [contracts.ruby](https://egonschiele.github.io/contracts.ruby/) is disabled on Ruby 3 because it appears to be incompatible. As contracts.ruby is not maintained, it is probably worth looking into Ruby 3’s static typing support.
* Markaby tests are disabled on Ruby 3, as it too appears to be incompatible. Markaby appears unmaintained (last minor release in 2013, and last patch release in 2017).
n/a

Support Ruby 3

---

.github/workflows/ruby.yml

Using `bundle install --path` is deprecated, use recommended/up to date way to configure install path.
```
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path 'vendor/bundle'`, and stop using this flag
```
I also took the opportunity to install gems in parallel.
Follow up of nanoc/nanoc/pull/1534

Fix GitHub Actions bundle install path

---

nanoc-live/lib/nanoc/live/live_recompiler.rb

This removes the customised `latency` and `wait_for_delay` options for Listen, so that they use Listen’s default ones. This hopefully brings more stability to nanoc-live.
n/a
Possibly #1537

Use default Listen latency/wait_for_delay opts

---

nanoc-core/lib/nanoc/core/compilation_item_rep_view.rb

I've seen this randomly for as long as I've used Nanoc, but I've never bothered to read the code to learn that it was caused by my use of `raw_path`. I thought it was just some random item that sometimes randomly failed. (E.g. sitemaps cause this through `File.mtime(item.raw_path)`.)
I can calculate the item[:mtime] in the preprocessor and save myself random errors, but first I needed to learn that this was caused by `raw_path`. Hoping the new error can help others better understand what happens and save them time.

Spelling and more descriptive error

---

nanoc/lib/nanoc/filters/erb.rb

Positional arguments were deprecated in Ruby 3. Change is backwards-compatible to Ruby 2.3.
Resolves #1547.

Switch ERB to use keyword arguments

---

nanoc-core/lib/nanoc/core/code_snippet.rb
nanoc-core/spec/nanoc/core/code_snippet_spec.rb

Don’t redefine `use_helper` if it is already defined.
Unfortunately, this is tough to test automatically, as capturing stderr/stdio doesn’t seem possible with these types of warnings (presumably because Ruby prints to `STDOUT`/`STDERR` rather than `$stdout`/`$stderr`). I tested this manually though.
Fixes #1548.

Fix: Don’t redefine use_helper function (fixes #1548)

---

nanoc-checking/lib/nanoc/checking/check.rb
nanoc-cli/lib/nanoc/cli/compile_listeners/timing_recorder.rb
nanoc-core/lib/nanoc/core.rb
nanoc-core/lib/nanoc/core/action_sequence.rb
nanoc-core/lib/nanoc/core/identifiable_collection.rb
nanoc-core/lib/nanoc/core/item_collection.rb
nanoc-core/lib/nanoc/core/layout_collection.rb
nanoc-core/lib/nanoc/core/outdatedness_checker.rb
nanoc-core/lib/nanoc/core/outdatedness_rules/code_snippets_modified.rb
nanoc-core/nanoc-core.gemspec
nanoc/lib/nanoc/filters/relativize_paths.rb
nanoc/lib/nanoc/rule_dsl/action_sequence_calculator.rb

Replaces nanoc’s usage of [ddmemoize](https://github.com/ddfreyne/ddmemoize) with [memo_wise](https://github.com/panorama-ed/memo_wise).
This fixes #1559, likely because it no longer relies on soft references. This might mean increased memory usage, but this should be fine as Nanoc doesn’t memoize *that* much data.
It also means we lose memoization metrics, as memo_wise doesn’t provide those. This is probably fine.
Future work:
* `memo_wise` doesn’t seem to properly support memoization in superclasses. This is a problem for `IdentifiableCollection`, but for now I’ve done the memoization on the subclass instead. Possibly related: https://github.com/panorama-ed/memo_wise/issues/262 and https://github.com/panorama-ed/memo_wise/pull/265 (though that PR did not resolve the issue for me).
Fun …

Replace ddmemoize with memo_wise

---

nanoc/lib/nanoc/data_sources/filesystem/parser.rb

Nanoc 4.12.4 on Ruby 3.1.0 fails to parse metadata for pages if it contains a timestamp.
```
Nanoc::DataSources::Filesystem::Errors::UnparseableMetadata: Could not parse metadata for /path/to/article.yaml: Tried to load unspecified class: Time
```
This change adds the `Time` class to the allowed objects.
#1560

Add Time to the list of permitted classes for YAML

---

nanoc-core/nanoc-core.gemspec
nanoc/lib/nanoc/data_sources/filesystem/parser.rb

This replaces `YAML.load(…, permitted_classes: …)` with `YAML.safe_load(…, permitted_classes: …)`, which works on Ruby 2.6+ without requiring a newer version of Psych.
The runtime dependency on `psych` 4.0+ is removed, as it’s no longer needed.
Context:
* [this commit’s comments](https://github.com/nanoc/nanoc/commit/b3755eca87b4372c8755dfc170f38653fb15a710#commitcomment-64201618)
* [mailing list discussion](https://groups.google.com/g/nanoc/c/eLQavTSFhVU)

Prefer YAML.safe_load over YAML.load

---

nanoc-deploying/spec/nanoc/deploying/deployers/fog_spec.rb

This issue happens on Ruby 3.x due to the way keyword arguments are handled differently from Ruby 2.x. This only affects tests, and is not a problem with nanoc-deploying itself.
```
1) Nanoc::Deploying::Deployers::Fog dry run with CDN ID does not actually invalidate
[11](https://github.com/nanoc/nanoc/runs/5166826011?check_suite_focus=true#step:11:11)
Failure/Error: cdn = ::Fog::CDN.new(config_for_fog)
[12](https://github.com/nanoc/nanoc/runs/5166826011?check_suite_focus=true#step:11:12)
[13](https://github.com/nanoc/nanoc/runs/5166826011?check_suite_focus=true#step:11:13)
Fog::CDN received :new with unexpected arguments
[14](https://github.com/nanoc/nanoc/runs/5166826011?check_suite_focus=true#step:11:14)
expected: ({:local_root=>"remote", :provider=>"local"}) …
```

Fix nanoc-deploying build failure related to Fog

---

nanoc-cli/spec/nanoc/cli/commands/view_spec.rb

In certain situations, when a TUN device is present (e.g., when a VPN
is connected), `Socket.getifaddrs.map(&:addr)` can contain one or more
`nil` elements.  This can lead to errors like the following:
``` ruby
(irb):6:in `select': undefined method `ipv4?' for nil:NilClass (NoMethodError)
from (irb):6:in `<main>'
from /usr/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
from /usr/bin/irb3.0:23:in `load'
from /usr/bin/irb3.0:23:in `<main>'
```
This commit prevents such errors by using `compact` to remove any
`nil` elements from the map before passing it to `select`.

Use `compact` on `Socket.getifaddrs.map`

---

nanoc/lib/nanoc/data_sources/filesystem.rb

Psych-4.0 changes to safe_load by default. Compilation breaks with below error for anyone with binary files accompanied by a Yaml file with a date. 
```
Psych::DisallowedClass: Tried to load unspecified class: Date
```
The DateClass isn’t allowed in safe_load mode. Nanoc expects it to be for e.g. created_at. Duplicating code from parser.b to allow same classes in all Yaml source files and front matter.

Allow same Yaml classes for binary and frontmatter

---

nanoc-deploying/lib/nanoc/deploying/deployers/git.rb
nanoc-deploying/spec/nanoc/deploying/deployers/git_spec.rb

If the `output/` directory is clean (nothing to commit), then the Git deployer (as part of `nanoc deploy`) should still attempt to `git push`.
Additionally, this change makes `--verbose` print out the executed `git` commands.
n/a

“git push” even if repo does not need a commit

---

.github/workflows/ruby.yml

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
> Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
https://www.legitsecurity.com/blog/github-privilege-escalation-vulnerability
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

Set permissions for GitHub actions

---

.rubocop_todo.yml
nanoc-core/lib/nanoc/core/binary_compiled_content_cache.rb
nanoc/spec/nanoc/regressions/gh_1572_spec.rb

A non-writable binary file in `content/` will lead to file with the same permissions (non-writable) in the binary compiled content cache, and the cached file will not be overwriteable, which makes Nanoc crash.
This fix removes the file from the binary compiled content cache before attempting to write it. This retains the permissions (which is intentional).
Fixes #1572: nanoc 4.12 binary cache copies read-only source permissions then attempts to open for writing.

Fix: Support non-writable binary content cache files

---

nanoc-core/lib/nanoc/core/config_loader.rb
nanoc-core/nanoc-core.gemspec
nanoc/lib/nanoc/data_sources/filesystem.rb
nanoc/lib/nanoc/data_sources/filesystem/parser.rb

This adds a dependency on Psych 4.x, which fixes #1577. The `YAML.safe_load` and `YAML.safe_load_file` functions are now used consistently throughout. Having a single, consistent Psych version eliminates issues like #1577 which arise from different behavior in incompatible major versions. 
n/a
Fixes #1577.

Use Psych 4

---

.rubocop.yml
Gemfile
nanoc-cli/lib/nanoc/cli/cleaning_stream.rb

This is a minor edit that should get the green check back for rubocop.
The first commit fixes the currently-emitted error that [showed up](https://github.com/nanoc/nanoc/runs/7055937582?check_suite_focus=true) running rubocop 1.30.1 on the last test run in June. That error was due to a minor change added in that exact version, here: https://github.com/rubocop/rubocop/commit/a83732be3767cd50f821aba4b3d01542ff6f6f86
The second and third commits fix what would have been a newly-emitted error, unrelated to the first, showing up just a couple days later when rubocop released its version 1.31. One of the cops nanoc is using got removed in a breaking change: https://github.com/rubocop/rubocop/commit/c6a4e91f1badf3c41921949d7afd982c8c959b05
The second commit is the minimum possible fix that just …

Fix rubocop test

---

guard-nanoc/lib/guard/nanoc/live_command.rb
nanoc-cli/lib/nanoc/cli/commands/view.rb
nanoc-live/lib/nanoc/live/commands/live.rb

- Replaces `mongrel` with `puma` in documentation.
- Fixes incorrect mention that `view` and `live` listen on all IP addresses by default.
n/a
Fixes #1584.

Fix documentation in view and live commands

---

nanoc-checking/lib/nanoc/checking/checks/external_links.rb
nanoc-checking/lib/nanoc/checking/checks/internal_links.rb
nanoc-checking/spec/nanoc/checking/checks/external_links_spec.rb

Escape links as `<url>`, so terminals don’t interpret unwanted characters as being part of the link. E.g. the link from the message `broken reference to https://nanoc.app/: error` would be interpreted as `https://nanoc.app/:` instead of `https://nanoc.app/` as expected. This small change fixes that issue.
All done and I’ve updated the affected tests.

Escape URLs so terminals can detect them properly

---

nanoc/lib/nanoc/helpers/html_escape.rb
nanoc/spec/nanoc/helpers/html_escape_spec.rb

This changes the HTML-escape code to also escape single-quotes (`'`).
This is necessary for security reasons, and it is what Rails does as well (see [`ERB::Util`](https://api.rubyonrails.org/classes/ERB/Util.html)).
Fixes #1590.

HTML-escape single quotes

---

nanoc-core/lib/nanoc/core/store.rb

This changes `Store#load` to use a read-only transaction, which should speed up loading site data.
n/a
n/a

Use read-only tx in Store#load

---

nanoc-cli/lib/nanoc/cli/compile_listeners/timing_recorder.rb
nanoc-core/lib/nanoc/core/instrumentor.rb
nanoc-core/spec/nanoc/core/compilation_stage_spec.rb
nanoc-core/spec/nanoc/core/instrumentor_spec.rb

This prevents the `Instrumentor` class from doing anything unless instrumentation is explicitly requested.
This leads to a measureable speedup.
n/a

Enable Instrumentor only when needed

---

.rubocop.yml
nanoc-core/lib/nanoc/core/outdatedness_rules/not_written.rb
nanoc-core/spec/nanoc/core/outdatedness_rules_spec.rb

This changes the `NotWritten` to pre-load the list of files in the output directory, so that the filesystem only has to be accessed once, rather than for every file.
This leads to a nice speedup. For one particular site:
```
x │ count     min     .50     .90     .95     max     tot
────────────────────────────────────────────┼──────────────────────────────────────────────────────
Nanoc::Core::OutdatednessRules::NotWritten │  3704   0.00s   0.00s   0.01s   0.01s   0.05s   4.77s
```
```
x │ count     min     .50     .90     .95     max     tot
────────────────────────────────────────────┼──────────────────────────────────────────────────────
Nanoc::Core::OutdatednessRules::NotWritten │  3704   0.00s   0.00s   0.00s   0.00s   0.05s   0.07s
```
Before: 4.77s. After: 0.07s. That’s a 60x–70x …

Performance: Speed up NotWritten outdatedness rule

---

nanoc-core/lib/nanoc/core/checksummer.rb
nanoc-core/spec/nanoc/core/checksummer_spec.rb

The `Checksummer` now knows how to handle a `Set`, without using `Marshal.dump` (which causes the checksums to fluctuate, and items be marked as outdated).
Additionally, this renames `ArrayUpdateBehavior` to `CollectionUpdateBehavior`. This way, it reflects that it can be used for other collections as well.
* ~~[ ] Documentation~~
* ~~[ ] Feature flags~~
n/a

Implement accurate checksumming for Set

---

Gemfile
nanoc/lib/nanoc/filters/haml.rb
nanoc/spec/nanoc/helpers/filtering_spec.rb
nanoc/test/filters/test_haml.rb

Nanoc currently supports Haml 5.x, but not the newly-released Haml 6. This adds compatibility with Haml 6.
Some drawbacks:
* This drops support for running the `filter` helper in Haml. It will still work in Haml 5.x, but not in Haml 6.x. As far as I can tell, it’s simply not supported, but it’s probably fine as Haml has built-in helpers that might just do the trick.
* Haml 5.x is supported, but there aren’t any test run against it. I could use [Appraisals](https://github.com/thoughtbot/appraisal) to test both Haml 5.x and 6.x, but I’m not sure it’s worth the effort.
n/a

Make compatible with Haml 6.x

---

nanoc-cli/lib/nanoc/cli/commands/show-data.rb
nanoc-core/lib/nanoc/core/dependency_props.rb
nanoc-core/lib/nanoc/core/dependency_store.rb
nanoc-core/lib/nanoc/core/dependency_tracker.rb
nanoc-core/lib/nanoc/core/feature.rb
nanoc-core/lib/nanoc/core/identifiable_collection_view.rb
nanoc-core/lib/nanoc/core/outdatedness_checker.rb
nanoc-core/lib/nanoc/core/outdatedness_status.rb
nanoc-core/spec/nanoc/core/outdatedness_checker_spec.rb
nanoc-core/spec/nanoc/core/support/identifiable_collection_view_examples.rb

This adds support for queries like `@items.where(kind: 'article')`, which would return a collection of all items where the `kind` attribute is `"article"`.
In behavior, this is nearly identical to `@items.select { _1[:kind] == 'article' }`, but is more friendly to the dependency tracker and outdatedness checker. For example:
* This creates only a single dependency, onto the item collection, rather than individual dependencies for each item. This cuts down on the number of dependencies. A lower number of dependencies means the dependency is smaller, and can be loaded/stored more quickly. For large sites, with many thousands of items, this can make a significant difference.
* This prevents items from being marked outdated if their `kind` attribute changes from something that isn’t …

Support attribute-level dependencies on item collections

---

nanoc-core/lib/nanoc/core/checksum_collection.rb
nanoc-core/lib/nanoc/core/checksum_store.rb
nanoc-core/lib/nanoc/core/document.rb
nanoc-core/lib/nanoc/core/outdatedness_checker.rb

After some detailed profiling of `DetermineOutdatedness#run`, I found some hotspots that I tweaked.
For one particular site, this decreased the duration of `DetermineOutdatedness#run` from just over 7s to just over 4s. The call to `OutdatednessChecker#attributes_prop_causes_outdatedness?`  went from taking 45% to taking 6.4% of `DetermineOutdatedness#run` execution time.
n/a

Improve performance of outdatedness checker

---

nanoc-cli/spec/nanoc/cli/commands/show_data_spec.rb
nanoc-core/lib/nanoc/core/dependency_props.rb
nanoc-core/lib/nanoc/core/dependency_store.rb
nanoc-core/lib/nanoc/core/mutable_document_view_mixin.rb
nanoc-core/lib/nanoc/core/outdatedness_checker.rb
nanoc-core/lib/nanoc/core/outdatedness_rule.rb
nanoc-core/lib/nanoc/core/outdatedness_status.rb
nanoc-core/spec/nanoc/core/dependency_store_spec.rb

This continues the progress made in improving performance.
The main learning: `Set#any?` is *slow* -- much better to use `Set#empty?` and negate.
I also realised that `Set`s can be avoided if the possible elements are limited and known ahead of time. `Set` is rather slow, and more verbose code can be a lot faster.
* It’d be nice to have a test case for `#props_for` returning nil, but by now it’s less and less likely that there’s such old versions of Nanoc around that require this very tiny bit of backwards compatibility.
Two other performance-focused PRs:
* #1602 
* #1603

Improve performance (part III)

---

nanoc-core/lib/nanoc/core/outdatedness_checker.rb
nanoc-core/spec/nanoc/core/outdatedness_checker_spec.rb

This creates an entirely new set of specs for `Nanoc::Core::OutdatednessChecker`, as the old one (to be deleted) started becoming harder and harder to maintain. (The Git diff is meaningless.)
The new `Nanoc::Core::OutdatednessChecker` sets up a common example that all the specs use, consisting of the following items:
* /home.md
* /articles.html.erb
* /articles/2019-a.md
* /articles/2022-b.md
* /articles/2022-c.md
In addition, it fixes one bug 🐛 in the implementation of `#where`: newly added items that match a `#where` clause were not properly causing outdatedness.
The larger purpose is to facilitate a thorough refactoring of the `OutdatednessChecker` with the intent of making changes to improve performance even further.
n/a

Create new outdatedness checker specs

---

.github/workflows/ruby.yml
Gemfile
Rakefile
nanoc-tilt/.rspec
nanoc-tilt/LICENSE
nanoc-tilt/NEWS.md
nanoc-tilt/README.md
nanoc-tilt/Rakefile
nanoc-tilt/lib/nanoc-tilt.rb
nanoc-tilt/lib/nanoc/tilt.rb
nanoc-tilt/lib/nanoc/tilt/filter.rb
nanoc-tilt/lib/nanoc/tilt/version.rb
nanoc-tilt/nanoc-tilt.gemspec
nanoc-tilt/nanoc-tilt.manifest
nanoc-tilt/spec/gem_spec.rb
nanoc-tilt/spec/manifest_spec.rb
nanoc-tilt/spec/nanoc/tilt/filter_spec.rb
nanoc-tilt/spec/spec_helper.rb
scripts/release

Adds a `:tilt` filter. Similar to the existing [nanoc-tilt gem](https://rubygems.org/gems/nanoc-tilt), but up to date for Nanoc 4.
Soon:
* Release
n/a

Add nanoc-tilt filter

---

nanoc-core/lib/nanoc/core/item_rep_selector.rb
nanoc-core/spec/meta_spec.rb
nanoc-core/spec/nanoc/core/item_rep_selector/item_rep_priority_queue_spec.rb
nanoc-core/spec/nanoc/core/item_rep_selector/micro_graph_spec.rb
nanoc-core/spec/nanoc/core/item_rep_selector_spec.rb

This modifies the item rep selection algorithm to favor item rep that are *not* known to have dependencies over item rep that have known dependencies. (Note: It’s important to distinguish “not known to have dependencies” from “known to not have dependencies” here.)
This helps for pages that have dependencies on large numbers of items, such as blog archive pages. Below is an example of a posts archive for three posts, `/posts/a.md`, `/posts/b.md` and `/posts/c.md`.
Before:
1. Nanoc compiles post archive, which has a compiled content dependency on all posts. Post archive fails to compile because of dependency on `/posts/a.md`.
2. Nanoc compiles `/posts/a.md`, successfully.
3. Nanoc compiles post archive again. Post archive again fails to compile, but now because of a dependency on …

Optimize item rep selection

---

nanoc-core/lib/nanoc/core/item_rep_selector.rb

This changes `ItemRepIgnorableIterator`:
* It now uses `Array#shift`, which is faster than maintaining our own iteration index.
* It now uses `while` rather than `loop`, which is also significantly faster.
Probably a micro-optimisation.
I suppose that this shows that second-guessing Ruby is not a great idea!
n/a
n/a

Optimise ItemRepIgnorableIterator

---

nanoc-core/lib/nanoc/core/outdatedness_checker.rb

This call will break memoization of #find_all, as a Pattern is not memoizable well (it should really implement #eql? and #== etc, but does not at the moment).
This should speed things up slightly. Or a lot. To be seen.
* Open question: Does it make sense to make `Pattern` memoizable, by implementing `#==` etc? This would’ve avoided this issue…
Fixes, or at least improves #1605.

Remove redundant Pattern.from

---

nanoc-cli/spec/spec_helper.rb
nanoc-core/lib/nanoc/core/basic_item_view.rb
nanoc-core/lib/nanoc/core/executor.rb
nanoc-core/lib/nanoc/core/identifiable_collection.rb
nanoc-core/lib/nanoc/core/identifiable_collection_view.rb
nanoc-core/lib/nanoc/core/item_collection.rb
nanoc-core/lib/nanoc/core/layout_collection.rb
nanoc-core/lib/nanoc/core/outdatedness_rules/rules_modified.rb
nanoc-core/spec/nanoc/core/identifiable_collection_spec.rb
nanoc-core/spec/nanoc/core/item_collection_with_reps_view_spec.rb
nanoc-core/spec/nanoc/core/item_collection_without_reps_view_spec.rb
nanoc-core/spec/nanoc/core/layout_collection_view_spec.rb
nanoc-core/spec/nanoc/core/mutable_item_collection_view_spec.rb
nanoc-core/spec/nanoc/core/mutable_layout_collection_view_spec.rb
nanoc-core/spec/nanoc/core/site_loader_spec.rb
nanoc-core/spec/nanoc/core/support/identifiable_collection_view_examples.rb
nanoc/spec/nanoc/helpers/rendering_spec.rb
nanoc/spec/nanoc/orig_cli/commands/show_rules_spec.rb
nanoc/test/rule_dsl/test_action_provider.rb

This changes `@items[]` so that if there is a single exact match, no dependency on the item collection is created.
(Same for layouts.)
See source comments for details.
This PR can be a bit tough to review, but you can look through the commits individually. The first commit is the actual change of letting `#[]` not create dependencies on the item/laout collection, while the second commit removes `IdentifiableCollection#[]`, which is no longer needed and probably should not be used anyway.
* Add tests for `IdentifiableCollection`’s `#object_matching_glob` and `#object_with_identifier` methods (since `#[]` is gone).
Fixes, hopefully, #1605.

Let #[] create single-item dependencies if possible

---

nanoc-cli/lib/nanoc/cli/compile_listeners/timing_recorder.rb
nanoc-cli/spec/nanoc/cli/compile_listeners/timing_recorder_spec.rb
nanoc-core/lib/nanoc/core/compilation_stages/load_stores.rb
nanoc-core/lib/nanoc/core/store.rb

This adds instrumentation for `Store#store`.
As a refactoring, it also moves the existing instrumentation into `Store`. I think it makes more sense for `Store` instrumentation to live within `Store` itself!
Maybe the time has come to rename `Store#store`, e.g. to `Store#save`. The naming is *confusing*.
n/a

Improve store instrumentation

---

nanoc-core/lib/nanoc/core/store.rb
nanoc-core/spec/nanoc/core/store_spec.rb

This removes use of `PStore` from the `Store` classes, and instead uses `Marshal.dump` and `Marshal.load` directly. This creates a tiny but measurable speedup, because `PStore#transaction` loads the data, even if the only purpose for the transaction is to replace all the data.
**NOTE:** This change will invalidate all data in everyone’s `tmp/nanoc` directory. I think that’s fine.
An example zero-change compilation, before:
```
load:
Nanoc::Core::DependencyStore │ 5.85s
store:
Nanoc::Core::DependencyStore │ 8.65s
```
An example zero-change compilation, after:
```
load:
Nanoc::Core::DependencyStore │ 5.48s
store:
Nanoc::Core::DependencyStore │ 3.49s
```
Nothing
n/a

Use Marshal.{load,dump} instead of PStore

---

nanoc-core/lib/nanoc/core/store.rb

* Make `#load_uninstrumented` and `#store_uninstrumented` private. These aren’t supposed to be part of the class’ public API.
* Let `#load_uninstrumented` only retry errors once. If an error occurs the second time, then something else is wrong.
* Ideally, tests for `#load_uninstrumented` that it only retries errors once. However, this is tough to test because these errors are hard to test -- they’re really there more for preventing future programming errors.
n/a

Clean up Store implementation

---

nanoc-core/lib/nanoc/core/errors.rb
nanoc-core/lib/nanoc/core/item_rep_selector.rb
nanoc-core/spec/nanoc/core/errors/dependency_cycle_spec.rb
nanoc-core/spec/nanoc/core/item_rep_selector/item_rep_priority_queue_spec.rb
nanoc-core/spec/nanoc/core/item_rep_selector_spec.rb

This replaces the stack-based dependency cycle detector with one that actually works. See the newly added specs for `ItemRepPriorityQueue` which demonstrate the #1619 regression.
Fixes #1619.

Fix cycle detection in item rep selector

---

nanoc/lib/nanoc/data_sources/filesystem/tools.rb
nanoc/test/data_sources/test_filesystem_tools.rb

The Troubleshooting page gives instructions for what to do when [hidden files are ignored](https://nanoc.app/doc/troubleshooting/#hidden-files-are-ignored). The example given is as follows:
```yaml
data_sources:
-
type: filesystem
extra_files:
- "/.well-known/**/*"
- "/.nojekyll"
```
However, this example is not currently working as intended: the extra files end up with double slashes at the beginning (e.g. `//.nojekyll`).
This PR fixes that.
The troubleshooting documentation could also be updated, though if both variants (starting with slash and not starting with slash) are supported, the documentation is fine anyway.
n/a

Prevent double slash when using extra_files

---

nanoc/lib/nanoc/data_sources/filesystem.rb
nanoc/spec/nanoc/data_sources/filesystem_spec.rb

When a directory given in the `filesystem` data source does not exist, `nanoc compile` will handle it fine, but `nanoc listen` will crash with a `…/gems/listen-3.7.1/lib/listen/adapter/config.rb:16:in `realpath': No such file or directory @ rb_check_realpath_internal` error.
This fix makes Nanoc ignore directories that do not exist.
One drawback is that if `nanoc live` is started *and then* the directory is created, `nanoc live` will still be ignoring the directory. That seems like an edge case though, but still something that might be improved later.
Fixes #1625.

Gracefully handle non-existant dir in `nanoc listen`

---

nanoc-dart-sass/lib/nanoc/dart_sass/filter.rb

This PR rewrites the dart sass custom importer in idiomatic ruby code.

Write dart sass importer in idiomatic ruby

---

nanoc-dart-sass/lib/nanoc/dart_sass/filter.rb

This PR makes sure that importing a child dependency with `sass` extension a.k.a `:indented` syntax would work.

Apply sass syntax detection logic to dependencies

---

nanoc-cli/lib/nanoc/cli/cleaning_stream.rb
nanoc-cli/spec/nanoc/cli/cleaning_stream_spec.rb

`$stdout`/`$stderr`, both instances of `CleaningStream`, should also respond to `#closed?` and forward it to the underlying stream.
* [~] Documentation
* [~] Feature flags
Part of a fix for #1631.

Let CleaningStream forward #closed?

---

nanoc-core/lib/nanoc/core/item_rep_selector.rb
nanoc-core/spec/nanoc/core/item_rep_selector/item_rep_priority_queue_spec.rb

It is possible, though unlikely, for the `ItemRepPriorityQueue` to yield an item more than once.
This happens when an item rep has a dependency on an item that was previously yielded but could not be compiled due to a dependency it had itself. For example, given items A to E:
* item A depends on item D
* item B depends on item A
The order of yielding should be:
1. item A (regular prio; outcome=failure due to dependency on item D)
2. item D (prioritised; ok)
3. item B (regular prio; outcome=failure due to dependency on item A)
4. item A (prioritised; outcome=ok)
5. item C (regular prio; ok)
6. item E (regular prio; ok)
7. item B (least prio)
Previously, item A would be yielded twice: once in step 4 (when it was prioritised) and once near the end (in step 7 or 8). This is because item A …

Don’t let ItemRepPriorityQueue yield items more than once

---

nanoc-core/lib/nanoc/core/item_rep_selector.rb
nanoc-core/spec/nanoc/core/item_rep_selector/item_rep_priority_queue_spec.rb

* `ItemRepIgnorableIterator` is not a useful abstraction (it barely does anything), so away it goes.
* `@prio_a` only ever contains one or two elements, so having it as an array is not worth it.
* Some `expect(micro_graph.next).to be_nil` were missing.
n/a

Clean up priority queue implementation

---

nanoc-core/lib/nanoc/core/store.rb
nanoc-core/spec/nanoc/core/store_spec.rb

`IO.write` can raise the error `Invalid argument @ io_write` when there is too much data to write.
This PR changes `#write_obj_to_file` to write data as a stream, using `IO.copy_stream`. Additionally, the file is written atomically (written to temp file and then moved into place).
Fixes #1635.

Let Store#store support large amounts of data

---

nanoc-core/lib/nanoc/core.rb
nanoc-core/lib/nanoc/core/action_sequence_store.rb
nanoc-core/lib/nanoc/core/binary_compiled_content_cache.rb
nanoc-core/lib/nanoc/core/checksum_store.rb
nanoc-core/lib/nanoc/core/dependency_store.rb
nanoc-core/lib/nanoc/core/outdatedness_store.rb
nanoc-core/lib/nanoc/core/store.rb
nanoc-core/lib/nanoc/core/textual_compiled_content_cache.rb

This lets `Store` write/read compressed data, using Ruby’s built in [Zlib](https://ruby-doc.org/stdlib-3.1.2/libdoc/zlib/rdoc/Zlib.html).
The gains can be significant: for example, one site went from a 2+ GiB `compiled_content.data.db` to one that is 220 MiB.
I’ve opted not to have an upgrade path; the next version of Nanoc will ignore the files in `tmp/nanoc/` and do a full recompile. I think it’s not worth creating an upgrade path as these files are not meant to be permanent.
The performance hit seems to be negligible. Take a look at this:
```
git @ main
Nanoc::Core::DependencyStore │ 5.38s
Nanoc::Core::DependencyStore │ 3.57s
Nanoc::Core::DependencyStore │ 5.37s
Nanoc::Core::DependencyStore │ 3.47s
Nanoc::Core::DependencyStore │ 5.57s
Nanoc::Core::DependencyStore │ 3.55s …
```

Let Store compress data

---

nanoc-core/lib/nanoc/core/item.rb
nanoc-core/lib/nanoc/core/layout.rb
nanoc-core/spec/nanoc/core/item_spec.rb
nanoc-core/spec/nanoc/core/layout_spec.rb

This fixes the implementation of `Item#reference` and `Layout#reference` so that those methods return the correct value even after their `identifier` has changed.
Executing `@_reference = nil` isn’t really the cleanest solution, but it fixes the problem.
This likely fixes #1640.
Bug introduced in https://github.com/nanoc/nanoc/pull/1603.

Fix broken {Item,Layout}#reference

---

Gemfile

RDiscount does not compile with clang 16 (see https://github.com/davidfstr/rdiscount/issues/155). This disables RDiscount for now.
n/a
n/a

Disable RDiscount on clang 16

---

nanoc-dart-sass/lib/nanoc/dart_sass/filter.rb
nanoc-dart-sass/spec/nanoc/dart_sass/filter/nanoc_importer_spec.rb
nanoc-dart-sass/spec/nanoc/dart_sass/filter_spec.rb

This supports more types of paths in the nanoc-dart-sass filter:
* Full paths: `/assets/style/colors.scss`
* (NEW) Full paths without extension: `/assets/style/colors`
* (NEW) Relative paths with dot: `./colors.scss`, `./colors`
* (NEW) Relative paths without dot: `colors.scss`, `colors`
Fixes #1646.

Support relative paths in nanoc-dart-sass filter

---

Gemfile
nanoc/spec/nanoc/filters/colorize_syntax/rouge_spec.rb

The exact contents produced by the GitHub theme in rouge 4 has been updated and this PR adapts the test to pass against rouge 4 (it will fail against rouge < 4 given the output is different).

Adapt tests to rouge 4

---

nanoc-cli/lib/nanoc/cli/error_handler.rb
nanoc-cli/spec/nanoc/cli/error_handler_spec.rb
nanoc-dart-sass/lib/nanoc/dart_sass/filter.rb

If an error implements `#full_message`, it will be printed after the error detail. This makes the `nanoc-dart-sass` errors much more interesting:
```
Captain! We’ve been hit!
Sass::CompileError: Undefined mixin.
Error: Undefined mixin.
╷
9 │   @include oops;
│   ^^^^^^^^^^^^^
╵
nanoc:/assets/style/_2021q4_common.* 9:3  @use
- 7:1                                     root stylesheet
Current item: /assets/style/2021q4.scss (:default representation)
```
n/a

Make error handler print #full_message if available

---

.rubocop_todo.yml
nanoc-dart-sass/lib/nanoc/dart_sass/filter.rb

In sass-embedded 1.68.0, there is a breaking change in importer function signature.
See: https://github.com/ntkme/sass-embedded-host-ruby/pull/156

Update for breaking change in sass-embedded 1.68.0

---

nanoc-cli/lib/nanoc/cli/commands/create-site.rb

The initial rules file contains an example for handling `.md` files but doesn’t set the correct extension for the resulting `.html` file. This change strips the `.md` extension and adds a `.html` extension.
* Tests

fix: wrong extension for non-index .md files

---

nanoc-cli/lib/nanoc/cli/commands/create-site.rb
nanoc/test/orig_cli/commands/test_create_site.rb

Bundler is established well enough that a default `Gemfile` with `nanoc` in it absolutely makes sense.
n/a

Add Gemfile

---

nanoc-cli/lib/nanoc/cli/error_handler.rb
nanoc-cli/spec/nanoc/cli/error_handler_spec.rb

SIGINT and SIGTERM would make Nanoc exit immediately without going through the proper shutdown process. The outdatedness information was not written to disk properly, which means that re-running `nanoc compile` after an interrupt would yield incorrect results.
`#exit!` exits immediately, while `#exit` raises an exception which Nanoc can (and should) handle.
In addition, this makes interrupts exit with status code 1, which should’ve been the case before already anyway.
Testing out this solution properly is cumbersome: I could not figure out a good way to test this in an automated way.
This is not the ideal solution, because Nanoc ideally would be written in a way that a sudden kill (e.g. also SIGKILL) would leave the state information consistent and usable. Such a change would require some …

Do cleanup on SIGINT/SIGTERM

---

nanoc-cli/spec/nanoc/cli/compile_listeners/file_action_printer_spec.rb
nanoc-cli/spec/nanoc/cli/compile_listeners/timing_recorder_spec.rb
nanoc-core/spec/nanoc/core/compilation_stage_spec.rb
nanoc-core/spec/nanoc/core/instrumentor_spec.rb

This replaces `timecop` with mocking `Process.clock_gettime(Process::CLOCK_MONOTONIC, :nanosecond)` directly, which seems more reliable.
I don’t know what happened to make timecop break, and my investigation hasn’t turned up anything.
Also: the `stage_ran` *does* need to be sent on error. I am not sure why that test passed in the past; the test likely was wrong (but no clear way to verify that).
n/a
(Add issue IDs for related issues here.)

Fix time/duration tests

---

nanoc-cli/lib/nanoc/cli/commands/create-site.rb

The `nanoc-cli` gem doesn’t depend on the `nanoc` gem (but the other way around) so it shouldn’t be using `Nanoc::`.
n/a
This fixes #1670.

Don’t refer to Nanoc:: from nanoc-cli gem

---

nanoc-core/nanoc-core.gemspec

This allows psych 5.x to be used.
n/a
Fixes #1671.

Allow psych 5.x

---

nanoc-core/lib/nanoc/core/config_loader.rb
nanoc-core/lib/nanoc/core/yaml_loader.rb
nanoc-core/nanoc-core.manifest
nanoc-core/spec/nanoc/core/yaml_loader_spec.rb
nanoc/lib/nanoc/data_sources/filesystem.rb
nanoc/lib/nanoc/data_sources/filesystem/parser.rb

Hi @denisdefreyne, it's been a long time since we've last been in touch. How are you? :)
This is the fix for #1676. See details there.
FYI, the last commit is solely a refactoring to establish single responsibility for YAML parser invocations, while the prior commits fix the invocations in the multiple places where they occurred.
3 commits:
- commit 1: Fix YAML invocation for `nanoc.yaml`
- commit 2: Fix YAML invocations in other places
- commit 3: Factor out business rules for YAML invocation
=> single responsibility, less verbose YAML access, centrally testable (test included)

Return of the YAML aliases :)

---

nanoc-cli/lib/nanoc/cli/commands/create-site.rb

Replace the "fallthrough" rule with the convenience method `passthrough` to demonstrate its use and make the default rules shorter.
Sorry, I have no idea whether any of this will be necessary for this change.
None I’m aware of.

feat: show use of 'passthrough' in default config

---

.github/workflows/ruby.yml

Ruby 3.1 and the prior versions have to use rubygems v3.4.9 or later to build native extension. The most concise instruction I've found is here: https://github.com/ruby/psych/discussions/607#discussioncomment-7233953.
In this nanoc/nanoc repository, this issue has not been made apparent since it has apparently been referencing cached installations in the CI, until #1679 sees the following error (quoted from https://github.com/nanoc/nanoc/actions/runs/7328290703/job/19956352783?pr=1679)
<details>
<summary>Details</summary>
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory:
/home/runner/work/nanoc/nanoc/vendor/bundle/ruby/2.7.0/gems/mini_racer-0.6.4/ext/mini_racer_extension
/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/ruby -I …
```

Use rubygems version 3.4.9 on CI

---

nanoc-cli/nanoc-cli.gemspec

This PR adds a runtime dependency on pry to nanoc-cli so it does not fail when the application's Gemfile does not have pry.
I suppose that in the relatively old days pry was so prevalent that this was not thought of as a problem. Though nowadays irb is getting popularized again which sometimes displaces pry, when it becomes a problem.
None. 
Closes #1678.

Specify pry as one of nanoc-cli's runtime dependencies

---

nanoc-core/lib/nanoc/core.rb
nanoc-core/nanoc-core.gemspec
nanoc/lib/nanoc.rb

Ruby 3.3 still comes with `base64` as a gem, but future versions of Ruby won’t. This adds the `base64` gem as a dependency, and so Nanoc is future-proofed.
n/a
n/a

Add base64 as a gem dependency

---

nanoc-cli/lib/nanoc/cli/cleaning_stream.rb
nanoc-cli/spec/nanoc/cli/cleaning_stream_spec.rb

This fixes the following potential error:
```
NoMethodError: private method `printf' called for an instance of Nanoc::CLI::CleaningStream
```
n/a

Forward CleaningStream#printf

---

nanoc-core/lib/nanoc/core/checksummer.rb
nanoc-core/spec/nanoc/core/action_sequence_spec.rb
nanoc-core/spec/nanoc/core/checksummer_spec.rb
nanoc-core/spec/nanoc/core/processing_actions/filter_spec.rb
nanoc-core/spec/nanoc/core/processing_actions/layout_spec.rb
nanoc/spec/nanoc/core/checksummer_spec.rb

The new implementation is faster because of two reasons:
- It more aggressively avoids calculating checksums of already-calculated items
- It effectfully updates a hash rather than using Immutable::Set
Preliminary tests suggest a 30% speedup, but I have not at all tested this out properly.
It is also more correct because it replaces use of <recur> with a numerical reference to a previously-seen object.
Each newly checksummed object will have a number suffix, e.g. `Array#5<…>`. Each previously seen object will have an @-reference, e.g. `Array#9<@4,@5,>`.
This will invalidate existing stored checksums in Nanoc sites, but it is unavoidable and worth the tradeoff.
This does not fix #1692 yet, but it brings the checksummer in a better state to handle it.

Make Checksummer faster and more correct

---

.rubocop.yml
nanoc-core/lib/nanoc/core/core_ext/array.rb
nanoc-core/spec/nanoc/core/action_sequence_spec.rb
nanoc-core/spec/nanoc/core/config_view_spec.rb
nanoc-core/spec/nanoc/core/identifiable_collection_spec.rb

This enables new Rubocop cops that Rubocop complains about.
The `Style/MapIntoArray` cop needed some code changes, mostly sensible ones: no need to build arrays with `#each` when there is `#map`.
n/a

Enable new Rubocop cops

---

nanoc-checking/lib/nanoc/checking/checks/external_links.rb
nanoc-checking/spec/nanoc/checking/checks/external_links_spec.rb

This makes the `external_links` check not error on `javascript:` URLs.
Fixes #1689.

nanoc-checking: Handle javascript: URLs

---

nanoc-core/lib/nanoc/core/checksummer.rb

This removes dead code in the checksummer: `#calc_v1` and `#update_v1` were kept around for performance comparison purposes, but are no longer needed.
n/a
n/a

Remove obsolete checksummer code

---

nanoc-dart-sass/lib/nanoc/dart_sass/filter.rb
nanoc-dart-sass/spec/nanoc/dart_sass/filter/nanoc_importer_spec.rb

This makes nanoc-dart-sass support importing partials (e.g. `@import 'foundation';` loads `_foundation.scss`) and directory imports (e.g. `@import 'foundation';` loads `foundation/_index.scss`).
It also handles ambiguous better: if multiple items match, an error is raised.
It was tough to reuse [the existing `sass-embedded-shim-ruby` implementation](https://github.com/sass-contrib/sassc-embedded-shim-ruby/blob/72399fda8dcc3eb511d7914fedf6e9d4a705d073/lib/sassc/embedded.rb#L226-L295) because nanoc-dart-sass allows Nanoc-style patterns in its imports, which regular dart-sass doesn’t do. It’s both a drawback and an advantage.
- #1690
- #1691

nanoc-dart-sass: Support partial and directory imports

---

Gemfile
nanoc-checking/lib/nanoc/checking/checks/internal_links.rb
nanoc-checking/lib/nanoc/checking/link_collector.rb
nanoc-checking/spec/nanoc/checking/checks/external_links_spec.rb
nanoc-checking/spec/nanoc/checking/checks/internal_links_spec.rb
nanoc-checking/test/helper.rb
nanoc-checking/test/nanoc/checking/test_link_collector.rb
nanoc/test/helper.rb

If there are spaces in the path to the Nanoc site or in any filename in the output directory, the `internal_links` check will fail with “bad URI” errors. This fixes that.
`addressable` is added as a development dependency for convenience, but it’s probably a good idea to use it as a replacement for `URI` to get rid of the hacky space handling and instead use `Addressable::URI.convert_path`. But that is for later.
n/a

Support paths with spaces in internal_links check

---

.github/workflows/ruby.yml
.rubocop.yml
guard-nanoc/guard-nanoc.gemspec
nanoc-checking/nanoc-checking.gemspec
nanoc-cli/nanoc-cli.gemspec
nanoc-core/nanoc-core.gemspec
nanoc-dart-sass/nanoc-dart-sass.gemspec
nanoc-deploying/nanoc-deploying.gemspec
nanoc-external/nanoc-external.gemspec
nanoc-live/nanoc-live.gemspec
nanoc-org-mode/nanoc-org-mode.gemspec
nanoc-spec/nanoc-spec.gemspec
nanoc-tilt/nanoc-tilt.gemspec
nanoc/nanoc.gemspec

The minimum Ruby version can be set to 3.1, because Ruby 2.7 and 3.0 are both end-of-life.
n/a
n/a

Set minimum Ruby version to 3.1

---

nanoc-cli/lib/nanoc/cli/compile_listeners/file_action_printer.rb
nanoc/test/orig_cli/commands/test_prune.rb

This changes the `delete` lines, emitted when pruning stale files from the output directory, to have relative paths, rather than absolute ones:
```
delete  output/assets/style/typewritten_r7cl9-xmrxt-fnmvv.css
```
This is consistent with the other emitted lines.
n/a
n/a

Make `delete` log lines use relative paths

---

.rubocop.yml
nanoc-cli/lib/nanoc/cli/commands/compile.rb
nanoc-core/lib/nanoc/core/compilation_stages/compile_reps.rb
nanoc-core/lib/nanoc/core/compiler.rb
nanoc-core/lib/nanoc/core/compiler_loader.rb
nanoc-core/spec/nanoc/core/compilation_stages/compile_reps_spec.rb
nanoc-core/spec/nanoc/core/compiler_spec.rb
nanoc-live/lib/nanoc/live/command_runners/live.rb
nanoc-live/lib/nanoc/live/commands/live.rb
nanoc-live/lib/nanoc/live/live_recompiler.rb
nanoc-live/spec/nanoc/live/live_recompiler_spec.rb
nanoc/spec/nanoc/integration/compile_command_spec.rb

This adds a `--focus` option to the `compile` and `live` commands, which take a pattern that specifies which items to compile. For example:
```bash
$ bundle exec nanoc compile --focus="/assets/style/**/*"
```
```bash
$ bundle exec nanoc live --focus="/assets/style/**/*"
```
When `--focus` is specified, a caution message will be printed, to make it clear that *only part* of the site is compiled:
```
CAUTION: A --focus option is specified. Not the entire site has been compiled.
Re-run without --focus to compile the entire site.
```
n/a

Add --focus option

---

nanoc-core/nanoc-core.gemspec

Ruby 3.1+ comes with at least psych 4.0, which makes this dependency obsolete.
(Nanoc still uses psych, but there is no more explicit gem dependency.)
n/a
Fixes #1712.

Drop explicit dependency on psych

---

nanoc-dart-sass/spec/nanoc/dart_sass/filter_spec.rb

Dart Sass’ `@import` is deprecated and will start to function as regular CSS `@import` from Dart Sass 3.0 on.
No direct code changes are needed in Nanoc or the nanoc-dart-sass gem, but the tests emit a deprecation warning. This PR fixes that warning by switching to `@use` instead.
See https://sass-lang.com/documentation/breaking-changes/import/ for details.

nanoc-dart-sass: Replace @import with @use in tests

---

nanoc-core/lib/nanoc/core/utils.rb
nanoc-core/nanoc-core.manifest
nanoc-core/spec/nanoc/core/utils_spec.rb
nanoc-dart-sass/lib/nanoc/dart_sass/filter.rb
nanoc/lib/nanoc/data_sources/filesystem/tools.rb

On Windows, `File.expand_path` adds a drive identifier to the beginning (e.g. `C:`) which breaks things when a Nanoc path is expected (one that starts with a slash).
The fix isn’t particulary pretty, but I cannot come up with a better solution.
:warning: I also was not able to test this on Windows yet.
Fixes #1703.

Strip drive identifier from File.expand_path on Windows

---

nanoc-core/lib/nanoc/core/utils.rb

This makes the detection of Windows file paths (starting with a drive identifier, e.g. `C:\blah`) more reliable.
Tests? (This is hard to test automatically though.)
Fixes #1703, #1717.

Improve Windows file path detection

---

nanoc/lib/nanoc/filters/haml.rb
nanoc/test/filters/test_haml.rb

This makes the Haml filter compatible with the Rendering helper.
Fixes #1639.

Add missing _erbout binding to Haml filter

---

nanoc-core/lib/nanoc/core/pattern.rb
nanoc-core/spec/nanoc/core/string_pattern_spec.rb
nanoc/lib/nanoc.rb

This adds `Nanoc::Core::Patern#===` which makes it possible to use it in `case`/`when`:
```ruby
case s
when Nanoc::Pattern.from("/software/*")
when Nanoc::Pattern.from("/fiction/*")
end
```
In addition, this export `Nanoc::Core::Pattern` as `Nanoc::Pattern`. This needs documentation (the pattern class has been private/internal until now).

Add Pattern#=== and export it

---

nanoc/lib/nanoc/helpers/blogging.rb
nanoc/test/helpers/test_blogging.rb

This allows passing an `id_proc` argument to the blogging helper, to customize the ID generation. This is useful for when more control is required, e.g. when renaming items, or routing them to a different output location.

Add :id_proc to Blogging helper

---

Gemfile
nanoc-core/lib/nanoc/core.rb
nanoc-core/lib/nanoc/core/binary_compiled_content_cache.rb
nanoc-core/lib/nanoc/core/item_rep_writer.rb
nanoc-core/nanoc-core.gemspec
nanoc/spec/nanoc/regressions/gh_1572_spec.rb

`clonefile`, which is a good idea in general, should now be well supported across all operating systems. The compatibility issues should be a thing of the past.
- #1511 
- https://codeberg.org/da/ruby-clonefile

Make clonefile a hard dependency

---

nanoc-cli/lib/nanoc/cli/cleaning_stream.rb
nanoc-cli/spec/nanoc/cli/cleaning_stream_spec.rb

This makes `CleaningStream` use `Forwardable`/`def_delegator`, which simplifies the code quite a bit.

Simplify forwarding in CleaningStream

---

nanoc-cli/lib/nanoc/cli.rb

A follow-up to #1737. This makes `force_color`, `debug` and `verbosity` all use the way of being defined.

Simplify CLI attributes

---

nanoc-checking/lib/nanoc/checking/runner.rb
nanoc/spec/nanoc/regressions/gh_809_spec.rb

Similar to #1734: runs checks in parallel. This is what it looks like:
https://github.com/user-attachments/assets/aa9af20c-187a-425a-8ce0-ef07a00f3c70
Parallelism is currently set to 5, but is configurable. (I think it’s good to have a limit, but I’m not sure what it should be.)
I can’t imagine individual checks sharing state, so parallelising this should be possible without side effects. For that reason, like in ##1734, I think a feature flag wouldn’t be useful.
See #1734.

Run checks in parallel

---

nanoc-cli/lib/nanoc/cli/commands/show-data.rb
nanoc-core/lib/nanoc/core/dependency_props.rb
nanoc-core/lib/nanoc/core/outdatedness_checker.rb
nanoc-core/spec/nanoc/core/dependency_props_spec.rb

This changes `DependencyProps` to not eagerly convert its enumerable (`Array`) argument into a `Set` until it is necessary. This is faster.

Optimize DependencyProps: Don’t convert to Set until needed

---

nanoc-checking/lib/nanoc/checking/checks/external_links.rb
nanoc-checking/spec/nanoc/checking/checks/external_links_spec.rb
nanoc-core/lib/nanoc/core/configuration-schema.json

- Makes user agent for external links check configurable
- This is to bypass servers that blacklist certain user agent strings
n/a

external link check user agent configurable

---

Gemfile
nanoc-core/lib/nanoc/core.rb
nanoc-core/lib/nanoc/core/binary_compiled_content_cache.rb
nanoc-core/lib/nanoc/core/item_rep_writer.rb
nanoc-core/nanoc-core.gemspec
nanoc/spec/nanoc/regressions/gh_1572_spec.rb

[clonefile](https://codeberg.org/da/ruby-clonefile) unfortunately cannot be installed on Windows, and Windows support is needed.
This reverts commit 982575af3edc26e4a87b40c721da6104a4cbaaa1, but adds clonefile to the Gemfile.
The clonefile gem can still be installed, but it can’t be a hard dependency.
Fixes #1744.

Remove clonefile as a hard dependency

---

nanoc-checking/Rakefile
nanoc/Rakefile

`Rake::TestTask` has problems with spaces in paths, and since we’re using Minitest anyway (in addition to Rspec), it makes sense to use the Minitest-provided Rake task.

Replace Rake::TestTask with Minitest::TestTask
